/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __noreturn j_FEL_start(); // weak
void __noreturn FEL_start(); // weak
int nullsub_1(void); // weak
int __fastcall nullsub_2(_DWORD); // weak
int __fastcall sub_FFFF011C(int result);
int __fastcall sub_FFFF0138(_BYTE *a1);
int __fastcall sub_FFFF0160(int result, int a2, int a3);
_BYTE *__fastcall sub_FFFF0180(int a1, _BYTE *a2);
int __fastcall sub_FFFF0200(int a1, int a2, int a3, int *a4);
int __fastcall sub_FFFF026C(int result, int a2, int *a3);
int __fastcall sub_FFFF02DC(int a1, int a2, int a3, int a4);
int __fastcall sub_FFFF0350(int a1, int a2);
int __fastcall sub_FFFF03A4(int a1, int a2);
int *__fastcall sub_FFFF03C0(int a1, int a2);
int __fastcall sub_FFFF03FC(int a1);
int __fastcall sub_FFFF047C(int a1, int a2, int a3, int a4);
int __fastcall sub_FFFF04C8(int a1, int a2, int a3, int a4);
signed int __fastcall sub_FFFF0514(int a1, int a2);
signed int __fastcall sub_FFFF058C(int a1, int a2);
int __fastcall sub_FFFF061C(int a1, int a2);
int __fastcall sub_FFFF064C(int a1, __int16 a2, int a3, int a4);
int __fastcall sub_FFFF06A0(int a1, _BYTE *a2, int a3);
void __fastcall sub_FFFF06E4(int a1, int a2, int a3, int a4);
void __fastcall __noreturn sub_FFFF084C(int a1);
int __fastcall sub_FFFF086C(int result);
int __fastcall sub_FFFF0878(int result);
int __fastcall sub_FFFF0884(int result);
_BYTE *__fastcall sub_FFFF0890(_BYTE *result, char *a2, int a3);
_BYTE *__fastcall sub_FFFF08B8(_BYTE *result, char a2, int a3);
int sub_FFFF0924();
unsigned int sub_FFFF093C();
unsigned int sub_FFFF0950();
int __fastcall sub_FFFF0964(int result);
int sub_FFFF0970();
int __fastcall sub_FFFF097C(int result);
int __fastcall sub_FFFF09E0(int result);
_BYTE *__fastcall sub_FFFF0A20(_BYTE *result);
int __fastcall sub_FFFF0A60(int result);
int __fastcall sub_FFFF0A94(int result);
_DWORD *__fastcall sub_FFFF0AC8(_DWORD *result, int a2, int a3);
void nullsub_4();
void nullsub_5();
void nullsub_6();
int __fastcall sub_FFFF0AE0(int result, int a2, int a3);
int __fastcall sub_FFFF0B74(int result, int a2, int a3, int a4);
int __fastcall sub_FFFF0B98(int result, int a2);
int __fastcall sub_FFFF0BC4(int result, int a2);
int __fastcall sub_FFFF0BF4(int result, int a2);
_DWORD *__fastcall sub_FFFF0C24(_DWORD *result, int a2, int a3, int a4);
int sub_FFFF0C34();
int *sub_FFFF0C50();
int sub_FFFF0CB4();
int sub_FFFF0CCC();
signed int sub_FFFF0D08();
unsigned int sub_FFFF0D50();
BOOL sub_FFFF0D68();
int *sub_FFFF0DA0();
int __fastcall sub_FFFF0E00(int a1);
int __fastcall sub_FFFF0E98(int a1);
int __fastcall sub_FFFF0EBC(int a1);
int __fastcall sub_FFFF0F70(int a1);
signed int __fastcall sub_FFFF0FA8(int a1, _DWORD *a2, _DWORD *a3);
int __fastcall nullsub_3(_DWORD); // weak
int __fastcall sub_FFFF1078(int a1, int a2, char a3);
signed int __fastcall sub_FFFF10A4(int a1, int a2, _BYTE *a3, int a4);
signed int __fastcall sub_FFFF1224(int a1, int a2, int a3);
signed int __fastcall sub_FFFF13E4(int a1, int a2, int a3, int a4);
signed int __fastcall sub_FFFF15D8(int a1, int a2, int a3, int a4);
_DWORD *__fastcall sub_FFFF15FC(_DWORD *result);
int __fastcall sub_FFFF1610(_BYTE *a1);
signed int __fastcall sub_FFFF168C(int a1, _BYTE *a2, int a3, int a4);
int __fastcall sub_FFFF1784(int a1, unsigned __int8 *a2, int a3, int a4);
signed int __fastcall sub_FFFF18FC(int a1, int a2, int a3, int a4);
signed int __fastcall sub_FFFF1C08(signed int result, int a2);
int IRQ_handler();
_BYTE *sub_FFFF2000();
void __noreturn FEL_main();
signed int __fastcall sub_FFFF2258(int a1);
int __fastcall sub_FFFF22AC(int a1);
int __fastcall sub_FFFF22D0(int a1, int a2);
int __fastcall sub_FFFF22F0(int a1, int a2);
unsigned int __fastcall sub_FFFF2310(_BYTE *a1, _DWORD *a2, unsigned int a3);
unsigned int __fastcall sub_FFFF2380(_DWORD *a1, _DWORD *a2, int a3, unsigned int a4);
int __fastcall sub_FFFF2454(int result, int a2, unsigned int a3, unsigned int a4);
int __fastcall sub_FFFF2528(unsigned __int8 *a1);
_DWORD *__fastcall sub_FFFF2548(_DWORD *result, int *a2, unsigned int a3, int a4);
void __noreturn BRM_start();
void __fastcall set_boot_debug_flag__(int result);
unsigned int JTAG_GPIO_Enable();
void __noreturn BRM_main();
signed int __fastcall sub_FFFF4190(_DWORD *a1, unsigned int a2, int a3);
signed int sub_FFFF4228();
signed int sub_FFFF4350();
signed int load_SPI_1();
signed int __fastcall load_MMC(int a1);
signed int __fastcall sub_FFFF45E8(int a1, _DWORD *a2, _DWORD *a3);
signed int __fastcall sub_FFFF4750(_DWORD *a1);
signed int __fastcall sub_FFFF47D4(int a1, int a2);
signed int __fastcall sub_FFFF481C(int a1, int a2, int a3);
int __fastcall sub_FFFF4914(int a1);
signed int __fastcall sub_FFFF49F4(int *a1);
int __fastcall sub_FFFF4A68(int a1);
signed int __fastcall sub_FFFF4B08(int a1, _DWORD *a2, _DWORD *a3);
signed int __fastcall sub_FFFF4C50(int a1, int a2, unsigned int a3, int *a4);
signed int __fastcall sub_FFFF4E5C(_DWORD *a1);
signed int __fastcall sub_FFFF4EC0(int a1, _DWORD *a2);
signed int __fastcall sub_FFFF4F4C(int a1, _DWORD *a2);
signed int __fastcall sub_FFFF5088(int a1, _DWORD *a2);
signed int __fastcall sub_FFFF5270(int a1, _DWORD *a2);
signed int __fastcall sub_FFFF5380(_DWORD *a1);
signed int __fastcall sub_FFFF53F8(int a1, _DWORD *a2);
signed int __fastcall sub_FFFF5490(int a1, int a2, _DWORD *a3, int a4);
signed int __fastcall sub_FFFF5588(int a1, int a2, _DWORD *a3);
signed int __fastcall sub_FFFF5610(int a1, int a2, int *a3);
int __fastcall sub_FFFF5688(int a1);
signed int __fastcall sub_FFFF569C(int a1, int a2, int a3, int a4, int *a5);
signed int sub_FFFF57D0();
signed int sub_FFFF57EC();
signed int SPI0_Init();
unsigned int SPI0_DeInit();
signed int __fastcall DMA_busy_wait(int a1);
signed int __fastcall sub_FFFF5920(int a1);
signed int __fastcall sub_FFFF5954(unsigned int a1, int a2, int a3, int a4);
signed int __fastcall sub_FFFF5A78(unsigned int a1, int a2);
signed int __fastcall spi_loader_0__(int a1, int a2, int a3, int a4);
signed int __fastcall spi_loader_1__(int a1, int a2, int a3);
signed int sub_FFFF5C34();
int __fastcall get_loader_ptr__(int a1);
signed int __fastcall sub_FFFF5C94(unsigned int a1, int a2, int a3, int a4, int a5, unsigned int a6);
signed int load_SPI_2();
signed int __fastcall eGON_str_cmp(int a1, unsigned __int8 *a2);
BOOL __fastcall sub_FFFF5F2C(int *a1, unsigned int a2);
_DWORD *__fastcall sub_FFFF600C(_DWORD *result, int *a2, unsigned int a3, int a4);
_DWORD *__fastcall sub_FFFF6070(_DWORD *result, unsigned int a2);
int __fastcall sub_FFFF6240(unsigned int a1, unsigned int a2);
int __fastcall __noreturn jump_to(int (*a1)(void));

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_1; // weak
_UNKNOWN unk_8; // weak
int dword_10; // weak
_UNKNOWN unk_18; // weak
_UNKNOWN unk_30; // weak
_UNKNOWN unk_34; // weak
_UNKNOWN unk_38; // weak
_BYTE byte_48[4040]; // idb
_UNKNOWN unk_1010; // weak
_UNKNOWN unk_2710; // weak
_UNKNOWN unk_4E20; // weak
int dword_7D00; // weak
int dword_7D04; // weak
int dword_7D08; // weak
char byte_7D0C; // weak
_UNKNOWN unk_7E00; // weak
_DWORD dword_A100[1888]; // idb
_UNKNOWN unk_BE80; // weak
_UNKNOWN unk_C350; // weak
_UNKNOWN unk_EFE8; // weak
int dword_1C00004; // weak
int dword_1C02120; // weak
int dword_1C02124; // weak
int dword_1C02128; // weak
int dword_1C0212C; // weak
int dword_1C05004; // weak
int dword_1C05008; // weak
int dword_1C05010; // weak
int dword_1C05014; // weak
int dword_1C05018; // weak
int dword_1C05024; // weak
int dword_1C05030; // weak
int dword_1C05034; // weak
int dword_1C05038; // weak
char byte_1C05200; // weak
_UNKNOWN unk_1C05300; // weak
int dword_1C0F000[4096]; // idb
char byte_1C13000; // weak
_UNKNOWN unk_1C13004; // weak
_UNKNOWN unk_1C13008; // weak
_UNKNOWN unk_1C1300C; // weak
_UNKNOWN unk_1C13010; // weak
char byte_1C13040; // weak
char byte_1C13041; // weak
__int16 word_1C13042; // weak
char byte_1C13044; // weak
char byte_1C13046; // weak
char byte_1C13048; // weak
char byte_1C1304A; // weak
char byte_1C1304C; // weak
char byte_1C13050; // weak
_UNKNOWN unk_1C13080; // weak
__int16 word_1C13082; // weak
__int16 word_1C13084; // weak
int dword_1C13086; // weak
char byte_1C13090; // weak
__int16 word_1C13092; // weak
char byte_1C13094; // weak
__int16 word_1C13096; // weak
char byte_1C13098; // weak
int dword_1C13400; // weak
int dword_1C20000; // weak
int dword_1C20050; // weak
int dword_1C20054; // weak
int dword_1C20060; // weak
int dword_1C20088; // weak
int dword_1C2008C; // weak
int dword_1C200CC; // weak
int dword_1C202C0; // weak
int dword_1C20420; // weak
int dword_1C20424; // weak
int dword_1C20848; // weak
int dword_1C20864; // weak
int dword_1C208B4; // weak
int dword_1C208D0; // weak
int dword_1C20CB8; // weak
_UNKNOWN unk_FFFF6298; // weak


//----- (FFFF003C) --------------------------------------------------------
void __noreturn FEL_start()
{
  signed int v0; // r0

  __set_CPSR(0xD2u);
  __set_CPSR(__get_CPSR() & 0xFFFFFFE0 | 0xD3);
  __mcr(15, 0, __mrc(15, 0, 1, 0, 0) & 0xFFFFEF72, 1, 0, 0);
  dword_1C20050 = dword_1C20050 & 0xFFFCFFFF | 0x10000;
  dword_1C20054 = dword_1C20054 & 0xFFFFCC0F | (unsigned int)&unk_1010;
  dword_1C200CC = dword_1C200CC & 0xFFFFFFFD | 2;
  v0 = 50;
  do
    --v0;
  while ( v0 );
  dword_1C202C0 = dword_1C202C0 & 0xFEFFFFFF | 0x1000000;
  dword_1C20060 = dword_1C20060 & 0xFEFFFFFF | 0x1000000;
  dword_1C200CC = dword_1C200CC & 0xFFFFFFFE | 1;
  FEL_main();
}
// 1C20050: using guessed type int dword_1C20050;
// 1C20054: using guessed type int dword_1C20054;
// 1C20060: using guessed type int dword_1C20060;
// 1C200CC: using guessed type int dword_1C200CC;
// 1C202C0: using guessed type int dword_1C202C0;
// FFFF003C: using guessed type void __noreturn FEL_start();

//----- (FFFF011C) --------------------------------------------------------
int __fastcall sub_FFFF011C(int result)
{
  int v1; // r1

  v1 = 0;
  while ( *(_BYTE *)(result + 24) == 1 )
    ++v1;
  return result;
}

//----- (FFFF0138) --------------------------------------------------------
int __fastcall sub_FFFF0138(_BYTE *a1)
{
  _BYTE *v1; // r4
  int result; // r0

  v1 = a1;
  sub_FFFF08B8(a1, 0, 34);
  result = 0;
  v1[32] = 0;
  v1[33] = 0;
  return result;
}

//----- (FFFF0160) --------------------------------------------------------
int __fastcall sub_FFFF0160(int result, int a2, int a3)
{
  *(_DWORD *)result = a2;
  *(_DWORD *)(result + 4) = a3;
  *(_BYTE *)(result + 8) = 0;
  *(_DWORD *)(result + 16) = 0;
  *(_BYTE *)(result + 24) = 1;
  return result;
}

//----- (FFFF0180) --------------------------------------------------------
_BYTE *__fastcall sub_FFFF0180(int a1, _BYTE *a2)
{
  int v2; // r6
  _BYTE *v3; // r4
  char **v4; // r5
  int v5; // r3
  int v7; // [sp+0h] [bp-30h]

  v2 = a1;
  v3 = a2;
  v4 = *(char ***)(a1 + 52);
  sub_FFFF011C(*(_DWORD *)(a1 + 52));
  sub_FFFF08B8(&v7, 0, 32);
  sub_FFFF093C();
  sub_FFFF0160((int)v4, (int)&v7, 32);
  v3[32] = 1;
  sub_FFFF15D8(v2, (int)v4, 0, v5);
  sub_FFFF011C((int)v4);
  return sub_FFFF0890(v3, *v4, 34);
}

//----- (FFFF0200) --------------------------------------------------------
int __fastcall sub_FFFF0200(int a1, int a2, int a3, int *a4)
{
  int v4; // r4
  int v5; // r7
  int *v6; // r5
  int v7; // r8
  int v8; // r3

  v4 = a2;
  v5 = a3;
  v6 = a4;
  if ( a1 )
    v7 = *(_DWORD *)(a2 + 48);
  else
    v7 = *(_DWORD *)(a2 + 52);
  sub_FFFF011C(v7);
  *(_BYTE *)(v5 + 32) = 2;
  sub_FFFF093C();
  sub_FFFF0160(v7, *v6, v6[1]);
  sub_FFFF15D8(v4, v7, 0, v8);
  return sub_FFFF011C(v7);
}

//----- (FFFF026C) --------------------------------------------------------
int __fastcall sub_FFFF026C(int result, int a2, int *a3)
{
  int v3; // r7

  v3 = *(unsigned __int8 *)(a2 + 16);
  if ( v3 == 17 )
    return sub_FFFF0200(1, result, a2, a3);
  if ( v3 == 18 )
    result = sub_FFFF0200(0, result, a2, a3);
  return result;
}

//----- (FFFF02DC) --------------------------------------------------------
int __fastcall sub_FFFF02DC(int a1, int a2, int a3, int a4)
{
  int v4; // r5
  int v5; // r6
  int v6; // r3
  int v8; // [sp+0h] [bp-28h]
  int v9; // [sp+4h] [bp-24h]
  int v10; // [sp+8h] [bp-20h]
  int v11; // [sp+Ch] [bp-1Ch]

  v8 = a1;
  v10 = a3;
  v11 = a4;
  v4 = a1;
  v5 = *(_DWORD *)(a1 + 48);
  *(_BYTE *)(a2 + 32) = 3;
  v8 = 1398101825;
  v9 = sub_FFFF2528((unsigned __int8 *)(a2 + 4));
  v10 = 0;
  LOBYTE(v11) = 0;
  sub_FFFF093C();
  sub_FFFF0160(v5, (int)&v8, 13);
  sub_FFFF15D8(v4, v5, 0, v6);
  sub_FFFF011C(v5);
  return v8;
}

//----- (FFFF0350) --------------------------------------------------------
int __fastcall sub_FFFF0350(int a1, int a2)
{
  int v2; // r5
  int v3; // r4
  int v4; // r3
  int result; // r0
  int v6; // [sp+0h] [bp-30h]

  v2 = a1;
  v3 = a2;
  sub_FFFF0138(&v6);
  sub_FFFF0180(v2, &v6);
  sub_FFFF026C(v2, (int)&v6, (int *)v3);
  sub_FFFF02DC(v2, (int)&v6, v3, v4);
  result = 0;
  *(_BYTE *)(v3 + 8) = 0;
  return result;
}

//----- (FFFF03A4) --------------------------------------------------------
int __fastcall sub_FFFF03A4(int a1, int a2)
{
  return sub_FFFF0350(a1, a2);
}

//----- (FFFF03C0) --------------------------------------------------------
int *__fastcall sub_FFFF03C0(int a1, int a2)
{
  int v2; // r5
  int v3; // r4

  v2 = a1;
  v3 = a2;
  sub_FFFF08B8(&dword_7D04, 0, 12);
  dword_7D04 = v2;
  dword_7D08 = v3;
  byte_7D0C = 2;
  return &dword_7D04;
}
// 7D04: using guessed type int dword_7D04;
// 7D08: using guessed type int dword_7D08;
// 7D0C: using guessed type char byte_7D0C;

//----- (FFFF03FC) --------------------------------------------------------
int __fastcall sub_FFFF03FC(int a1)
{
  int v1; // r4
  int *v2; // r0
  char v4; // [sp+4h] [bp-2Ch]
  int v5; // [sp+Ch] [bp-24h]
  int v6; // [sp+10h] [bp-20h]
  __int16 v7; // [sp+14h] [bp-1Ch]
  char v8; // [sp+16h] [bp-1Ah]
  char v9; // [sp+17h] [bp-19h]
  int v10; // [sp+18h] [bp-18h]

  v1 = a1;
  sub_FFFF08B8(&v4, 0, 32);
  sub_FFFF0890(&v4, "AWUSBFEX", 8);
  v5 = 1467136;
  v6 = 1;
  v7 = 1;
  v8 = 68;
  v9 = 8;
  v10 = 32256;
  v2 = sub_FFFF03C0((int)&v4, 32);
  return sub_FFFF0350(v1, (int)v2);
}

//----- (FFFF047C) --------------------------------------------------------
int __fastcall sub_FFFF047C(int a1, int a2, int a3, int a4)
{
  int v4; // r4
  int *v5; // r0
  int v7; // [sp+0h] [bp-20h]
  int v8; // [sp+8h] [bp-18h]
  int v9; // [sp+Ch] [bp-14h]

  v7 = a1;
  v8 = a3;
  v9 = a4;
  v4 = a1;
  sub_FFFF08B8(&v7, 0, 16);
  v7 = 1;
  v5 = sub_FFFF03C0((int)&v7, 16);
  sub_FFFF0350(v4, (int)v5);
  return v7;
}

//----- (FFFF04C8) --------------------------------------------------------
int __fastcall sub_FFFF04C8(int a1, int a2, int a3, int a4)
{
  int v4; // r4
  int *v5; // r0
  int v7; // [sp+0h] [bp-20h]
  int v8; // [sp+8h] [bp-18h]
  int v9; // [sp+Ch] [bp-14h]

  v7 = a1;
  v8 = a3;
  v9 = a4;
  v4 = a1;
  sub_FFFF08B8(&v7, 0, 16);
  v7 = 32768002;
  v5 = sub_FFFF03C0((int)&v7, 16);
  sub_FFFF0350(v4, (int)v5);
  return v7;
}

//----- (FFFF0514) --------------------------------------------------------
signed int __fastcall sub_FFFF0514(int a1, int a2)
{
  int v2; // r6
  int v3; // r4
  int v5; // r8
  int v6; // r0
  int *v7; // r0

  v2 = a1;
  v3 = a2;
  if ( !a2 )
    return 1;
  if ( !sub_FFFF2528((unsigned __int8 *)(a2 + 8)) )
    return 1;
  v5 = sub_FFFF2528((unsigned __int8 *)(v3 + 8));
  v6 = sub_FFFF2528((unsigned __int8 *)(v3 + 4));
  v7 = sub_FFFF03C0(v6, v5);
  sub_FFFF0350(v2, (int)v7);
  return 0;
}

//----- (FFFF058C) --------------------------------------------------------
signed int __fastcall sub_FFFF058C(int a1, int a2)
{
  int v2; // r6
  int v3; // r4
  int v5; // r8
  int v6; // r0
  int *v7; // r0

  v2 = a1;
  v3 = a2;
  if ( !a2 )
    return 1;
  if ( !sub_FFFF2528((unsigned __int8 *)(a2 + 8)) )
    return 1;
  v5 = sub_FFFF2528((unsigned __int8 *)(v3 + 8));
  v6 = sub_FFFF2528((unsigned __int8 *)(v3 + 4));
  v7 = sub_FFFF03C0(v6, v5);
  sub_FFFF0350(v2, (int)v7);
  return 0;
}

//----- (FFFF061C) --------------------------------------------------------
int __fastcall sub_FFFF061C(int a1, int a2)
{
  int result; // r0

  if ( a2 )
    result = sub_FFFF2528((unsigned __int8 *)(a2 + 4));
  else
    result = -1;
  return result;
}

//----- (FFFF064C) --------------------------------------------------------
int __fastcall sub_FFFF064C(int a1, __int16 a2, int a3, int a4)
{
  int v4; // r6
  __int16 v5; // r4
  char v6; // r5
  int *v7; // r0
  int v9; // [sp+0h] [bp-20h]
  int v10; // [sp+4h] [bp-1Ch]

  v9 = a3;
  v10 = a4;
  v4 = a1;
  v5 = a2;
  v6 = a3;
  sub_FFFF08B8(&v9, 0, 8);
  LOWORD(v9) = -1;
  HIWORD(v9) = v5;
  LOBYTE(v10) = v6;
  v7 = sub_FFFF03C0((int)&v9, 8);
  return sub_FFFF0350(v4, (int)v7);
}

//----- (FFFF06A0) --------------------------------------------------------
int __fastcall sub_FFFF06A0(int a1, _BYTE *a2, int a3)
{
  int v3; // r6
  _BYTE *v4; // r4
  int v5; // r5
  int *v6; // r0

  v3 = a1;
  v4 = a2;
  v5 = a3;
  sub_FFFF08B8(a2, 0, a3);
  v6 = sub_FFFF03C0((int)v4, v5);
  return sub_FFFF03A4(v3, (int)v6);
}

//----- (FFFF06E4) --------------------------------------------------------
void __fastcall sub_FFFF06E4(int a1, int a2, int a3, int a4)
{
  int v4; // r6
  int v5; // r9
  int v6; // r1
  int v7; // r2
  int v8; // r3
  __int16 v9; // r8
  int v10; // r0
  void (__fastcall *v11)(signed int); // r5
  int v12; // r3
  signed int v13; // r0
  int v14; // [sp+0h] [bp-30h]
  int v15; // [sp+4h] [bp-2Ch]
  int v16; // [sp+8h] [bp-28h]
  int v17; // [sp+Ch] [bp-24h]

  v14 = a1;
  v15 = a2;
  v16 = a3;
  v17 = a4;
  v4 = a1;
  v5 = 1;
  sub_FFFF06A0(a1, &v14, 16);
  v9 = HIWORD(v14);
  if ( (unsigned __int16)v14 == 16 )
    goto LABEL_20;
  if ( (signed int)(unsigned __int16)v14 > 16 )
  {
    v10 = (unsigned __int16)v14 - 257;
    if ( (unsigned __int16)v14 == 257 )
    {
      v5 = sub_FFFF0514(v4, (int)&v14);
      goto LABEL_20;
    }
    if ( v10 == 1 )
    {
      v11 = (void (__fastcall *)(signed int))sub_FFFF061C(v4, (int)&v14);
      sub_FFFF064C(v4, v9, 0, v12);
      v13 = sub_FFFF2258(v4);
      v11(v13);
      return;
    }
    if ( v10 == 2 )
    {
      v5 = sub_FFFF058C(v4, (int)&v14);
      goto LABEL_20;
    }
LABEL_19:
    v5 = 1;
    goto LABEL_20;
  }
  switch ( (unsigned __int16)v14 )
  {
    case 1u:
      sub_FFFF03FC(v4);
      v5 = 0;
      goto LABEL_20;
    case 2u:
      goto LABEL_20;
    case 3u:
      sub_FFFF04C8(v4, v6, v7, v8);
      v5 = 0;
      goto LABEL_20;
  }
  if ( (unsigned __int16)v14 != 4 )
    goto LABEL_19;
  sub_FFFF047C(v4, v6, v7, v8);
  v5 = 0;
LABEL_20:
  sub_FFFF064C(v4, v9, v5, v8);
}

//----- (FFFF084C) --------------------------------------------------------
void __fastcall __noreturn sub_FFFF084C(int a1)
{
  int v1; // r4
  int i; // r5
  int v3; // r1
  int v4; // r2
  int v5; // r3

  v1 = a1;
  for ( i = 0; ; ++i )
  {
    nullsub_1();
    sub_FFFF06E4(v1, v3, v4, v5);
  }
}
// FFFF0114: using guessed type int nullsub_1(void);

//----- (FFFF086C) --------------------------------------------------------
int __fastcall sub_FFFF086C(int result)
{
  *(_BYTE *)(result + 24) = 0;
  return result;
}

//----- (FFFF0878) --------------------------------------------------------
int __fastcall sub_FFFF0878(int result)
{
  *(_BYTE *)(result + 24) = 0;
  return result;
}

//----- (FFFF0884) --------------------------------------------------------
int __fastcall sub_FFFF0884(int result)
{
  *(_BYTE *)(result + 24) = 0;
  return result;
}

//----- (FFFF0890) --------------------------------------------------------
_BYTE *__fastcall sub_FFFF0890(_BYTE *result, char *a2, int a3)
{
  _BYTE *v3; // r3
  char *v4; // r12
  char v5; // t1
  bool v6; // zf

  v3 = result;
  v4 = a2;
  while ( 1 )
  {
    v6 = a3-- == 0;
    if ( v6 )
      break;
    v5 = *v4++;
    *v3++ = v5;
  }
  return result;
}

//----- (FFFF08B8) --------------------------------------------------------
_BYTE *__fastcall sub_FFFF08B8(_BYTE *result, char a2, int a3)
{
  _BYTE *i; // r3
  bool v4; // zf

  for ( i = result; ; ++i )
  {
    v4 = a3-- == 0;
    if ( v4 )
      break;
    *i = a2;
  }
  return result;
}

//----- (FFFF0924) --------------------------------------------------------
int sub_FFFF0924()
{
  int result; // r0

  result = dword_1C20420 | 0x4000000;
  dword_1C20420 |= 0x4000000u;
  return result;
}
// 1C20420: using guessed type int dword_1C20420;

//----- (FFFF093C) --------------------------------------------------------
unsigned int sub_FFFF093C()
{
  unsigned int result; // r0

  result = __get_CPSR() | 0x80;
  __set_CPSR(result);
  return result;
}

//----- (FFFF0950) --------------------------------------------------------
unsigned int sub_FFFF0950()
{
  unsigned int result; // r0

  result = __get_CPSR() & 0xFFFFFF7F;
  __set_CPSR(result);
  return result;
}

//----- (FFFF0964) --------------------------------------------------------
int __fastcall sub_FFFF0964(int result)
{
  LOBYTE(word_1C13042) = result;
  return result;
}
// 1C13042: using guessed type __int16 word_1C13042;

//----- (FFFF0970) --------------------------------------------------------
int sub_FFFF0970()
{
  return (unsigned __int8)word_1C13042;
}
// 1C13042: using guessed type __int16 word_1C13042;

//----- (FFFF097C) --------------------------------------------------------
int __fastcall sub_FFFF097C(int result)
{
  *(_BYTE *)result = 18;
  *(_BYTE *)(result + 1) = 1;
  *(_WORD *)(result + 2) = 272;
  *(_BYTE *)(result + 4) = 0;
  *(_BYTE *)(result + 5) = 0;
  *(_BYTE *)(result + 6) = 0;
  *(_BYTE *)(result + 7) = 64;
  *(_WORD *)(result + 8) = 7994;
  *(_WORD *)(result + 10) = (unsigned int)&unk_EFE8;
  *(_WORD *)(result + 12) = 691;
  *(_BYTE *)(result + 14) = 0;
  *(_BYTE *)(result + 15) = 0;
  *(_BYTE *)(result + 16) = 0;
  *(_BYTE *)(result + 17) = 1;
  return result;
}

//----- (FFFF09E0) --------------------------------------------------------
int __fastcall sub_FFFF09E0(int result)
{
  *(_BYTE *)result = 10;
  *(_BYTE *)(result + 1) = 2;
  *(_WORD *)(result + 2) = 32;
  *(_BYTE *)(result + 4) = 1;
  *(_BYTE *)(result + 5) = 1;
  *(_BYTE *)(result + 6) = 0;
  *(_BYTE *)(result + 7) = -128;
  *(_BYTE *)(result + 8) = -106;
  return result;
}

//----- (FFFF0A20) --------------------------------------------------------
_BYTE *__fastcall sub_FFFF0A20(_BYTE *result)
{
  *result = 9;
  result[1] = 4;
  result[2] = 0;
  result[3] = 0;
  result[4] = 2;
  result[5] = -1;
  result[6] = -1;
  result[7] = -1;
  result[8] = 0;
  return result;
}

//----- (FFFF0A60) --------------------------------------------------------
int __fastcall sub_FFFF0A60(int result)
{
  *(_BYTE *)result = 7;
  *(_BYTE *)(result + 1) = 5;
  *(_WORD *)(result + 4) = 64;
  *(_BYTE *)(result + 2) = 1;
  *(_BYTE *)(result + 3) = 2;
  *(_BYTE *)(result + 6) = 0;
  return result;
}

//----- (FFFF0A94) --------------------------------------------------------
int __fastcall sub_FFFF0A94(int result)
{
  *(_BYTE *)result = 7;
  *(_BYTE *)(result + 1) = 5;
  *(_WORD *)(result + 4) = 64;
  *(_BYTE *)(result + 2) = -126;
  *(_BYTE *)(result + 3) = 2;
  *(_BYTE *)(result + 6) = 0;
  return result;
}

//----- (FFFF0AC8) --------------------------------------------------------
_DWORD *__fastcall sub_FFFF0AC8(_DWORD *result, int a2, int a3)
{
  *result = a3;
  result[1] = a2;
  return result;
}

//----- (FFFF0AE0) --------------------------------------------------------
int __fastcall sub_FFFF0AE0(int result, int a2, int a3)
{
  *(_BYTE *)(result + 5) = 0;
  *(_BYTE *)(result + 6) = 0;
  *(_DWORD *)result = 0;
  *(_BYTE *)(result + 4) = 0;
  *(_DWORD *)(result + 8) = 64;
  *(_DWORD *)(result + 12) = 0;
  *(_BYTE *)(result + 21) = *(_BYTE *)(a2 + 2);
  *(_BYTE *)(result + 22) = *(_BYTE *)(a2 + 3);
  *(_DWORD *)(result + 16) = a2;
  *(_BYTE *)(result + 20) = 1;
  *(_DWORD *)(result + 24) = *(unsigned __int16 *)(a2 + 4);
  *(_DWORD *)(result + 28) = 0;
  *(_BYTE *)(result + 37) = *(_BYTE *)(a3 + 2);
  *(_BYTE *)(result + 38) = *(_BYTE *)(a3 + 3);
  *(_DWORD *)(result + 32) = a3;
  *(_BYTE *)(result + 36) = 2;
  *(_DWORD *)(result + 40) = *(unsigned __int16 *)(a3 + 4);
  *(_DWORD *)(result + 44) = 0;
  *(_DWORD *)(result + 48) = 0;
  *(_BYTE *)(result + 52) = 0;
  *(_DWORD *)(result + 56) = 0;
  *(_BYTE *)(result + 60) = 0;
  *(_BYTE *)(result + 61) = 0;
  return result;
}

//----- (FFFF0B74) --------------------------------------------------------
int __fastcall sub_FFFF0B74(int result, int a2, int a3, int a4)
{
  *(_DWORD *)result = a2;
  *(_BYTE *)(result + 4) = 0;
  *(_DWORD *)(result + 8) = 0;
  *(_DWORD *)(result + 20) = a3;
  *(_DWORD *)(result + 24) = 0;
  *(_DWORD *)(result + 12) = a4;
  *(_DWORD *)(result + 16) = 0;
  return result;
}

//----- (FFFF0B98) --------------------------------------------------------
int __fastcall sub_FFFF0B98(int result, int a2)
{
  *(_DWORD *)result = a2;
  *(_DWORD *)(result + 4) = 0;
  *(_DWORD *)(result + 12) = sub_FFFF086C;
  *(_DWORD *)(result + 16) = 0;
  *(_BYTE *)(result + 8) = 0;
  *(_BYTE *)(result + 24) = 0;
  *(_DWORD *)(result + 20) = 0;
  return result;
}

//----- (FFFF0BC4) --------------------------------------------------------
int __fastcall sub_FFFF0BC4(int result, int a2)
{
  *(_DWORD *)result = a2;
  *(_DWORD *)(result + 4) = 0;
  *(_DWORD *)(result + 12) = sub_FFFF0884;
  *(_DWORD *)(result + 16) = 0;
  *(_BYTE *)(result + 8) = 0;
  *(_BYTE *)(result + 24) = 0;
  *(_DWORD *)(result + 20) = 1;
  return result;
}

//----- (FFFF0BF4) --------------------------------------------------------
int __fastcall sub_FFFF0BF4(int result, int a2)
{
  *(_DWORD *)result = a2;
  *(_DWORD *)(result + 4) = 0;
  *(_DWORD *)(result + 12) = sub_FFFF0878;
  *(_DWORD *)(result + 16) = 0;
  *(_BYTE *)(result + 8) = 0;
  *(_BYTE *)(result + 24) = 0;
  *(_DWORD *)(result + 20) = 2;
  return result;
}

//----- (FFFF0C24) --------------------------------------------------------
_DWORD *__fastcall sub_FFFF0C24(_DWORD *result, int a2, int a3, int a4)
{
  result[3] = a2;
  result[7] = a3;
  result[11] = a4;
  return result;
}

//----- (FFFF0C34) --------------------------------------------------------
int sub_FFFF0C34()
{
  byte_1C13040 &= 0xDFu;
  return (unsigned __int8)byte_1C13040;
}
// 1C13040: using guessed type char byte_1C13040;

//----- (FFFF0C50) --------------------------------------------------------
int *sub_FFFF0C50()
{
  char *v0; // r2
  int *result; // r0

  dword_1C20000 = dword_1C20000 & 0x7FFCE0CC | 0x80011000;
  v0 = (char *)&unk_C350;
  while ( v0-- != 0 )
    ;
  result = &dword_1C20000;
  dword_1C20050 = dword_1C20050 & 0xFFFCFFFF | 0x20000;
  dword_1C20054 = dword_1C20054 & 0xFFFFCFFF | 0x2000;
  return result;
}
// 1C20000: using guessed type int dword_1C20000;
// 1C20050: using guessed type int dword_1C20050;
// 1C20054: using guessed type int dword_1C20054;

//----- (FFFF0CB4) --------------------------------------------------------
int sub_FFFF0CB4()
{
  int result; // r0

  result = dword_1C13400 | 0xC000;
  dword_1C13400 |= 0xC000u;
  return result;
}
// 1C13400: using guessed type int dword_1C13400;

//----- (FFFF0CCC) --------------------------------------------------------
int sub_FFFF0CCC()
{
  int v0; // r0
  signed int v1; // r1
  int result; // r0

  v0 = dword_1C13400 | 0x10000;
  dword_1C13400 |= 0x10000u;
  v1 = 2000;
  while ( v1-- != 0 )
    ;
  result = v0 | 0xC00;
  dword_1C13400 = result;
  return result;
}
// 1C13400: using guessed type int dword_1C13400;

//----- (FFFF0D08) --------------------------------------------------------
signed int sub_FFFF0D08()
{
  if ( (byte_1C13041 & 0x18) != 24 )
    dword_1C13400 |= 0x3000u;
  return 1;
}
// 1C13041: using guessed type char byte_1C13041;
// 1C13400: using guessed type int dword_1C13400;

//----- (FFFF0D50) --------------------------------------------------------
unsigned int sub_FFFF0D50()
{
  unsigned int result; // r0

  result = dword_1C13400 & 0xFFFEFFFF;
  dword_1C13400 &= 0xFFFEFFFF;
  return result;
}
// 1C13400: using guessed type int dword_1C13400;

//----- (FFFF0D68) --------------------------------------------------------
BOOL sub_FFFF0D68()
{
  return (byte_1C13041 & 0x80) == 128 && byte_1C13041 & 1;
}
// 1C13041: using guessed type char byte_1C13041;

//----- (FFFF0DA0) --------------------------------------------------------
int *sub_FFFF0DA0()
{
  signed int v0; // r0
  int v1; // r3

  dword_1C20420 = 0;
  dword_1C20424 = 0;
  sub_FFFF0CB4();
  sub_FFFF0CCC();
  do
  {
    sub_FFFF0D68();
    v0 = sub_FFFF0D08();
  }
  while ( !v1 && !v0 );
  sub_FFFF0D50();
  return sub_FFFF0C50();
}
// 1C20420: using guessed type int dword_1C20420;
// 1C20424: using guessed type int dword_1C20424;

//----- (FFFF0E00) --------------------------------------------------------
int __fastcall sub_FFFF0E00(int a1)
{
  int v1; // r4
  int result; // r0

  v1 = a1;
  sub_FFFF0964(*(unsigned __int8 *)(a1 + 4));
  if ( *(_BYTE *)(v1 + 5) & 0x80 )
  {
    word_1C13082 = 72;
    unk_1C13080 = *(_DWORD *)(v1 + 8) & 0x7FF;
    result = (unsigned __int8)byte_1C13048 | (1 << *(_BYTE *)(v1 + 4));
    byte_1C13048 |= 1 << *(_BYTE *)(v1 + 4);
  }
  else
  {
    LOWORD(dword_1C13086) = 144;
    word_1C13084 = *(_WORD *)(v1 + 8) & 0x7FF;
    result = (unsigned __int8)byte_1C1304A | (1 << *(_BYTE *)(v1 + 4));
    byte_1C1304A |= 1 << *(_BYTE *)(v1 + 4);
  }
  return result;
}
// 1C13048: using guessed type char byte_1C13048;
// 1C1304A: using guessed type char byte_1C1304A;
// 1C13082: using guessed type __int16 word_1C13082;
// 1C13084: using guessed type __int16 word_1C13084;
// 1C13086: using guessed type int dword_1C13086;

//----- (FFFF0E98) --------------------------------------------------------
int __fastcall sub_FFFF0E98(int a1)
{
  int v1; // r4

  v1 = a1;
  sub_FFFF0E00(*(_DWORD *)(a1 + 36) + 32);
  return sub_FFFF0E00(*(_DWORD *)(v1 + 36) + 16);
}

//----- (FFFF0EBC) --------------------------------------------------------
int __fastcall sub_FFFF0EBC(int a1)
{
  int v1; // r4
  int result; // r0

  v1 = a1;
  dword_1C20420 = 0;
  dword_1C20424 = 0;
  sub_FFFF0C34();
  dword_1C00004 |= 1u;
  byte_1C13094 = 7;
  word_1C13096 = 128;
  LOBYTE(word_1C13042) = 2;
  byte_1C13090 = 7;
  word_1C13092 = 256;
  byte_1C13050 = 7;
  byte_1C13048 = byte_48[(unsigned int)&byte_1C13000 & 0xFFFFFFF8] | 1;
  sub_FFFF0E98(dword_7D00);
  *(_BYTE *)(*(_DWORD *)(v1 + 36) + 52) = 2;
  sub_FFFF0DA0();
  result = (unsigned __int8)byte_1C13040 | 0x40;
  byte_1C13040 |= 0x40u;
  return result;
}
// 7D00: using guessed type int dword_7D00;
// 1C00004: using guessed type int dword_1C00004;
// 1C13000: using guessed type char byte_1C13000;
// 1C13040: using guessed type char byte_1C13040;
// 1C13042: using guessed type __int16 word_1C13042;
// 1C13048: using guessed type char byte_1C13048;
// 1C13050: using guessed type char byte_1C13050;
// 1C13090: using guessed type char byte_1C13090;
// 1C13092: using guessed type __int16 word_1C13092;
// 1C13094: using guessed type char byte_1C13094;
// 1C13096: using guessed type __int16 word_1C13096;
// 1C20420: using guessed type int dword_1C20420;
// 1C20424: using guessed type int dword_1C20424;

//----- (FFFF0F70) --------------------------------------------------------
int __fastcall sub_FFFF0F70(int a1)
{
  unsigned int v1; // r0

  HIBYTE(word_1C13042) &= 0xFEu;
  sub_FFFF0EBC(a1);
  sub_FFFF0924();
  v1 = sub_FFFF0950();
  return nullsub_2(v1);
}
// 1C13042: using guessed type __int16 word_1C13042;
// FFFF0118: using guessed type int __fastcall nullsub_2(_DWORD);

//----- (FFFF0FA8) --------------------------------------------------------
signed int __fastcall sub_FFFF0FA8(int a1, _DWORD *a2, _DWORD *a3)
{
  if ( (*(_BYTE *)(a1 + 5) & 0x7F) > 4 )
    return -1;
  switch ( *(_BYTE *)(a1 + 5) & 0x7F )
  {
    case 1:
      *a2 = 1;
      *a3 = &unk_1C13004;
      break;
    case 2:
      *a2 = 2;
      *a3 = &unk_1C13008;
      break;
    case 3:
      *a2 = 3;
      *a3 = &unk_1C1300C;
      break;
    case 4:
      *a2 = 4;
      *a3 = &unk_1C13010;
      break;
    default:
      *a2 = 0;
      *a3 = &byte_1C13000;
      break;
  }
  return 0;
}
// 1C13000: using guessed type char byte_1C13000;

//----- (FFFF1078) --------------------------------------------------------
int __fastcall sub_FFFF1078(int a1, int a2, char a3)
{
  *(_BYTE *)(a2 + 24) = a3;
  return (*(int (__fastcall **)(int))(a2 + 12))(a2);
}

//----- (FFFF10A4) --------------------------------------------------------
signed int __fastcall sub_FFFF10A4(int a1, int a2, _BYTE *a3, int a4)
{
  int v4; // r7
  int v5; // r6
  _BYTE *v6; // r5
  signed int v7; // r9
  signed int v9; // r4
  _BYTE *v10; // [sp+0h] [bp-28h]
  int v11; // [sp+4h] [bp-24h]

  v10 = a3;
  v11 = a4;
  v4 = a1;
  v5 = a2;
  v6 = a3;
  v7 = 0;
  if ( sub_FFFF0FA8(a2, &v11, &v10) )
    return -1;
  if ( *(_DWORD *)(v5 + 8) == sub_FFFF2310(v10, v6, *(_DWORD *)(v5 + 8)) )
  {
    if ( *((_DWORD *)v6 + 1) != *((_DWORD *)v6 + 4) || v6[8] )
      v9 = 0;
    else
      v9 = 2;
  }
  else
  {
    v9 = 1;
  }
  if ( v9 )
  {
    if ( v11 )
    {
      LOBYTE(word_1C13042) = v11;
      word_1C13082 = 8193;
      v7 = 1;
    }
    else if ( !(sub_FFFF22AC(v4) & 4) )
    {
      if ( v9 == 1 )
      {
        LOBYTE(word_1C13042) = v11;
        word_1C13082 = 10;
        *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48) = 0;
        v7 = 1;
      }
      else if ( v9 == 2 )
      {
        LOBYTE(word_1C13042) = v11;
        word_1C13082 = 2;
      }
    }
    if ( v7 == 1 )
      sub_FFFF1078(v5, (int)v6, 0);
  }
  else if ( v11 )
  {
    LOBYTE(word_1C13042) = v11;
    word_1C13082 = 8193;
  }
  else if ( !(sub_FFFF22AC(v4) & 4) )
  {
    LOBYTE(word_1C13042) = v11;
    word_1C13082 = 2;
  }
  return v7;
}
// 1C13042: using guessed type __int16 word_1C13042;
// 1C13082: using guessed type __int16 word_1C13082;

//----- (FFFF1224) --------------------------------------------------------
signed int __fastcall sub_FFFF1224(int a1, int a2, int a3)
{
  int v3; // r9
  int v4; // r6
  int v5; // r4
  _DWORD *v7; // r10
  unsigned int v8; // r7
  unsigned int v9; // r8
  _DWORD *v10; // [sp+0h] [bp-30h]
  int v11; // [sp+4h] [bp-2Ch]
  BOOL v12; // [sp+8h] [bp-28h]

  v11 = a3;
  v3 = a1;
  v4 = a2;
  v5 = a3;
  v12 = 1;
  if ( sub_FFFF0FA8(a2, &v11, &v10) )
    return -1;
  v7 = (_DWORD *)(*(_DWORD *)v5 + *(_DWORD *)(v5 + 16));
  if ( *(_DWORD *)(v5 + 4) == *(_DWORD *)(v5 + 16) )
    return -1;
  LOBYTE(word_1C13042) = v11;
  if ( *(_DWORD *)(v4 + 8) >= *(unsigned int *)((char *)&dword_1C13086 + 2) )
    v8 = *(int *)((char *)&dword_1C13086 + 2);
  else
    v8 = *(_DWORD *)(v4 + 8);
  v9 = sub_FFFF2380(v10, v7, v5, v8);
  if ( *(_DWORD *)(v4 + 8) <= v9 )
  {
    v12 = *(_DWORD *)(v5 + 4) == *(_DWORD *)(v5 + 16);
  }
  else
  {
    v12 = 1;
    if ( v9 != v8 )
      *(_BYTE *)(v5 + 24) = -1;
  }
  LOBYTE(word_1C13042) = v11;
  if ( v12 )
  {
    if ( v11 )
    {
      LOBYTE(word_1C13042) = v11;
      LOWORD(dword_1C13086) = dword_1C13086 & 0xFFFE;
    }
    else
    {
      LOBYTE(word_1C13042) = 0;
      word_1C13082 = 72;
      *(_DWORD *)(*(_DWORD *)(v3 + 36) + 48) = 0;
    }
    sub_FFFF1078(v4, v5, 0);
    v12 = 1;
  }
  else if ( v11 )
  {
    LOBYTE(word_1C13042) = v11;
    LOWORD(dword_1C13086) = dword_1C13086 & 0xFFFE;
  }
  else
  {
    LOBYTE(word_1C13042) = 0;
    word_1C13082 = 64;
  }
  return v12;
}
// 1C13042: using guessed type __int16 word_1C13042;
// 1C13082: using guessed type __int16 word_1C13082;
// 1C13086: using guessed type int dword_1C13086;

//----- (FFFF13E4) --------------------------------------------------------
signed int __fastcall sub_FFFF13E4(int a1, int a2, int a3, int a4)
{
  int v4; // r6
  int v5; // r5
  int v6; // r7
  __int16 v7; // r8
  int v9; // r4
  __int16 *v10; // r0
  int v11; // r0
  __int16 *v12; // r0

  v4 = a1;
  v5 = a2;
  v6 = a3;
  LOBYTE(v7) = 0;
  if ( *(_DWORD *)(a2 + 20) & 0xFFFFFFFC )
    return -1;
  if ( !a3 )
    sub_FFFF093C();
  v9 = *(_DWORD *)(v4 + 36) + 16 * *(_DWORD *)(v5 + 20);
  *(_DWORD *)(v5 + 16) = 0;
  if ( *(_BYTE *)(v9 + 5) )
  {
    LOBYTE(word_1C13042) = *(_BYTE *)(v9 + 5) & 0x7F;
    if ( *(_BYTE *)(v9 + 5) & 0x80 )
      v10 = &word_1C13082;
    else
      v10 = (__int16 *)&dword_1C13086;
    v7 = *v10;
  }
  if ( *(_BYTE *)(v9 + 5) )
  {
    if ( (!(*(_BYTE *)(v9 + 5) & 0x80) || v7 & 1 || !sub_FFFF10A4(v4, v9, (_BYTE *)v5, a4))
      && !(*(_BYTE *)(v9 + 5) & 0x80)
      && v7 & 1
      && HIWORD(dword_1C13086) )
    {
      do
      {
        sub_FFFF1224(v4, v9, v5);
        LOBYTE(word_1C13042) = *(_BYTE *)(v9 + 5) & 0x7F;
        if ( *(_BYTE *)(v9 + 5) & 0x80 )
          v12 = &word_1C13082;
        else
          v12 = (__int16 *)&dword_1C13086;
      }
      while ( *(_BYTE *)(v5 + 24) && *v12 & 1 && HIWORD(dword_1C13086) );
    }
    goto LABEL_32;
  }
  v11 = *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48);
  if ( v11 == 1 )
  {
    sub_FFFF10A4(v4, v9, (_BYTE *)v5, a4);
    goto LABEL_32;
  }
  if ( v11 == 2 )
  {
    *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48) = 0;
LABEL_32:
    if ( !v6 )
      sub_FFFF0950();
    return 0;
  }
  if ( !v6 )
    sub_FFFF0950();
  return -1;
}
// 1C13042: using guessed type __int16 word_1C13042;
// 1C13082: using guessed type __int16 word_1C13082;
// 1C13086: using guessed type int dword_1C13086;

//----- (FFFF15D8) --------------------------------------------------------
signed int __fastcall sub_FFFF15D8(int a1, int a2, int a3, int a4)
{
  return sub_FFFF13E4(a1, a2, a3, a4);
}

//----- (FFFF15FC) --------------------------------------------------------
_DWORD *__fastcall sub_FFFF15FC(_DWORD *result)
{
  result[2] = 0;
  result[1] = 0;
  *result = 0;
  return result;
}

//----- (FFFF1610) --------------------------------------------------------
int __fastcall sub_FFFF1610(_BYTE *a1)
{
  int v1; // r6
  _BYTE *v2; // r8
  int v3; // r4
  signed int i; // r5
  bool v5; // zf

  v1 = 0;
  v2 = a1;
  sub_FFFF0964(0);
  v3 = HIWORD(dword_1C13086);
  if ( HIWORD(dword_1C13086) != 8 )
  {
    for ( i = 0; i < 16 && v3 != 8; ++i )
      v3 = HIWORD(dword_1C13086);
  }
  while ( 1 )
  {
    v5 = v3-- == 0;
    if ( v5 )
      break;
    *v2++ = byte_1C13000;
    ++v1;
  }
  return v1;
}
// 1C13000: using guessed type char byte_1C13000;
// 1C13086: using guessed type int dword_1C13086;

//----- (FFFF168C) --------------------------------------------------------
signed int __fastcall sub_FFFF168C(int a1, _BYTE *a2, int a3, int a4)
{
  int v4; // r6
  _BYTE *v5; // r4
  _BYTE *v6; // r5
  char **v8; // r8
  _BYTE *v9; // r4

  v4 = a1;
  v5 = a2;
  v6 = a2;
  if ( a4 )
    return -1;
  v8 = *(char ***)(a1 + 20);
  sub_FFFF0890(a2, *(char **)(a1 + 4), 9);
  v9 = v5 + 9;
  sub_FFFF0890(v9, *(char **)(v4 + 8), 9);
  v9 += 9;
  sub_FFFF0890(v9, *v8, 7);
  sub_FFFF0890(v9 + 7, v8[1], 7);
  *v6 = 9;
  v6[1] = 2;
  *((_WORD *)v6 + 1) = 32;
  v6[7] |= 0x80u;
  return 32;
}

//----- (FFFF1784) --------------------------------------------------------
int __fastcall sub_FFFF1784(int a1, unsigned __int8 *a2, int a3, int a4)
{
  char **v4; // r8
  unsigned __int8 *v5; // r5
  int v6; // r6
  _BYTE **v7; // r4
  int v8; // r0
  int v9; // r0
  int v10; // r7
  signed int v11; // r7
  _BYTE *v12; // r0
  _BYTE *v13; // r0

  v4 = (char **)a1;
  v5 = a2;
  v6 = *((unsigned __int16 *)a2 + 1);
  v7 = *(_BYTE ***)(*(_DWORD *)(a1 + 36) + 12);
  v8 = a2[1];
  if ( v8 == 6 )
  {
    if ( *a2 == 128 )
    {
      v9 = v6 >> 8;
      if ( v6 >> 8 == 1 )
      {
        if ( *((unsigned __int16 *)a2 + 3) <= 0x12u )
          v10 = *((unsigned __int16 *)a2 + 3);
        else
          v10 = 18;
        sub_FFFF0890(*v7, *v4, v10);
        v7[1] = (_BYTE *)v10;
        *((_BYTE *)v7 + 8) = 0;
      }
      else if ( v9 == 2 )
      {
        v11 = sub_FFFF168C((int)v4, *v7, v6 >> 8, (unsigned __int8)v6);
        if ( *((unsigned __int16 *)v5 + 3) < v11 )
          v7[1] = (_BYTE *)*((unsigned __int16 *)v5 + 3);
        else
          v7[1] = (_BYTE *)v11;
        *((_BYTE *)v7 + 8) = 0;
      }
      else if ( v9 == 3 && !(_BYTE)v6 )
      {
        v12 = *v7;
        *v12 = 4;
        v12[1] = 3;
        v12[2] = 9;
        v12[3] = 4;
      }
    }
  }
  else if ( v8 == 254 )
  {
    v13 = *v7;
    v7[1] = (_BYTE *)&unk_1;
    *v13 = 0;
  }
  sub_FFFF15D8((int)v4, (int)v7, 1, a4);
  return 0;
}

//----- (FFFF18FC) --------------------------------------------------------
signed int __fastcall sub_FFFF18FC(int a1, int a2, int a3, int a4)
{
  int v4; // r4
  int v5; // r6
  _BYTE *v6; // r7
  int v7; // r3
  char v8; // r5
  signed int result; // r0
  unsigned int v10; // r3
  int v11; // r2
  int v12; // r3
  int v13; // r8
  int v14; // [sp+0h] [bp-28h]
  int v15; // [sp+4h] [bp-24h]

  v14 = a3;
  v15 = a4;
  v4 = a1;
  v5 = *(_DWORD *)(a1 + 36);
  v6 = *(_BYTE **)(v5 + 12);
  sub_FFFF0964(*(unsigned __int8 *)(v5 + 4));
  v8 = word_1C13082;
  if ( word_1C13082 & 4 )
  {
    result = 0;
    word_1C13082 = 0;
    *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48) = 0;
    return result;
  }
  if ( word_1C13082 & 0x10 )
  {
    word_1C13082 &= 0xFFEFu;
    *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48) = 0;
  }
  result = *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48);
  switch ( result )
  {
    case 0:
      if ( !(v8 & 1) )
        return result;
      if ( sub_FFFF1610(&v14) != 8 )
      {
        result = 96;
        word_1C13082 = 96;
        return result;
      }
      sub_FFFF2454(*(_DWORD *)(v4 + 36) + 62, (int)&v14, 8u, v10);
      *(_BYTE *)(*(_DWORD *)(v4 + 36) + 61) = 1;
      switch ( BYTE1(v14) )
      {
        case 5u:
          if ( !(_BYTE)v14 )
          {
            *(_BYTE *)(*(_DWORD *)(v4 + 36) + 60) = BYTE2(v14) & 0x7F;
            word_1C13082 = 74;
            result = 3;
            *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48) = 3;
            return result;
          }
          break;
        case 9u:
          if ( !(_BYTE)v14 )
            goto LABEL_15;
          break;
        case 0xBu:
          if ( (unsigned __int8)v14 != 1 )
            break;
LABEL_15:
          result = 72;
          word_1C13082 = 72;
          return result;
        default:
          word_1C13082 = 64;
          break;
      }
      if ( v14 & 0x80 )
        *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48) = 1;
      else
        *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48) = 2;
      if ( sub_FFFF1784(v4, (unsigned __int8 *)&v14, v11, v12) >= 0 )
      {
        result = *(unsigned __int8 *)(*(_DWORD *)(v4 + 36) + 61);
        if ( *(_BYTE *)(*(_DWORD *)(v4 + 36) + 61) )
        {
          result = 0;
          *(_BYTE *)(*(_DWORD *)(v4 + 36) + 61) = 0;
        }
      }
      else
      {
        word_1C13082 = 72;
        result = 0;
        *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48) = 0;
      }
      return result;
    case 1:
      if ( !(v8 & 2) && v6 )
        result = sub_FFFF10A4(v4, v5, v6, v7);
      return result;
    case 2:
      if ( v8 & 1 && v6 )
        result = sub_FFFF1224(v4, v5, (int)v6);
      return result;
    case 3:
      if ( *(_BYTE *)(*(_DWORD *)(v4 + 36) + 63) == 5 )
      {
        word_1C13082 = 192;
        v13 = sub_FFFF0970();
        sub_FFFF0964(0);
        byte_1C13098 = *(_BYTE *)(*(_DWORD *)(v4 + 36) + 60);
        sub_FFFF0964(v13);
      }
      result = 0;
      *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48) = 0;
      return result;
    case 4:
      result = 0;
      *(_DWORD *)(*(_DWORD *)(v4 + 36) + 48) = 0;
      return result;
    default:
      return result;
  }
}
// 1C13082: using guessed type __int16 word_1C13082;
// 1C13098: using guessed type char byte_1C13098;

//----- (FFFF1C08) --------------------------------------------------------
signed int __fastcall sub_FFFF1C08(signed int result, int a2)
{
  int v2; // r9
  int v3; // r6
  _BYTE *v4; // r5
  __int16 v5; // r7
  int v6; // r3
  char v7; // r4

  v2 = result;
  if ( a2 )
  {
    v3 = *(_DWORD *)(result + 36) + 16 * a2;
    v4 = *(_BYTE **)(v3 + 12);
    v5 = *(_BYTE *)(v3 + 5) & 0x7F;
    result = (unsigned __int8)v4[24];
    if ( result == 1 )
    {
      if ( *(_BYTE *)(v3 + 5) & 0x80 )
      {
        sub_FFFF0964(*(unsigned __int8 *)(v3 + 4));
        result = (signed int)&byte_1C13000;
        if ( word_1C13082 & 0x20 )
        {
          word_1C13042 = v5;
          result = 0;
          word_1C13082 = 0;
        }
        else if ( !(word_1C13082 & 1) )
        {
          if ( v4 )
            result = sub_FFFF10A4(v2, v3, v4, v6);
        }
      }
      else
      {
        LOBYTE(word_1C13042) = *(_BYTE *)(v3 + 5) & 0x7F;
        result = (signed int)&byte_1C13000;
        v7 = dword_1C13086;
        if ( dword_1C13086 & 0x40 )
        {
          word_1C13042 = v5;
          result = 0;
          LOWORD(dword_1C13086) = 0;
        }
        else
        {
          do
          {
            if ( !(v7 & 1) )
              break;
            if ( !v4 )
              break;
            sub_FFFF1224(v2, v3, (int)v4);
            result = (unsigned __int8)v4[24];
            if ( !v4[24] )
              break;
            LOBYTE(word_1C13042) = v5;
            result = (signed int)&byte_1C13000;
            v7 = dword_1C13086;
            if ( !(dword_1C13086 & 1) )
              break;
          }
          while ( v4 );
        }
      }
    }
  }
  return result;
}
// 1C13000: using guessed type char byte_1C13000;
// 1C13042: using guessed type __int16 word_1C13042;
// 1C13082: using guessed type __int16 word_1C13082;
// 1C13086: using guessed type int dword_1C13086;

//----- (FFFF1D34) --------------------------------------------------------
int IRQ_handler()
{
  char v0; // r7
  char v1; // r6
  int v2; // r0
  int v3; // r8
  int v4; // r0
  int v5; // r9
  int v6; // r0
  int v7; // r5
  int result; // r0
  int v9; // r1
  int v10; // r2
  int v11; // r3
  signed int i; // r4
  int j; // r5
  signed int k; // r4
  int l; // r5

  v0 = sub_FFFF0970();
  v1 = sub_FFFF22AC(dword_7D00);
  v2 = dword_7D00;
  if ( !*(_DWORD *)(dword_7D00 + 56) )
    *(_DWORD *)(dword_7D00 + 56) = (unsigned __int8)byte_1C13044;
  v3 = *(_DWORD *)(v2 + 56);
  v4 = dword_7D00;
  if ( !*(_DWORD *)(dword_7D00 + 60) )
    *(_DWORD *)(dword_7D00 + 60) = (unsigned __int8)byte_1C13046;
  v5 = *(_DWORD *)(v4 + 60);
  if ( v1 & 4 )
  {
    *(_BYTE *)(*(_DWORD *)(dword_7D00 + 36) + 52) = 2;
    *(_DWORD *)(*(_DWORD *)(dword_7D00 + 36) + 48) = 0;
    v6 = sub_FFFF22F0(dword_7D00, 4);
    LOBYTE(word_1C13042) = v0;
    nullsub_3(v6);
    byte_1C13048 |= 1u;
    sub_FFFF0E98(dword_7D00);
    v7 = sub_FFFF0970();
    sub_FFFF0964(0);
    byte_1C13098 = 0;
    result = sub_FFFF0964(v7);
  }
  else
  {
    if ( v1 & 2 )
      v4 = sub_FFFF22F0(dword_7D00, 2);
    if ( v1 & 1 )
    {
      sub_FFFF22F0(dword_7D00, 1);
      v4 = 0;
      *(_DWORD *)(*(_DWORD *)(dword_7D00 + 36) + 48) = 0;
    }
    if ( v3 & 1 )
    {
      sub_FFFF22D0(dword_7D00, 1);
      v4 = sub_FFFF18FC(dword_7D00, v9, v10, v11);
    }
    for ( i = 1; i <= 5; ++i )
    {
      v4 = 1;
      if ( v3 & (1 << i) )
      {
        v4 = sub_FFFF22D0(dword_7D00, (1 << i) & 0xFF);
        for ( j = 1; j < 3; ++j )
        {
          v4 = *(_BYTE *)(*(_DWORD *)(dword_7D00 + 36) + 16 * j + 5) & 0x80;
          if ( v4 == 128 )
            v4 = sub_FFFF1C08(dword_7D00, j);
        }
      }
    }
    for ( k = 1; k <= 5; ++k )
    {
      v4 = 1;
      if ( v5 & (1 << k) )
      {
        v4 = dword_7D00;
        *(_DWORD *)(dword_7D00 + 60) &= ~(unsigned __int8)(1 << k);
        byte_1C13046 = 1 << k;
        for ( l = 1; l < 3; ++l )
        {
          v4 = *(unsigned __int8 *)(*(_DWORD *)(dword_7D00 + 36) + 16 * l + 5);
          if ( !(v4 & 0x80) )
            v4 = sub_FFFF1C08(dword_7D00, l);
        }
      }
    }
    nullsub_3(v4);
    LOBYTE(word_1C13042) = v0;
    result = dword_7D00;
    *(_DWORD *)(dword_7D00 + 64) = 0;
    *(_DWORD *)(result + 56) = 0;
    *(_DWORD *)(result + 60) = 0;
  }
  return result;
}
// 7D00: using guessed type int dword_7D00;
// 1C13042: using guessed type __int16 word_1C13042;
// 1C13044: using guessed type char byte_1C13044;
// 1C13046: using guessed type char byte_1C13046;
// 1C13048: using guessed type char byte_1C13048;
// 1C13098: using guessed type char byte_1C13098;
// FFFF1074: using guessed type int __fastcall nullsub_3(_DWORD);

//----- (FFFF2000) --------------------------------------------------------
_BYTE *sub_FFFF2000()
{
  return sub_FFFF08B8(&unk_7E00, 204, 256);
}

//----- (FFFF2018) --------------------------------------------------------
void __noreturn FEL_main()
{
  char v0; // [sp+24h] [bp-11A4h]
  char v1; // [sp+68h] [bp-1160h]
  int v2; // [sp+1068h] [bp-160h]
  int v3; // [sp+1084h] [bp-144h]
  int v4; // [sp+10A0h] [bp-128h]
  int v5; // [sp+10BCh] [bp-10Ch]
  int v6; // [sp+10D8h] [bp-F0h]
  int v7; // [sp+1120h] [bp-A8h]
  int v8; // [sp+1128h] [bp-A0h]
  int v9; // [sp+1130h] [bp-98h]
  int v10; // [sp+1138h] [bp-90h]
  char v11; // [sp+1140h] [bp-88h]
  int v12; // [sp+1148h] [bp-80h]
  int v13; // [sp+1150h] [bp-78h]
  int v14; // [sp+115Ch] [bp-6Ch]
  int v15; // [sp+1168h] [bp-60h]
  int *v16; // [sp+117Ch] [bp-4Ch]
  int *v17; // [sp+1180h] [bp-48h]
  int *v18; // [sp+1184h] [bp-44h]
  int *v19; // [sp+1188h] [bp-40h]
  char *v20; // [sp+118Ch] [bp-3Ch]
  int *v21; // [sp+1190h] [bp-38h]
  int *v22; // [sp+1194h] [bp-34h]
  int *v23; // [sp+1198h] [bp-30h]
  int *v24; // [sp+119Ch] [bp-2Ch]
  int *v25; // [sp+11A0h] [bp-28h]
  int *v26; // [sp+11A4h] [bp-24h]
  int *v27; // [sp+11A8h] [bp-20h]
  int *v28; // [sp+11ACh] [bp-1Ch]
  int *v29; // [sp+11B0h] [bp-18h]
  int v30; // [sp+11B4h] [bp-14h]

  sub_FFFF2000();
  dword_7D00 = (int)&v16;
  v16 = &v15;
  v17 = &v14;
  v18 = &v13;
  v19 = &v12;
  v20 = &v11;
  v21 = &v10;
  v22 = &v9;
  v23 = &v8;
  v24 = &v7;
  v25 = &v6;
  v26 = &v5;
  v27 = &v4;
  v28 = &v3;
  v29 = &v2;
  sub_FFFF15FC(&v30);
  sub_FFFF097C((int)&v15);
  sub_FFFF09E0((int)&v14);
  sub_FFFF0A20(&v13);
  sub_FFFF0A60((int)&v12);
  sub_FFFF0A94((int)&v11);
  sub_FFFF0AC8(&v10, (int)&v11, (int)&v12);
  nullsub_4();
  nullsub_5();
  nullsub_6();
  sub_FFFF0AE0((int)&v6, (int)&v12, (int)&v11);
  sub_FFFF0B74((int)&v5, (int)&v1, (int)&v2, (int)&v3);
  sub_FFFF0B98((int)&v4, (int)&v0);
  sub_FFFF0BF4((int)&v3, (int)&v1);
  sub_FFFF0BC4((int)&v2, (int)&v1);
  sub_FFFF0C24(v25, (int)&v4, (int)&v2, (int)&v3);
  sub_FFFF093C();
  sub_FFFF0F70((int)&v16);
  sub_FFFF084C((int)&v16);
}
// 7D00: using guessed type int dword_7D00;

//----- (FFFF2258) --------------------------------------------------------
signed int __fastcall sub_FFFF2258(int a1)
{
  char *v1; // r5

  v1 = (char *)&unk_4E20;
  sub_FFFF0964(*(unsigned __int8 *)(*(_DWORD *)(a1 + 36) + 36));
  while ( 1 )
  {
    if ( !(word_1C13082 & 1) )
      return 1;
    if ( !v1 )
      break;
    --v1;
  }
  return 2;
}
// 1C13082: using guessed type __int16 word_1C13082;

//----- (FFFF22AC) --------------------------------------------------------
int __fastcall sub_FFFF22AC(int a1)
{
  if ( !*(_DWORD *)(a1 + 64) )
    *(_DWORD *)(a1 + 64) = (unsigned __int8)byte_1C1304C;
  return *(_DWORD *)(a1 + 64);
}
// 1C1304C: using guessed type char byte_1C1304C;

//----- (FFFF22D0) --------------------------------------------------------
int __fastcall sub_FFFF22D0(int a1, int a2)
{
  *(_DWORD *)(a1 + 56) &= ~a2;
  byte_1C13044 = a2;
  return 0;
}
// 1C13044: using guessed type char byte_1C13044;

//----- (FFFF22F0) --------------------------------------------------------
int __fastcall sub_FFFF22F0(int a1, int a2)
{
  *(_DWORD *)(a1 + 64) &= ~a2;
  byte_1C1304C = a2;
  return 0;
}
// 1C1304C: using guessed type char byte_1C1304C;

//----- (FFFF2310) --------------------------------------------------------
unsigned int __fastcall sub_FFFF2310(_BYTE *a1, _DWORD *a2, unsigned int a3)
{
  _BYTE *v3; // r3
  char *v4; // r12
  unsigned int v5; // r4
  unsigned int result; // r0
  unsigned int v7; // r2
  char v8; // t1
  bool v9; // zf

  v3 = a1;
  v4 = (char *)(*a2 + a2[4]);
  if ( a2[1] - a2[4] >= a3 )
    v5 = a3;
  else
    v5 = a2[1] - a2[4];
  result = v5;
  a2[4] += v5;
  v7 = v5;
  while ( 1 )
  {
    v9 = v7-- == 0;
    if ( v9 )
      break;
    v8 = *v4++;
    *v3 = v8;
  }
  return result;
}

//----- (FFFF2380) --------------------------------------------------------
unsigned int __fastcall sub_FFFF2380(_DWORD *a1, _DWORD *a2, int a3, unsigned int a4)
{
  _DWORD *v4; // r12
  unsigned int v5; // r4
  unsigned int v6; // r5
  unsigned int result; // r0
  unsigned int v8; // r3
  bool v9; // zf

  v4 = a1;
  v5 = 0;
  if ( *(_DWORD *)(a3 + 4) - *(_DWORD *)(a3 + 16) >= a4 )
    v6 = a4;
  else
    v6 = *(_DWORD *)(a3 + 4) - *(_DWORD *)(a3 + 16);
  result = v6;
  *(_DWORD *)(a3 + 16) += v6;
  v8 = v6;
  if ( v6 <= 4 )
  {
    if ( v6 == 4 )
    {
      *a2 = *v4;
    }
    else if ( v6 == 2 )
    {
      *(_WORD *)a2 = *(_WORD *)v4;
    }
    else
    {
      while ( 1 )
      {
        v9 = v8-- == 0;
        if ( v9 )
          break;
        *(_BYTE *)a2 = *(_BYTE *)v4;
        a2 = (_DWORD *)((char *)a2 + 1);
      }
    }
  }
  else
  {
    while ( 1 )
    {
      v9 = v8-- == 0;
      if ( v9 )
        break;
      *(_BYTE *)a2 = *(_BYTE *)v4;
      if ( v5 < 8 )
        ++v5;
      a2 = (_DWORD *)((char *)a2 + 1);
    }
  }
  return result;
}

//----- (FFFF2454) --------------------------------------------------------
int __fastcall sub_FFFF2454(int result, int a2, unsigned int a3, unsigned int a4)
{
  unsigned int v4; // r12
  char v5; // r3
  char v6; // t1
  bool v7; // cf
  bool v8; // zf
  unsigned int v9; // r2
  char v10; // t1
  char v11; // t1
  unsigned int v12; // r1
  unsigned int v13; // t1
  unsigned int v14; // r3
  unsigned int v15; // t1
  unsigned int v16; // r3
  unsigned int v17; // t1
  unsigned int v18; // r3
  unsigned int v19; // t1
  unsigned __int8 v20; // cf
  bool v21; // nf
  signed int v22; // r2
  char *v23; // r1
  char v24; // t1
  char v25; // t1
  _BYTE *v26; // r0

  if ( a3 > 3 )
  {
    v4 = result & 3;
    if ( result & 3 )
    {
      v6 = *(_BYTE *)a2++;
      v5 = v6;
      v7 = v4 >= 2;
      v8 = v4 == 2;
      v9 = a3 + v4;
      if ( v4 <= 2 )
      {
        v10 = *(_BYTE *)a2++;
        LOBYTE(v4) = v10;
      }
      *(_BYTE *)result++ = v5;
      if ( !v7 )
      {
        v11 = *(_BYTE *)a2++;
        v5 = v11;
      }
      if ( v8 || !v7 )
        *(_BYTE *)result++ = v4;
      a3 = v9 - 4;
      if ( !v7 )
        *(_BYTE *)result++ = v5;
    }
    a4 = a2 & 3;
    if ( !(a2 & 3) )
      return (int)sub_FFFF2548((_DWORD *)result, (int *)a2, a3, 0);
    v7 = a3 >= 4;
    a3 -= 4;
    if ( v7 )
    {
      v13 = *(_DWORD *)(a2 - a4);
      v12 = a2 - a4;
      v4 = v13;
      if ( a4 == 2 )
      {
        do
        {
          v16 = v4 >> 16;
          v17 = *(_DWORD *)(v12 + 4);
          v12 += 4;
          v4 = v17;
          v7 = a3 >= 4;
          a3 -= 4;
          a4 = v16 | (v17 << 16);
          *(_DWORD *)result = a4;
          result += 4;
        }
        while ( v7 );
        a2 = v12 + 2;
      }
      else if ( a4 > 2 )
      {
        do
        {
          v18 = v4 >> 24;
          v19 = *(_DWORD *)(v12 + 4);
          v12 += 4;
          v4 = v19;
          v7 = a3 >= 4;
          a3 -= 4;
          a4 = v18 | (v19 << 8);
          *(_DWORD *)result = a4;
          result += 4;
        }
        while ( v7 );
        a2 = v12 + 3;
      }
      else
      {
        do
        {
          v14 = v4 >> 8;
          v15 = *(_DWORD *)(v12 + 4);
          v12 += 4;
          v4 = v15;
          v7 = a3 >= 4;
          a3 -= 4;
          a4 = v14 | (v15 << 24);
          *(_DWORD *)result = a4;
          result += 4;
        }
        while ( v7 );
        a2 = v12 + 1;
      }
    }
  }
  v20 = __CFSHL__(a3, 31);
  v22 = a3 << 31;
  v21 = v22 < 0;
  if ( v20 )
  {
    v24 = *(_BYTE *)a2;
    v23 = (char *)(a2 + 1);
    LOBYTE(a4) = v24;
    v25 = *v23;
    a2 = (int)(v23 + 1);
    LOBYTE(v4) = v25;
  }
  if ( v22 < 0 )
    LOBYTE(v22) = *(_BYTE *)a2;
  if ( v20 )
  {
    *(_BYTE *)result = a4;
    v26 = (_BYTE *)(result + 1);
    *v26 = v4;
    result = (int)(v26 + 1);
  }
  if ( v21 )
    *(_BYTE *)result++ = v22;
  return result;
}

//----- (FFFF2528) --------------------------------------------------------
int __fastcall sub_FFFF2528(unsigned __int8 *a1)
{
  return *a1 | (a1[1] << 8) | (a1[2] << 16) | (a1[3] << 24);
}

//----- (FFFF2548) --------------------------------------------------------
_DWORD *__fastcall sub_FFFF2548(_DWORD *result, int *a2, unsigned int a3, int a4)
{
  unsigned int i; // r2
  int *v5; // r1
  int v6; // r3
  int v7; // r4
  int v8; // r12
  int v9; // lr
  int *v10; // r0
  int v11; // r4
  int v12; // r12
  int v13; // lr
  int v14; // r4
  int v15; // r12
  int v16; // lr
  int v17; // r4
  int v18; // t1
  bool v19; // cf
  bool v20; // nf
  signed int v21; // r2
  __int16 v22; // t1

  v19 = a3 >= 0x20;
  for ( i = a3 - 32; v19; result = v10 + 4 )
  {
    v6 = *a2;
    v7 = a2[1];
    v8 = a2[2];
    v9 = a2[3];
    v5 = a2 + 4;
    v19 = i >= 0x20;
    i -= 32;
    *result = v6;
    result[1] = v7;
    result[2] = v8;
    result[3] = v9;
    v10 = result + 4;
    a4 = *v5;
    v11 = v5[1];
    v12 = v5[2];
    v13 = v5[3];
    a2 = v5 + 4;
    *v10 = a4;
    v10[1] = v11;
    v10[2] = v12;
    v10[3] = v13;
  }
  if ( __CFSHL__(i, 28) )
  {
    a4 = *a2;
    v14 = a2[1];
    v15 = a2[2];
    v16 = a2[3];
    a2 += 4;
    *result = a4;
    result[1] = v14;
    result[2] = v15;
    result[3] = v16;
    result += 4;
  }
  if ( ((i << 28) & 0x80000000) != 0 )
  {
    a4 = *a2;
    v17 = a2[1];
    a2 += 2;
    *result = a4;
    result[1] = v17;
    result += 2;
  }
  if ( __CFSHL__(i, 30) )
  {
    v18 = *a2;
    ++a2;
    LOWORD(a4) = v18;
    *result = v18;
    ++result;
  }
  if ( i << 30 )
  {
    v19 = __CFSHL__(i, 31);
    v21 = i << 31;
    v20 = v21 < 0;
    if ( v19 )
    {
      v22 = *(_WORD *)a2;
      a2 = (int *)((char *)a2 + 2);
      LOWORD(a4) = v22;
    }
    if ( v21 < 0 )
      LOBYTE(v21) = *(_BYTE *)a2;
    if ( v19 )
    {
      *(_WORD *)result = a4;
      result = (_DWORD *)((char *)result + 2);
    }
    if ( v20 )
    {
      *(_BYTE *)result = v21;
      result = (_DWORD *)((char *)result + 1);
    }
  }
  return result;
}

//----- (FFFF4020) --------------------------------------------------------
void __noreturn BRM_start()
{
  __set_CPSR(__get_CPSR() & 0xFFFFFFE0 | 0x53);
  __mcr(15, 0, __mrc(15, 0, 1, 0, 0) & 0xFFFFEF72, 1, 0, 0);
  dword_1C20CB8 &= 0xFFFFFFFE;
  dword_1C20050 = dword_1C20050 & 0xFFFCFFFF | 0x10000;
  dword_1C20054 = dword_1C20054 & 0xFFFFCC0F | (unsigned int)&unk_1010;
  BRM_main();
}
// 1C20050: using guessed type int dword_1C20050;
// 1C20054: using guessed type int dword_1C20054;
// 1C20CB8: using guessed type int dword_1C20CB8;

//----- (FFFF40A4) --------------------------------------------------------
void __fastcall set_boot_debug_flag__(int result)
{
  int v1; // r2

  v1 = dword_A100[16 * result];
}

//----- (FFFF40BC) --------------------------------------------------------
unsigned int JTAG_GPIO_Enable()
{
  unsigned int result; // r0

  result = dword_1C208B4 & 0xFF888888 | 0x373733;
  dword_1C208B4 = dword_1C208B4 & 0xFF888888 | 0x373733;
  return result;
}
// 1C208B4: using guessed type int dword_1C208B4;

//----- (FFFF40E0) --------------------------------------------------------
void __noreturn BRM_main()
{
  JTAG_GPIO_Enable();
  set_boot_debug_flag__(0);
  if ( load_MMC(0) )
  {
    set_boot_debug_flag__(1);
    if ( load_SPI_1() )
    {
      set_boot_debug_flag__(2);
      if ( load_SPI_2() )
      {
        set_boot_debug_flag__(3);
        if ( load_MMC(1) )
        {
          set_boot_debug_flag__(4);
          jump_to((int (*)(void))j_FEL_start);  // Jump to FEL
        }
      }
    }
  }
  jump_to(0);                                   // Jump to APP
}
// FFFF0020: using guessed type void __noreturn j_FEL_start();

//----- (FFFF4190) --------------------------------------------------------
signed int __fastcall sub_FFFF4190(_DWORD *a1, unsigned int a2, int a3)
{
  signed int result; // r0
  int v4; // r12
  int v5; // r4

  if ( a3 )
  {
    if ( a3 == 1 )
    {
      if ( a2 >= 3 )
      {
        result = -1;
      }
      else
      {
        v4 = *(_DWORD *)(12 * a2 - 40328);
        v5 = *(_DWORD *)(12 * a2 - 40324);
        *a1 = *(_DWORD *)(12 * a2 - 40332);
        a1[1] = v4;
        a1[2] = v5;
        result = 0;
      }
    }
    else
    {
      result = -1;
    }
  }
  else if ( a2 )
  {
    result = -1;
  }
  else
  {
    a1[2] = 64;
    a1[1] = 0;
    *a1 = 1024;
    result = 0;
  }
  return result;
}

//----- (FFFF4228) --------------------------------------------------------
signed int sub_FFFF4228()
{
  unsigned int i; // r6
  unsigned int j; // r10
  int v2; // r5
  unsigned int v3; // r7
  int v4; // r8
  unsigned int v5; // r4
  int v7; // [sp+Ch] [bp-34h]
  int v8; // [sp+10h] [bp-30h]
  unsigned int v9; // [sp+14h] [bp-2Ch]
  int v10; // [sp+18h] [bp-28h]

  SPI0_Init();
  sub_FFFF5C34();
  for ( i = 0; i < 3; ++i )
  {
    for ( j = 32; j < 0x100; j += 32 )
    {
      if ( sub_FFFF4190(&v7, i, 1) != -1 )
      {
        v2 = v7;
        v3 = v9;
        v4 = v8;
        if ( sub_FFFF5C94(j, 0, 1, v7, v8, v9) != 2 && !eGON_str_cmp(0, "eGON.BT0") )
        {
          v5 = dword_10;
          if ( !((v2 - 1) & dword_10) )
          {
            v10 = sub_FFFF6240(dword_10, v2);
            if ( sub_FFFF5C94(j, 0, v10, v2, v4, v3) != 2 && !sub_FFFF5F2C(0, v5) )
            {
              SPI0_DeInit();
              return 0;
            }
          }
        }
      }
    }
  }
  SPI0_DeInit();
  return -1;
}
// 10: using guessed type int dword_10;

//----- (FFFF4350) --------------------------------------------------------
signed int sub_FFFF4350()
{
  signed int i; // r6
  int v1; // r5
  unsigned int v2; // r8
  int v3; // r7
  unsigned int v4; // r4
  int v5; // r0
  int v7; // [sp+8h] [bp-30h]
  int v8; // [sp+Ch] [bp-2Ch]
  unsigned int v9; // [sp+10h] [bp-28h]

  SPI0_Init();
  sub_FFFF5C34();
  for ( i = 0; !i; i = 1 )
  {
    if ( sub_FFFF4190(&v7, 0, 0) != -1 )
    {
      v1 = v7;
      v2 = v9;
      v3 = v8;
      if ( sub_FFFF5C94(0, 0, 1, v7, v8, v9) != 2 && !eGON_str_cmp(0, "eGON.BT0") )
      {
        v4 = dword_10;
        if ( !((v1 - 1) & dword_10) )
        {
          v5 = sub_FFFF6240(dword_10, v1);
          if ( sub_FFFF5C94(0, 0, v5, v1, v3, v2) != 2 && !sub_FFFF5F2C(0, v4) )
          {
            SPI0_DeInit();
            return 0;
          }
        }
      }
    }
  }
  SPI0_DeInit();
  return -1;
}
// 10: using guessed type int dword_10;

//----- (FFFF445C) --------------------------------------------------------
signed int load_SPI_1()
{
  if ( !sub_FFFF4350() )
    return 0;
  if ( sub_FFFF4228() )
    return -1;
  return 0;
}

//----- (FFFF449C) --------------------------------------------------------
signed int __fastcall load_MMC(int a1)
{
  int v1; // r4
  signed int v2; // r8
  unsigned int v3; // r5
  char v5; // [sp+Ch] [bp-4Ch]

  v1 = a1;
  sub_FFFF6070(&v5, 0x30u);
  v2 = -1;
  if ( sub_FFFF5610(v1, (int)&v5, &dword_1C0F000[1024 * v1]) != -1
    && (!sub_FFFF569C(16, 2, 0, (int)&v5, &dword_1C0F000[1024 * v1])
     || !sub_FFFF481C(v1, 3, (int)&dword_1C0F000[1024 * v1])
     && !sub_FFFF569C(16, 2, 0, (int)&v5, &dword_1C0F000[1024 * v1]))
    && !eGON_str_cmp(0, "eGON.BT0") )
  {
    v3 = dword_10;
    if ( !(dword_10 & 0x1FF)
      && !sub_FFFF569C(16, (unsigned int)dword_10 >> 9, 0, (int)&v5, &dword_1C0F000[1024 * v1])
      && !sub_FFFF5F2C(0, v3) )
    {
      v2 = 0;
    }
  }
  sub_FFFF5688(v1);
  return v2;
}
// 10: using guessed type int dword_10;

//----- (FFFF45E8) --------------------------------------------------------
signed int __fastcall sub_FFFF45E8(int a1, _DWORD *a2, _DWORD *a3)
{
  _DWORD *v3; // r12
  int v4; // r1
  signed int v5; // r4
  bool v6; // zf
  int v8; // r1

  v3 = a2;
  a3[7] = *(_DWORD *)(a1 + 4);
  v4 = *(_DWORD *)(a1 + 8) & 0x3F | (*(_DWORD *)(a1 + 8) << 20 >> 31 << 15) | (*(_DWORD *)(a1 + 8) << 24 >> 31 << 12);
  if ( *(_BYTE *)(a1 + 1) )
    v4 = *(_DWORD *)(a1 + 8) & 0x3F | (*(_DWORD *)(a1 + 8) << 20 >> 31 << 15) | (*(_DWORD *)(a1 + 8) << 24 >> 31 << 12) | 0x40 | (*(_DWORD *)(a1 + 8) << 25 >> 31 << 7) | (*(_DWORD *)(a1 + 8) << 23 >> 31 << 8);
  if ( *(_BYTE *)(a1 + 1) == 3 )
    v4 |= 0x2200 | (*(_DWORD *)(a1 + 8) << 22 >> 31 << 10) | (*(_DWORD *)(a1 + 8) << 21 >> 31 << 11);
  a3[6] = v4 | 0x80000000;
  v5 = 0xFFFF;
  do
    v6 = v5-- == 0;
  while ( !v6 && !(a3[14] & 4) );
  a3[14] = 4;
  if ( v5 < 0 )
    return -1;
  v8 = a3[14];
  if ( *(_BYTE *)(a1 + 1) )
  {
    if ( v8 & 0x102 )
    {
      a3[14] = 258;
      return -1;
    }
    if ( *(_DWORD *)(a1 + 8) & 0x100 && v8 & 0x40 )
    {
      a3[14] = 64;
      return -1;
    }
    *v3 = a3[8];
    if ( (*(_DWORD *)(a1 + 8) & 0x40) == 64 )
    {
      v3[1] = a3[9];
      v3[2] = a3[10];
      v3[3] = a3[11];
    }
  }
  return 0;
}

//----- (FFFF4750) --------------------------------------------------------
signed int __fastcall sub_FFFF4750(_DWORD *a1)
{
  signed int result; // r0
  int v2; // [sp+0h] [bp-24h]
  int v3; // [sp+10h] [bp-14h]
  int v4; // [sp+14h] [bp-10h]
  int v5; // [sp+18h] [bp-Ch]

  v3 = 0;
  BYTE1(v3) = 2;
  v4 = 0;
  v5 = 268;
  if ( sub_FFFF45E8((int)&v3, &v2, a1) )
    result = -1;
  else
    result = 0;
  return result;
}

//----- (FFFF47D4) --------------------------------------------------------
signed int __fastcall sub_FFFF47D4(int a1, int a2)
{
  signed int v2; // r3
  signed int result; // r0
  bool v4; // zf

  v2 = 0xFFFF;
  *(_DWORD *)(a2 + 24) = a1;
  while ( 1 )
  {
    v4 = v2-- == 0;
    if ( v4 )
      break;
    if ( *(_DWORD *)(a2 + 24) >= 0 )
      return 0;
  }
  if ( v2 >= 0 )
    result = 0;
  else
    result = -1;
  return result;
}

//----- (FFFF481C) --------------------------------------------------------
signed int __fastcall sub_FFFF481C(int a1, int a2, int a3)
{
  int v3; // r7
  int v4; // r6
  int v5; // r5
  signed int result; // r0

  v3 = a1;
  v4 = a2;
  v5 = a3;
  *(_DWORD *)(a3 + 4) &= 0xFFFEFFFF;
  if ( sub_FFFF47D4(-2145378304, a3) )
    return -1;
  if ( v3 )
  {
    dword_1C2008C &= 0x7FFFFFFFu;
    dword_1C2008C = dword_1C2008C & 0xFFFCFFF0 | v4 | 0x80000000;
  }
  else
  {
    dword_1C20088 &= 0x7FFFFFFFu;
    dword_1C20088 = dword_1C20088 & 0xFFFCFFF0 | v4 | 0x80000000;
  }
  *(_DWORD *)(v5 + 4) &= 0xFFFFFF00;
  if ( sub_FFFF47D4(-2145378304, v5) )
    return -1;
  *(_DWORD *)(v5 + 4) |= 0x10000u;
  if ( sub_FFFF47D4(-2145378304, v5) )
    result = -1;
  else
    result = 0;
  return result;
}
// 1C20088: using guessed type int dword_1C20088;
// 1C2008C: using guessed type int dword_1C2008C;

//----- (FFFF4914) --------------------------------------------------------
int __fastcall sub_FFFF4914(int a1)
{
  if ( a1 == 1 )
  {
    dword_1C202C0 &= 0xFFFFFDFF;
    dword_1C202C0 |= 0x200u;
    dword_1C20060 |= 0x200u;
    dword_1C2008C = (dword_1C2008C | 0x80000000) & 0xFCFCFFF0;
    dword_1C20848 = ((unsigned int)dword_1C20848 >> 12 << 12) | 0x333;
    dword_1C20864 = dword_1C20864 & 0xFFFFFFC0 | 0x15;
  }
  else if ( !a1 )
  {
    dword_1C202C0 &= 0xFFFFFEFF;
    dword_1C202C0 |= 0x100u;
    dword_1C20060 |= 0x100u;
    dword_1C20088 = (dword_1C20088 | 0x80000000) & 0xFCFCFFF0;
    dword_1C208B4 = 2236962;
    dword_1C208D0 = 1365;
  }
  return 0;
}
// 1C20060: using guessed type int dword_1C20060;
// 1C20088: using guessed type int dword_1C20088;
// 1C2008C: using guessed type int dword_1C2008C;
// 1C202C0: using guessed type int dword_1C202C0;
// 1C20848: using guessed type int dword_1C20848;
// 1C20864: using guessed type int dword_1C20864;
// 1C208B4: using guessed type int dword_1C208B4;
// 1C208D0: using guessed type int dword_1C208D0;

//----- (FFFF49F4) --------------------------------------------------------
signed int __fastcall sub_FFFF49F4(int *a1)
{
  signed int v1; // r12
  int v2; // r2
  unsigned int i; // r3

  v1 = 0xFFFF;
  LOBYTE(v2) = 7;
  *a1 = 7;
  while ( v2 & 7 )
  {
    if ( --v1 < 0 )
      return -1;
    v2 = *a1;
  }
  for ( i = 0; i < 0x32; ++i )
    ;
  a1[14] |= 0xFFFFu;
  *a1 &= 0xFFFFFFDF;
  a1[16] = 458760;
  return 0;
}

//----- (FFFF4A68) --------------------------------------------------------
int __fastcall sub_FFFF4A68(int a1)
{
  if ( a1 == 1 )
  {
    dword_1C2008C &= 0x7FFFFFFFu;
    dword_1C20060 &= 0xFFFFFDFF;
    dword_1C202C0 &= 0xFFFFFDFF;
    dword_1C20848 = 30583;
    dword_1C20864 = 4;
  }
  else if ( !a1 )
  {
    dword_1C20088 &= 0x7FFFFFFFu;
    dword_1C20060 &= 0xFFFFFEFF;
    dword_1C202C0 &= 0xFFFFFEFF;
    dword_1C208B4 = 3618611;
    dword_1C208D0 = 0;
  }
  return 0;
}
// 1C20060: using guessed type int dword_1C20060;
// 1C20088: using guessed type int dword_1C20088;
// 1C2008C: using guessed type int dword_1C2008C;
// 1C202C0: using guessed type int dword_1C202C0;
// 1C20848: using guessed type int dword_1C20848;
// 1C20864: using guessed type int dword_1C20864;
// 1C208B4: using guessed type int dword_1C208B4;
// 1C208D0: using guessed type int dword_1C208D0;

//----- (FFFF4B08) --------------------------------------------------------
signed int __fastcall sub_FFFF4B08(int a1, _DWORD *a2, _DWORD *a3)
{
  int v3; // r7
  _DWORD *v4; // r6
  _DWORD *v5; // r5
  signed int result; // r0

  v3 = a1;
  v4 = a2;
  v5 = a3;
  a3[2] = a2[5] & 0xFF | (a2[4] << 8);
  a3[4] = a2[3] & 0xFFFF;
  a3[3] = a2[2] & 3;
  a3[1] &= 0xFFFEFFFF;
  if ( sub_FFFF47D4(-2145378304, (int)a3) )
    return -1;
  if ( v3 )
  {
    dword_1C2008C &= 0x7FFFFFFFu;
    dword_1C2008C = dword_1C2008C & 0xFFFCFFF0 | *v4 | 0x80000000;
  }
  else
  {
    dword_1C20088 &= 0x7FFFFFFFu;
    dword_1C20088 = dword_1C20088 & 0xFFFCFFF0 | *v4 | 0x80000000;
  }
  v5[1] &= 0xFFFFFF00;
  if ( sub_FFFF47D4(-2145378304, (int)v5) )
    return -1;
  v5[1] |= ((v4[1] & 1) << 17) | 0x10000;
  if ( sub_FFFF47D4(-2145378304, (int)v5) )
    result = -1;
  else
    result = 0;
  return result;
}
// 1C20088: using guessed type int dword_1C20088;
// 1C2008C: using guessed type int dword_1C2008C;

//----- (FFFF4C50) --------------------------------------------------------
signed int __fastcall sub_FFFF4C50(int a1, int a2, unsigned int a3, int *a4)
{
  int v4; // r9
  int v5; // r10
  unsigned int v6; // r7
  int *v7; // r4
  signed int v8; // r11
  unsigned int i; // r6
  signed int v10; // r5
  signed int v11; // r5
  bool v12; // zf
  signed int v13; // r5
  int v15; // r8
  signed int v16; // r5
  char v17; // [sp+4h] [bp-34h]

  v4 = a1;
  v5 = a2;
  v6 = a3;
  v7 = a4;
  v8 = 0;
  a4[5] = a3;
  *a4 |= 0x80000000;
  if ( sub_FFFF45E8(a1, &v17, a4) )
  {
    v8 = -1;
  }
  else
  {
    for ( i = 0; i < v6 >> 2; ++i )
    {
      v10 = 0x7FFFF;
      do
        --v10;
      while ( v10 && v7[15] & 4 );
      if ( v10 <= 0 )
      {
        v8 = -1;
        goto LABEL_25;
      }
      *(_DWORD *)(v5 + 4 * i) = v7[128];
    }
    v11 = 0x7FFFF;
    do
      v12 = v11-- == 0;
    while ( !v12 && !(v7[14] & 8) );
    v7[14] = 8;
    if ( v11 < 0 )
      v8 = -1;
    if ( v7[14] & (unsigned int)&unk_BE80 )
      v8 = -1;
    if ( *(_DWORD *)(v4 + 8) & 0x80 )
    {
      v13 = 0xFFFFF;
      do
        v12 = v13-- == 0;
      while ( !v12 && !(v7[14] & 0x4000) );
      v7[14] = 0x4000;
      if ( v13 < 0 )
        v8 = -1;
      goto LABEL_30;
    }
  }
LABEL_25:
  *v7 &= 0x7FFFFFFFu;
  v7[14] = 0xFFFF;
  if ( sub_FFFF4750(v7) )
  {
    v8 = -1;
  }
  else if ( !v8 )
  {
    v7[14] = 0xFFFF;
    return 0;
  }
LABEL_30:
  v7[14] = 0xFFFF;
  LOBYTE(v15) = 3;
  *v7 = 3;
  v16 = 0xFFFF;
  while ( v15 & 3 )
  {
    if ( --v16 < 0 )
      return -1;
    v15 = *v7;
  }
  v7[4] = 512;
  return v8;
}

//----- (FFFF4E5C) --------------------------------------------------------
signed int __fastcall sub_FFFF4E5C(_DWORD *a1)
{
  signed int result; // r0
  int v2; // [sp+0h] [bp-18h]
  int v3; // [sp+4h] [bp-14h]
  int v4; // [sp+8h] [bp-10h]

  v2 = 0;
  BYTE1(v2) = 0;
  v3 = 0;
  v4 = 2048;
  if ( sub_FFFF45E8((int)&v2, 0, a1) )
    result = -1;
  else
    result = 0;
  return result;
}

//----- (FFFF4EC0) --------------------------------------------------------
signed int __fastcall sub_FFFF4EC0(int a1, _DWORD *a2)
{
  signed int result; // r0
  int v3; // [sp+0h] [bp-28h]
  int v4; // [sp+10h] [bp-18h]
  int v5; // [sp+14h] [bp-14h]
  int v6; // [sp+18h] [bp-10h]

  v4 = 0;
  v5 = 0;
  v6 = 0;
  BYTE1(v4) = 2;
  v5 = *(_DWORD *)(a1 + 8) << 16;
  v6 = 263;
  if ( sub_FFFF45E8((int)&v4, &v3, a2) )
    result = -1;
  else
    result = 0;
  return result;
}

//----- (FFFF4F4C) --------------------------------------------------------
signed int __fastcall sub_FFFF4F4C(int a1, _DWORD *a2)
{
  int v2; // r4
  _DWORD *v3; // r5
  signed int result; // r0
  int v5; // [sp+0h] [bp-28h]
  int v6; // [sp+10h] [bp-18h]
  int v7; // [sp+14h] [bp-14h]
  unsigned int v8; // [sp+18h] [bp-10h]

  v2 = a1;
  v3 = a2;
  v6 = 0;
  v7 = 0;
  v8 = 0;
  if ( sub_FFFF4E5C(a2) )
    return -1;
  LOWORD(v6) = 256;
  v7 = 426;
  v8 = v8 & 0xFFFFFFC0 | 8;
  if ( sub_FFFF45E8((int)&v6, &v5, v3) || (v5 & 0xFFF) != 426 )
  {
    LOWORD(v6) = 513;
    v7 = 0;
    v8 = v8 & 0xFFFFFFC0 | 0x37;
    if ( sub_FFFF45E8((int)&v6, &v5, v3)
      || (BYTE1(v6) = 1, v7 = 1090453504, v8 = v8 & 0xFFFFFFC0 | 0x29, sub_FFFF45E8((int)&v6, &v5, v3)) )
    {
      *(_DWORD *)(v2 + 4) = 2;
      result = 0;
    }
    else
    {
      *(_DWORD *)(v2 + 4) = 1;
      result = 0;
    }
  }
  else
  {
    *(_DWORD *)(v2 + 4) = 1;
    result = 0;
  }
  return result;
}

//----- (FFFF5088) --------------------------------------------------------
signed int __fastcall sub_FFFF5088(int a1, _DWORD *a2)
{
  int v2; // r4
  _DWORD *v3; // r5
  signed int v4; // r6
  signed int v5; // r7
  unsigned int v7; // r8
  unsigned int v8; // r0
  int v9; // [sp+4h] [bp-34h]
  int v10; // [sp+14h] [bp-24h]
  int v11; // [sp+18h] [bp-20h]
  unsigned int v12; // [sp+1Ch] [bp-1Ch]

  v2 = a1;
  v3 = a2;
  v4 = 0;
  v5 = 200;
  v10 = 0;
  v11 = 0;
  v12 = 0;
  if ( sub_FFFF4E5C(a2) )
    return -1;
  v10 = 0;
  BYTE1(v10) = 1;
  v11 = 426;
  v12 = 8;
  if ( !sub_FFFF45E8((int)&v10, &v9, v3) && (v9 & 0xFFF) == 426 )
    v4 = 1;
  do
  {
    if ( v5 <= 0 )
      return -1;
    --v5;
    v10 = 0;
    LOWORD(v10) = 513;
    v11 = 0;
    v12 = 55;
    if ( sub_FFFF45E8((int)&v10, &v9, v3) )
      return -1;
    BYTE1(v10) = 1;
    if ( v4 )
      v11 |= 0x40000000u;
    v11 |= 0xFC0000u;
    v12 = v12 & 0xFFFFFFC0 | 0x29;
    if ( sub_FFFF45E8((int)&v10, &v9, v3) )
      return -1;
    if ( (v9 & 0xFC0000) != 16515072 )
      return -1;
    v7 = 0;
    do
      v8 = v7++;
    while ( v8 < 0x4E2 );
  }
  while ( v9 >= 0 );
  if ( v4 )
  {
    if ( v9 & 0x40000000 )
      *(_DWORD *)(v2 + 4) |= 0x20u;
  }
  return 0;
}

//----- (FFFF5270) --------------------------------------------------------
signed int __fastcall sub_FFFF5270(int a1, _DWORD *a2)
{
  int v2; // r4
  _DWORD *v3; // r5
  signed int v4; // r6
  unsigned int v6; // r7
  unsigned int v7; // r0
  int v8; // [sp+0h] [bp-30h]
  int v9; // [sp+10h] [bp-20h]
  int v10; // [sp+14h] [bp-1Ch]
  unsigned int v11; // [sp+18h] [bp-18h]

  v2 = a1;
  v3 = a2;
  v4 = 200;
  v9 = 0;
  v10 = 0;
  v11 = 0;
  if ( sub_FFFF4E5C(a2) )
    return -1;
  LOWORD(v9) = 258;
  v10 = 1090486272;
  v11 = v11 & 0xFFFFFFC0 | 1;
  while ( 1 )
  {
    if ( v4 <= 0 )
      return -1;
    --v4;
    if ( sub_FFFF45E8((int)&v9, &v8, v3) )
      return -1;
    if ( (v8 & 0xFF8000) != 16744448 )
      return -1;
    if ( v8 < 0 )
      break;
    v6 = 0;
    do
      v7 = v6++;
    while ( v7 < 0x4E2 );
  }
  if ( v8 & 0x40000000 )
    *(_DWORD *)(v2 + 4) |= 0x20u;
  return 0;
}

//----- (FFFF5380) --------------------------------------------------------
signed int __fastcall sub_FFFF5380(_DWORD *a1)
{
  signed int result; // r0
  char v2; // [sp+4h] [bp-24h]
  int v3; // [sp+14h] [bp-14h]
  int v4; // [sp+18h] [bp-10h]
  int v5; // [sp+1Ch] [bp-Ch]

  v3 = 0;
  BYTE1(v3) = 1;
  v4 = 0;
  v5 = 66;
  if ( sub_FFFF45E8((int)&v3, &v2, a1) )
    result = -1;
  else
    result = 0;
  return result;
}

//----- (FFFF53F8) --------------------------------------------------------
signed int __fastcall sub_FFFF53F8(int a1, _DWORD *a2)
{
  int v2; // r4
  unsigned int v4; // [sp+0h] [bp-28h]
  int v5; // [sp+10h] [bp-18h]
  int v6; // [sp+14h] [bp-14h]
  int v7; // [sp+18h] [bp-10h]

  v2 = a1;
  v5 = 0;
  BYTE1(v5) = 1;
  v6 = 0;
  v7 = 259;
  if ( sub_FFFF45E8((int)&v5, &v4, a2) )
    return -1;
  *(_DWORD *)(v2 + 8) = v4 >> 16;
  return 0;
}

//----- (FFFF5490) --------------------------------------------------------
signed int __fastcall sub_FFFF5490(int a1, int a2, _DWORD *a3, int a4)
{
  int v4; // r6
  int v5; // r4
  _DWORD *v6; // r5
  int v8; // [sp+0h] [bp-28h]

  v4 = a1;
  v5 = a2;
  v6 = a3;
  sub_FFFF600C(&v8, (int *)&unk_FFFF6298, 0x18u, a4);
  v8 = 131086;
  if ( sub_FFFF4B08(v4, &v8, v6) )
    return -1;
  if ( sub_FFFF4F4C(v5, v6) )
    return -1;
  if ( *(_DWORD *)(v5 + 4) == 1 )
  {
    if ( sub_FFFF5088(v5, v6) == -1 )
      return -1;
  }
  else if ( sub_FFFF5270(v5, v6) == -1 )
  {
    return -1;
  }
  if ( sub_FFFF5380(v6) )
    return -1;
  if ( sub_FFFF53F8(v5, v6) )
    return -1;
  *(_DWORD *)(v5 + 4) &= 0xFFFFFFEF;
  return 0;
}

//----- (FFFF5588) --------------------------------------------------------
signed int __fastcall sub_FFFF5588(int a1, int a2, _DWORD *a3)
{
  int v3; // r6
  _DWORD *v4; // r5
  signed int result; // r0
  int v6; // [sp+0h] [bp-28h]
  char v7; // [sp+4h] [bp-24h]
  int v8; // [sp+8h] [bp-20h]
  int v9; // [sp+Ch] [bp-1Ch]
  int v10; // [sp+10h] [bp-18h]
  int v11; // [sp+14h] [bp-14h]

  v3 = a1;
  v4 = a3;
  if ( sub_FFFF4EC0(a2, a3) )
    return -1;
  v6 = 1;
  v8 = 0;
  v7 = 0;
  v9 = 512;
  v10 = 0xFFFFFF;
  v11 = 255;
  if ( sub_FFFF4B08(v3, &v6, v4) )
    result = -1;
  else
    result = 0;
  return result;
}

//----- (FFFF5610) --------------------------------------------------------
signed int __fastcall sub_FFFF5610(int a1, int a2, int *a3)
{
  int v3; // r5
  int v4; // r6
  int *v5; // r4
  int v6; // r3

  v3 = a1;
  v4 = a2;
  v5 = a3;
  sub_FFFF4914(a1);
  if ( sub_FFFF49F4(v5) )
    return -1;
  if ( sub_FFFF5490(v3, v4, v5, v6) )
    return -1;
  if ( sub_FFFF5588(v3, v4, v5) )
    return -1;
  return 0;
}

//----- (FFFF5688) --------------------------------------------------------
int __fastcall sub_FFFF5688(int a1)
{
  return sub_FFFF4A68(a1);
}

//----- (FFFF569C) --------------------------------------------------------
signed int __fastcall sub_FFFF569C(int a1, int a2, int a3, int a4, int *a5)
{
  signed int result; // r0
  int v6; // [sp+4h] [bp-2Ch]
  int v7; // [sp+8h] [bp-28h]
  unsigned int v8; // [sp+Ch] [bp-24h]

  v6 = 0;
  v7 = 0;
  v8 = 256;
  LOWORD(v6) = 768;
  if ( a2 == 1 )
    v8 = v8 & 0xFFFFFFC0 | 0x11;
  else
    v8 = (v8 & 0xFFFFFFC0 | 0x12) & 0xFFFFFF7F;
  if ( *(_DWORD *)(a4 + 4) & 0x20 )
    v7 = a1;
  else
    v7 = a1 << 9;
  if ( sub_FFFF4C50((int)&v6, a3, a2 << 9, a5) )
    result = -1;
  else
    result = 0;
  return result;
}

//----- (FFFF57D0) --------------------------------------------------------
signed int sub_FFFF57D0()
{
  signed int result; // r0

  dword_1C20848 = 8738;
  result = 4;
  dword_1C20864 = 4;
  return result;
}
// 1C20848: using guessed type int dword_1C20848;
// 1C20864: using guessed type int dword_1C20864;

//----- (FFFF57EC) --------------------------------------------------------
signed int sub_FFFF57EC()
{
  signed int result; // r0

  dword_1C20848 = 30583;
  result = 4;
  dword_1C20864 = 4;
  return result;
}
// 1C20848: using guessed type int dword_1C20848;
// 1C20864: using guessed type int dword_1C20864;

//----- (FFFF5808) --------------------------------------------------------
signed int SPI0_Init()
{
  signed int result; // r0

  dword_1C202C0 |= 0x100000u;
  dword_1C20060 |= 0x100000u;
  sub_FFFF57D0();
  dword_1C20060 |= 0x40u;
  dword_1C202C0 |= 0x40u;
  dword_1C05024 = 4097;
  dword_1C05004 = -2147483517;
  dword_1C05008 = 388;
  dword_1C05018 = -2145353696;
  dword_1C05010 = 0;
  result = -1;
  dword_1C05014 = -1;
  return result;
}
// 1C05004: using guessed type int dword_1C05004;
// 1C05008: using guessed type int dword_1C05008;
// 1C05010: using guessed type int dword_1C05010;
// 1C05014: using guessed type int dword_1C05014;
// 1C05018: using guessed type int dword_1C05018;
// 1C05024: using guessed type int dword_1C05024;
// 1C20060: using guessed type int dword_1C20060;
// 1C202C0: using guessed type int dword_1C202C0;

//----- (FFFF5890) --------------------------------------------------------
unsigned int SPI0_DeInit()
{
  unsigned int result; // r0

  dword_1C05004 = 0;
  sub_FFFF57EC();
  dword_1C20060 &= 0xFFFFFFBF;
  dword_1C202C0 &= 0xFFFFFFBF;
  dword_1C20060 &= 0xFFEFFFFF;
  result = dword_1C202C0 & 0xFFEFFFFF;
  dword_1C202C0 &= 0xFFEFFFFF;
  return result;
}
// 1C05004: using guessed type int dword_1C05004;
// 1C20060: using guessed type int dword_1C20060;
// 1C202C0: using guessed type int dword_1C202C0;

//----- (FFFF58EC) --------------------------------------------------------
signed int __fastcall DMA_busy_wait(int a1)
{
  int v1; // r1

  v1 = a1;
  do
  {
    if ( !(dword_1C02120 & 0x40000000) )
      return 0;
    --v1;
  }
  while ( v1 );
  return 2;
}
// 1C02120: using guessed type int dword_1C02120;

//----- (FFFF5920) --------------------------------------------------------
signed int __fastcall sub_FFFF5920(int a1)
{
  int v1; // r1

  v1 = a1;
  do
  {
    if ( dword_1C05014 & 0x1000 )
      return 0;
    --v1;
  }
  while ( v1 );
  return 2;
}
// 1C05014: using guessed type int dword_1C05014;

//----- (FFFF5954) --------------------------------------------------------
signed int __fastcall sub_FFFF5954(unsigned int a1, int a2, int a3, int a4)
{
  unsigned int v4; // r4
  int v5; // r5
  char *v6; // r9
  unsigned int v7; // r1
  unsigned int v8; // r0
  unsigned int i; // r6
  signed int result; // r0

  v4 = a1;
  v5 = a2;
  v6 = (char *)&unk_2710 + 2 * (a1 + a2);
  *(_DWORD *)((char *)&unk_34 + ((unsigned int)&unk_1C05300 & ~(unsigned int)&unk_2710)) = a1;
  v7 = (unsigned int)&unk_1C05300 & ~(unsigned int)&unk_2710;
  *(_DWORD *)((char *)&unk_30 + v7) = a1 + v5;
  v8 = (unsigned int)&unk_1C05300 & ~(unsigned int)&unk_2710;
  *(_DWORD *)((char *)&unk_38 + v8) = v4;
  *(_DWORD *)((char *)&unk_18 + v7) = *(_DWORD *)((char *)&unk_18 + v8) | 0x100;
  for ( i = 0; i < v4; ++i )
    byte_1C05200 = *(_BYTE *)(a3 + i);
  dword_1C02124 = (int)&unk_1C05300;
  dword_1C02128 = a4;
  dword_1C0212C = v5;
  dword_1C02120 = 0x8C100024;
  dword_1C05008 |= 0x80000000;
  if ( DMA_busy_wait((int)v6) == 2 )
  {
    dword_1C02120 &= 0x7FFFFFFFu;
    result = 2;
  }
  else if ( sub_FFFF5920((int)v6) == 2 )
  {
    dword_1C02120 &= 0x7FFFFFFFu;
    result = 2;
  }
  else
  {
    dword_1C02120 &= 0x7FFFFFFFu;
    dword_1C05014 |= 0x1000u;
    result = 0;
  }
  return result;
}
// 1C02120: using guessed type int dword_1C02120;
// 1C02124: using guessed type int dword_1C02124;
// 1C02128: using guessed type int dword_1C02128;
// 1C0212C: using guessed type int dword_1C0212C;
// 1C05008: using guessed type int dword_1C05008;
// 1C05014: using guessed type int dword_1C05014;
// 1C05200: using guessed type char byte_1C05200;

//----- (FFFF5A78) --------------------------------------------------------
signed int __fastcall sub_FFFF5A78(unsigned int a1, int a2)
{
  unsigned int i; // r5

  dword_1C05034 = a1;
  dword_1C05030 = a1;
  dword_1C05038 = a1;
  dword_1C05008 = *(_DWORD *)((char *)&unk_8 + ((unsigned int)&byte_1C05200 & ~(unsigned int)&unk_2710)) | 0x80000000;
  for ( i = 0; i < a1; ++i )
    byte_1C05200 = *(_BYTE *)(a2 + i);
  if ( sub_FFFF5920((int)&unk_2710 + 2 * a1) == 2 )
    return 2;
  dword_1C05014 |= 0x1000u;
  return 0;
}
// 1C05008: using guessed type int dword_1C05008;
// 1C05014: using guessed type int dword_1C05014;
// 1C05030: using guessed type int dword_1C05030;
// 1C05034: using guessed type int dword_1C05034;
// 1C05038: using guessed type int dword_1C05038;
// 1C05200: using guessed type char byte_1C05200;

//----- (FFFF5B04) --------------------------------------------------------
signed int __fastcall spi_loader_0__(int a1, int a2, int a3, int a4)
{
  int v4; // r11
  unsigned int v5; // r4
  int v6; // r5
  unsigned int v7; // r7
  int v8; // r0
  int v9; // r6
  int v11; // [sp+0h] [bp-28h]

  v11 = a4;
  v4 = a2;
  v5 = 0;
  v6 = a1 << 8;
  v7 = a3 << 8;
  while ( v5 < v7 )
  {
    LOBYTE(v11) = 3;
    BYTE1(v11) = (unsigned int)(v6 << 8) >> 24;
    BYTE2(v11) = (unsigned int)(v6 << 16) >> 24;
    HIBYTE(v11) = v6;
    if ( v7 - v5 <= 0x800 )
      v8 = v7 - v5;
    else
      v8 = 2048;
    v9 = v8;
    if ( sub_FFFF5954(4u, v8, (int)&v11, v4 + v5) == 2 )
      return 2;
    v6 += v9;
    v5 += v9;
  }
  return 0;
}

//----- (FFFF5BA4) --------------------------------------------------------
signed int __fastcall spi_loader_1__(int a1, int a2, int a3)
{
  unsigned int v3; // r7
  int v4; // r10
  unsigned int v5; // r8
  int v6; // r9
  int v7; // r4
  int v9; // [sp+0h] [bp-28h]
  int v10; // [sp+4h] [bp-24h]

  v9 = a3;
  v3 = a3;
  v4 = a2;
  v10 = 0;
  v5 = 0;
  v6 = 0;
  v7 = a1 << 9;
  while ( v5 < v3 )
  {
    LOBYTE(v9) = -24;
    BYTE1(v9) = (unsigned int)(v7 << 8) >> 24;
    BYTE2(v9) = (unsigned int)(v7 << 16) >> 24;
    HIBYTE(v9) = v7;
    if ( sub_FFFF5954(8u, 256, (int)&v9, v4 + v6) == 2 )
      return 2;
    ++v5;
    v6 += 256;
    v7 += 512;
  }
  return 0;
}

//----- (FFFF5C34) --------------------------------------------------------
signed int sub_FFFF5C34()
{
  signed int v0; // r4
  int v2; // [sp+0h] [bp-10h]

  v2 = 255;
  v0 = 1000;
  if ( sub_FFFF5A78(1u, (int)&v2) == 2 )
    return 2;
  do
    --v0;
  while ( v0 );
  return 0;
}

//----- (FFFF5C78) --------------------------------------------------------
int __fastcall get_loader_ptr__(int a1)
{
  signed int (__fastcall *v2)(int, int, int, int); // [sp+0h] [bp-Ch]
  signed int (__fastcall *v3)(int, int, int); // [sp+4h] [bp-8h]

  v2 = spi_loader_0__;
  v3 = spi_loader_1__;
  return (int)*(&v2 + a1);
}

//----- (FFFF5C94) --------------------------------------------------------
signed int __fastcall sub_FFFF5C94(unsigned int a1, int a2, int a3, int a4, int a5, unsigned int a6)
{
  unsigned int v6; // r5
  int v7; // r8
  int v8; // r6
  int v9; // r10
  signed int v10; // r11
  unsigned int i; // r4
  int v13; // [sp+0h] [bp-30h]
  int v14; // [sp+4h] [bp-2Ch]
  int v15; // [sp+8h] [bp-28h]

  v14 = a3;
  v15 = a4;
  v6 = a1;
  v7 = a3;
  v8 = a4;
  v9 = a2;
  v13 = 0;
  v10 = 50;
  for ( i = a1; v6 + v7 > i; ++i )
  {
    LOBYTE(v15) = 19;
    BYTE1(v15) = i << 8 >> 24;
    BYTE2(v15) = i << 16 >> 24;
    HIBYTE(v15) = i;
    if ( sub_FFFF5A78(4u, (int)&v15) == 2 )
      return 2;
    LOWORD(v14) = -16369;
    do
    {
      if ( sub_FFFF5954(2u, 1, (int)&v14, (int)&v13) == 2 )
        return 2;
      if ( !(v13 & 1) )
        break;
      --v10;
    }
    while ( v10 );
    LOBYTE(v15) = 11;
    if ( a5 != 1 || (sub_FFFF6240(i, a6) & 1) != 1 )
      BYTE1(v15) = 0;
    else
      BYTE1(v15) = 16;
    HIWORD(v15) = 0;
    if ( sub_FFFF5954(4u, v8, (int)&v15, v9 + v8 * (i - v6)) == 2 )
      return 2;
  }
  return 0;
}

//----- (FFFF5E1C) --------------------------------------------------------
signed int load_SPI_2()
{
  unsigned int i; // r5
  int (__fastcall *v1)(int, int, int, int); // r6
  unsigned int v2; // r4

  SPI0_Init();
  for ( i = 0; i < 2; ++i )
  {
    v1 = (int (__fastcall *)(int, int, int, int))get_loader_ptr__(i);
    if ( ((int (__fastcall *)(_DWORD))v1)(0) != 2 && !eGON_str_cmp(0, "eGON.BT0") )
    {
      v2 = dword_10;
      if ( !(_BYTE)dword_10 && ((int (__fastcall *)(_DWORD))v1)(0) != 2 && !sub_FFFF5F2C(0, v2) )
      {
        SPI0_DeInit();
        return 0;
      }
    }
  }
  SPI0_DeInit();
  return -1;
}
// 10: using guessed type int dword_10;

//----- (FFFF5EE4) --------------------------------------------------------
signed int __fastcall eGON_str_cmp(int a1, unsigned __int8 *a2)
{
  unsigned __int8 *v2; // r12
  unsigned int i; // r3
  int v4; // r0
  int v5; // t1
  int v6; // t1

  v2 = (unsigned __int8 *)(a1 + 4);
  for ( i = 0; i < 8; ++i )
  {
    v5 = *v2++;
    v4 = v5;
    v6 = *a2++;
    if ( v4 != v6 )
      return 1;
  }
  return 0;
}

//----- (FFFF5F2C) --------------------------------------------------------
BOOL __fastcall sub_FFFF5F2C(int *a1, unsigned int a2)
{
  int v2; // r5
  unsigned int v3; // r6
  int v4; // r2
  int *v5; // r1
  int *v6; // r1
  int v7; // t1
  int v8; // r2
  int v9; // t1
  int v10; // r2
  int v11; // t1
  int v12; // r2
  int v13; // t1
  int v14; // t1
  bool v15; // zf

  v2 = a1[3];
  a1[3] = 0x5F0A6C39;
  v3 = a2 >> 2;
  v4 = 0;
  v5 = a1;
  do
  {
    v7 = *v5;
    v6 = v5 + 1;
    v8 = v4 + v7;
    v9 = *v6;
    ++v6;
    v10 = v8 + v9;
    v11 = *v6;
    ++v6;
    v12 = v10 + v11;
    v13 = *v6;
    v5 = v6 + 1;
    v4 = v12 + v13;
    v3 -= 4;
  }
  while ( v3 > 3 );
  while ( 1 )
  {
    v15 = v3-- == 0;
    if ( v15 )
      break;
    v14 = *v5;
    ++v5;
    v4 += v14;
  }
  a1[3] = v2;
  return v4 != v2;
}

//----- (FFFF600C) --------------------------------------------------------
_DWORD *__fastcall sub_FFFF600C(_DWORD *result, int *a2, unsigned int a3, int a4)
{
  unsigned int i; // r2
  int *v5; // r1
  int v6; // r3
  int v7; // r4
  int v8; // r12
  int v9; // lr
  int *v10; // r0
  int v11; // r4
  int v12; // r12
  int v13; // lr
  int v14; // r4
  int v15; // r12
  int v16; // lr
  int v17; // r4
  int v18; // t1
  bool v19; // cf
  bool v20; // nf
  signed int v21; // r2
  __int16 v22; // t1

  v19 = a3 >= 0x20;
  for ( i = a3 - 32; v19; result = v10 + 4 )
  {
    v6 = *a2;
    v7 = a2[1];
    v8 = a2[2];
    v9 = a2[3];
    v5 = a2 + 4;
    v19 = i >= 0x20;
    i -= 32;
    *result = v6;
    result[1] = v7;
    result[2] = v8;
    result[3] = v9;
    v10 = result + 4;
    a4 = *v5;
    v11 = v5[1];
    v12 = v5[2];
    v13 = v5[3];
    a2 = v5 + 4;
    *v10 = a4;
    v10[1] = v11;
    v10[2] = v12;
    v10[3] = v13;
  }
  if ( __CFSHL__(i, 28) )
  {
    a4 = *a2;
    v14 = a2[1];
    v15 = a2[2];
    v16 = a2[3];
    a2 += 4;
    *result = a4;
    result[1] = v14;
    result[2] = v15;
    result[3] = v16;
    result += 4;
  }
  if ( ((i << 28) & 0x80000000) != 0 )
  {
    a4 = *a2;
    v17 = a2[1];
    a2 += 2;
    *result = a4;
    result[1] = v17;
    result += 2;
  }
  if ( __CFSHL__(i, 30) )
  {
    v18 = *a2;
    ++a2;
    LOWORD(a4) = v18;
    *result = v18;
    ++result;
  }
  if ( i << 30 )
  {
    v19 = __CFSHL__(i, 31);
    v21 = i << 31;
    v20 = v21 < 0;
    if ( v19 )
    {
      v22 = *(_WORD *)a2;
      a2 = (int *)((char *)a2 + 2);
      LOWORD(a4) = v22;
    }
    if ( v21 < 0 )
      LOBYTE(v21) = *(_BYTE *)a2;
    if ( v19 )
    {
      *(_WORD *)result = a4;
      result = (_DWORD *)((char *)result + 2);
    }
    if ( v20 )
    {
      *(_BYTE *)result = v21;
      result = (_DWORD *)((char *)result + 1);
    }
  }
  return result;
}

//----- (FFFF6070) --------------------------------------------------------
_DWORD *__fastcall sub_FFFF6070(_DWORD *result, unsigned int a2)
{
  bool v2; // cf
  unsigned int v3; // r1
  _DWORD *v4; // r0
  signed int v5; // r1
  int v6; // r1

  v2 = a2 >= 0x20;
  v3 = a2 - 32;
  do
  {
    if ( !v2 )
      break;
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    v4 = result + 4;
    *v4 = 0;
    v4[1] = 0;
    v4[2] = 0;
    v4[3] = 0;
    result = v4 + 4;
    v2 = v3 >= 0x20;
    v3 -= 32;
  }
  while ( v2 );
  v2 = __CFSHL__(v3, 28);
  v5 = v3 << 28;
  if ( v2 )
  {
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    result += 4;
  }
  if ( v5 < 0 )
  {
    *result = 0;
    result[1] = 0;
    result += 2;
  }
  v2 = __CFSHL__(v5, 2);
  v6 = 4 * v5;
  if ( v2 )
  {
    *result = 0;
    ++result;
  }
  if ( v6 )
  {
    if ( v6 < 0 )
    {
      *(_WORD *)result = 0;
      result = (_DWORD *)((char *)result + 2);
    }
    if ( v6 & 0x40000000 )
    {
      *(_BYTE *)result = 0;
      result = (_DWORD *)((char *)result + 1);
    }
  }
  return result;
}

//----- (FFFF6240) --------------------------------------------------------
int __fastcall sub_FFFF6240(unsigned int a1, unsigned int a2)
{
  bool v2; // cf
  BOOL v3; // r2
  bool v4; // cf
  int v5; // r2
  bool v6; // cf
  bool v7; // cf
  int v8; // r2
  bool v9; // cf
  int v10; // r2
  bool v11; // cf
  bool v12; // cf
  unsigned int v14; // r1
  int v15; // r2
  char v16; // cf
  bool v17; // cf
  int v18; // r2
  bool v19; // cf
  int v20; // r2
  bool v21; // cf
  int v22; // r2
  bool v23; // cf
  int v24; // r2
  bool v25; // cf
  int v26; // r2
  bool v27; // cf
  int v28; // off
  bool v29; // cf
  int v30; // r2

  v30 = 0;
  if ( a1 >> 2 < a2 )
  {
LABEL_18:
    v12 = a1 >> 1 >= a2;
    if ( a1 >> 1 >= a2 )
      a1 -= 2 * a2;
    return v30 + v12 + v30 + (a1 >= a2) + v30 + v12 + v30;
  }
  if ( a1 >> 5 < a2 )
  {
LABEL_11:
    v7 = a1 >> 4 >= a2;
    if ( a1 >> 4 >= a2 )
      a1 -= 16 * a2;
    v8 = v30 + v7 + v30;
    v9 = a1 >> 3 >= a2;
    if ( a1 >> 3 >= a2 )
      a1 -= 8 * a2;
    v10 = v8 + v9 + v8;
    v11 = a1 >> 2 >= a2;
    if ( a1 >> 2 >= a2 )
      a1 -= 4 * a2;
    v30 = v10 + v11 + v10;
    goto LABEL_18;
  }
  if ( a1 >> 8 < a2 )
  {
    v2 = a1 >> 7 >= a2;
    if ( a1 >> 7 >= a2 )
      a1 -= a2 << 7;
    v3 = v2;
    v4 = a1 >> 6 >= a2;
    if ( a1 >> 6 >= a2 )
      a1 -= a2 << 6;
    v5 = v3 + v4 + v3;
    v6 = a1 >> 5 >= a2;
    if ( a1 >> 5 >= a2 )
      a1 -= 32 * a2;
    v30 = v5 + v6 + v5;
    goto LABEL_11;
  }
  v14 = a2 << 6;
  v15 = -67108864;
  if ( a1 >> 8 < v14 )
    goto LABEL_28;
  v14 <<= 6;
  v15 = -1048576;
  if ( a1 >> 8 < v14 )
    goto LABEL_28;
  v14 <<= 6;
  v15 = -16384;
  if ( a1 >> 8 >= v14 )
  {
    v14 <<= 6;
    v15 = -256;
  }
  v16 = v14 <= 0;
  if ( v14 <= 0 )
    return 0;
  do
  {
    if ( v16 )
      v14 >>= 6;
LABEL_28:
    v17 = a1 >> 7 >= v14;
    if ( a1 >> 7 >= v14 )
      a1 -= v14 << 7;
    v18 = v15 + v17 + v15;
    v19 = a1 >> 6 >= v14;
    if ( a1 >> 6 >= v14 )
      a1 -= v14 << 6;
    v20 = v18 + v19 + v18;
    v21 = a1 >> 5 >= v14;
    if ( a1 >> 5 >= v14 )
      a1 -= 32 * v14;
    v22 = v20 + v21 + v20;
    v23 = a1 >> 4 >= v14;
    if ( a1 >> 4 >= v14 )
      a1 -= 16 * v14;
    v24 = v22 + v23 + v22;
    v25 = a1 >> 3 >= v14;
    if ( a1 >> 3 >= v14 )
      a1 -= 8 * v14;
    v26 = v24 + v25 + v24;
    v27 = a1 >> 2 >= v14;
    if ( a1 >> 2 >= v14 )
      a1 -= 4 * v14;
    v28 = v27 + v26;
    v16 = __CFADD__(v27, v26) | __CFADD__(v26, v28);
    v15 = v26 + v28;
  }
  while ( v16 );
  v29 = a1 >> 1 >= v14;
  if ( a1 >> 1 >= v14 )
    a1 -= 2 * v14;
  return v15 + v29 + v15 + (a1 >= v14) + v15 + v29 + v15;
}

// ALL OK, 128 function(s) have been successfully decompiled
