/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall BSP_LCDInit(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, char a11, int a12);
_DWORD *__fastcall DE_BE_Disablel(int a1);
_DWORD *__fastcall DE_BE_Enablel(int a1);
_DWORD *__fastcall Debe_Init(int a1);
_DWORD *__fastcall Debe_TVAlphaSet(int a1);
_DWORD *Debe_tvdoff();
_DWORD *__fastcall Debe_tvdset(int a1, int a2, int a3, int a4);
_DWORD *Disable_Layer_Video();
_DWORD *Enable_Layer_Video();
int LCD_IO_Init();
int LCD_MCU_IO_Init();
int TCON_ISR();
_DWORD *__fastcall Tcon_Init(int a1);
_DWORD *__fastcall f1c100s_debe_set_address(int a1, unsigned int a2);
_DWORD *__fastcall f1c100s_set_address(unsigned int a1);
_DWORD *__fastcall f1c100s_tcon_disable(int a1);
int __fastcall f1c100s_tcon_enable(int a1);
int __fastcall read16(unsigned __int16 *a1);
int __fastcall read32(int a1);
__int64 __fastcall read64(int a1);
int __fastcall read8(unsigned __int8 *a1);
int __fastcall set_video_window(int a1, int a2, int a3, int a4);
_WORD *__fastcall write16(_WORD *result, int a2, __int16 a3);
_DWORD *__fastcall write32(_DWORD *result, int a2, int a3);
_QWORD *__fastcall write64(_QWORD *result, int a2, __int64 a3);
_BYTE *__fastcall write8(_BYTE *result, int a2, char a3);
// int __fastcall GPIO_Congif(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall ILI9341_028_Init(_DWORD); weak
// int IRQ_Init(void); weak
// int __fastcall delay_ms(_DWORD); weak
// int __fastcall sysprintf(_DWORD); weak
// int __fastcall vpost_set_windows(_DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_8; // weak
_UNKNOWN loc_18; // weak
_UNKNOWN loc_1C; // weak
_UNKNOWN loc_20; // weak
_UNKNOWN loc_2C; // weak
_UNKNOWN loc_30; // weak
_UNKNOWN loc_34; // weak
_UNKNOWN loc_38; // weak
_UNKNOWN loc_3C; // weak
_UNKNOWN loc_40; // weak
_UNKNOWN loc_44; // weak
_UNKNOWN loc_48; // weak
_UNKNOWN loc_4C; // weak
_UNKNOWN loc_50; // weak
_UNKNOWN loc_54; // weak
_UNKNOWN loc_58; // weak
_UNKNOWN loc_5C; // weak
_UNKNOWN loc_60; // weak
_UNKNOWN loc_64; // weak
_UNKNOWN loc_68; // weak
_UNKNOWN f1; // weak
_UNKNOWN unk_F38; // weak
_UNKNOWN unk_F3C; // weak
_UNKNOWN unk_F40; // weak
_UNKNOWN unk_F44; // weak
int (*lcd_pdat)(int, int, int, int, int, int, int, int) = &BSP_LCDInit; // weak


//----- (00000000) --------------------------------------------------------
int __fastcall BSP_LCDInit(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, char a11, int a12)
{
  int v12; // r5
  int v13; // r6
  int v14; // r7
  int v15; // r10
  _DWORD *v16; // r0
  signed int i; // r4

  v12 = a1;
  v13 = a2;
  v14 = a3;
  v15 = a4;
  lcd_pdat = (int (*)(int, int, int, int, int, int, int, int))&f1;
  unk_F3C = 0;
  unk_F38 = 31850496;
  unk_F44 = 0;
  unk_F40 = 29409280;
  v16 = f1c100s_tcon_disable((int)&f1);
  if ( v12 == 48 )
  {
    ILI9341_028_Init(v16);
    LCD_MCU_IO_Init();
    *(_DWORD *)((char *)&loc_18 + (_DWORD)lcd_pdat) = 0;
    sysprintf("tcon set to i80 mode\r\n");
  }
  else
  {
    LCD_IO_Init();
    *(_DWORD *)((char *)&loc_18 + (_DWORD)lcd_pdat) = 1;
  }
  *(_DWORD *)((char *)&loc_1C + (_DWORD)lcd_pdat) = v13;
  *(_DWORD *)((char *)&loc_20 + (_DWORD)lcd_pdat) = a6;
  *(_DWORD *)((char *)&loc_2C + (_DWORD)lcd_pdat) = 18;
  *(_DWORD *)((char *)&loc_40 + (_DWORD)lcd_pdat) = 1000 * a10;
  *(_DWORD *)((char *)&loc_44 + (_DWORD)lcd_pdat) = a5;
  *(_DWORD *)((char *)&loc_48 + (_DWORD)lcd_pdat) = v15;
  *(_DWORD *)((char *)&loc_4C + (_DWORD)lcd_pdat) = v14;
  *(_DWORD *)((char *)&loc_50 + (_DWORD)lcd_pdat) = a9;
  *(_DWORD *)((char *)&loc_54 + (_DWORD)lcd_pdat) = a8;
  *(_DWORD *)((char *)&loc_58 + (_DWORD)lcd_pdat) = a7;
  *(_DWORD *)((char *)&loc_5C + (_DWORD)lcd_pdat) = 0;
  *(_DWORD *)((char *)&loc_60 + (_DWORD)lcd_pdat) = 0;
  *(_DWORD *)((char *)&loc_64 + (_DWORD)lcd_pdat) = 1;
  *(_DWORD *)((char *)&loc_68 + (_DWORD)lcd_pdat) = a11 & 1;
  *(_DWORD *)((char *)&loc_34 + (_DWORD)lcd_pdat) = 0;
  *(_DWORD *)((char *)&loc_30 + (_DWORD)lcd_pdat) = 4;
  *(_DWORD *)((char *)&loc_38 + (_DWORD)lcd_pdat) = a12;
  *(_DWORD *)((char *)&loc_3C + (_DWORD)lcd_pdat) = a12;
  for ( i = 2048; i < 4096; i += 4 )
    write32((_DWORD *)(i + 31850496), (i + 31850496) >> 31, 0);
  Debe_Init((int)lcd_pdat);
  Tcon_Init((int)lcd_pdat);
  return f1c100s_tcon_enable((int)lcd_pdat);
}
// FA0: using guessed type int (*lcd_pdat)(int, int, int, int, int, int, int, int);
// FAC: using guessed type int __fastcall ILI9341_028_Init(_DWORD);
// FBC: using guessed type int __fastcall sysprintf(_DWORD);

//----- (00000228) --------------------------------------------------------
_DWORD *__fastcall DE_BE_Disablel(int a1)
{
  int v1; // r4
  int v2; // r0
  int v3; // r0

  v1 = *(_DWORD *)(a1 + 8);
  v2 = read32(v1 + 2048);
  write32((_DWORD *)(v1 + 2048), 0, v2 & 0xFFFFFFFD);
  v3 = read32(v1 + 2048);
  return write32((_DWORD *)(v1 + 2048), 0, v3 & 0xFFFFFFFE);
}

//----- (00000278) --------------------------------------------------------
_DWORD *__fastcall DE_BE_Enablel(int a1)
{
  int v1; // r4
  int v2; // r0
  int v3; // r0

  v1 = *(_DWORD *)(a1 + 8);
  v2 = read32(v1 + 2048);
  write32((_DWORD *)(v1 + 2048), 0, v2 | 2);
  v3 = read32(v1 + 2048);
  return write32((_DWORD *)(v1 + 2048), 0, v3 | 1);
}

//----- (000002C8) --------------------------------------------------------
_DWORD *__fastcall Debe_Init(int a1)
{
  int v1; // r5
  _DWORD *v2; // r4
  int v3; // r0
  int v4; // r0
  int v5; // r0
  int v6; // r0
  int v7; // r0
  int v8; // r0
  int v9; // r0
  int v10; // r0
  int v11; // r0
  int v12; // r0
  int v13; // r0

  v1 = a1;
  v2 = *(_DWORD **)(a1 + 8);
  v3 = read32(29491300);
  write32((_DWORD *)0x1C20064, 0, v3 | 0x1000);
  v4 = read32(29491908);
  write32((_DWORD *)0x1C202C4, 0, v4 | 0x1000);
  delay_ms(1);
  v5 = read32((int)(v2 + 512));
  write32(v2 + 512, 0, v5 | 1);
  write32(v2 + 514, 0, (*(_DWORD *)(v1 + 28) - 1) | ((*(unsigned __int16 *)(v1 + 32) - 1) << 16));
  write32(v2 + 516, 0, (*(_DWORD *)(v1 + 28) - 1) | ((*(unsigned __int16 *)(v1 + 32) - 1) << 16));
  write32(v2 + 528, 0, 32 * *(_DWORD *)(v1 + 28));
  write32(v2 + 532, 0, 8 * *(_DWORD *)(v1 + 56));
  write32(v2 + 536, 0, *(_DWORD *)(v1 + 56) >> 29);
  write32(v2 + 552, 0, 2560);
  v6 = read32((int)(v2 + 548));
  write32(v2 + 548, 0, v6 | 2);
  write32(v2 + 514, 0, (*(_DWORD *)(v1 + 28) - 1) | ((*(unsigned __int16 *)(v1 + 32) - 1) << 16));
  write32(v2 + 517, 0, (*(_DWORD *)(v1 + 28) - 1) | ((*(unsigned __int16 *)(v1 + 32) - 1) << 16));
  write32(v2 + 529, 0, 16 * *(_DWORD *)(v1 + 28));
  write32(v2 + 533, 0, 8 * *(_DWORD *)(v1 + 60));
  write32(v2 + 537, 0, *(_DWORD *)(v1 + 60) >> 29);
  write32(v2 + 553, 0, 1280);
  v7 = read32((int)(v2 + 548));
  write32(v2 + 548, 0, v7 | 0x400);
  v8 = read32((int)(v2 + 549));
  write32(v2 + 549, 0, v8 | 0x8000);
  v9 = read32((int)(v2 + 512));
  write32(v2 + 512, 0, v9 | 0x200);
  v10 = read32((int)(v2 + 512));
  write32(v2 + 512, 0, v10 & 0xFFFFFEFF);
  v11 = read32((int)(v2 + 549));
  write32(v2 + 549, 0, v11 & 0xFFFFFFFE);
  v12 = read32((int)(v2 + 540));
  write32(v2 + 540, 0, v12 | 1);
  v13 = read32((int)(v2 + 512));
  return write32(v2 + 512, 0, v13 | 2);
}
// FB8: using guessed type int __fastcall delay_ms(_DWORD);

//----- (00000598) --------------------------------------------------------
_DWORD *__fastcall Debe_TVAlphaSet(int a1)
{
  int v1; // r5
  int v2; // r0

  v1 = a1;
  v2 = read32(31852688);
  return write32((_DWORD *)0x1E60890, 0, v2 & 0xFFFFFF | (v1 << 24) | 1);
}

//----- (000005D8) --------------------------------------------------------
_DWORD *Debe_tvdoff()
{
  int v0; // r0
  int v1; // r0
  int v2; // r0

  v0 = read32(31852544);
  write32((_DWORD *)0x1E60800, 0, v0 & 0xFFFFFEFF);
  v1 = read32(31852692);
  write32((_DWORD *)0x1E60894, 0, v1 & 0xFFFFFFFE);
  v2 = read32(31852688);
  return write32((_DWORD *)0x1E60890, 0, v2 & 0xFFFFFFFD);
}

//----- (00000650) --------------------------------------------------------
_DWORD *__fastcall Debe_tvdset(int a1, int a2, int a3, int a4)
{
  int v4; // r7
  int v5; // r8
  int v6; // r0
  int v7; // r0

  v4 = a3;
  v5 = a4;
  write32((_DWORD *)0x1E60810, 0, (a1 - 1) | ((a2 - 1) << 16));
  write32((_DWORD *)0x1E60820, 0, v4 | (v5 << 16));
  v6 = read32(0x1E60800);
  write32((_DWORD *)0x1E60800, 0, v6 | 0x100);
  v7 = read32(0x1E60890);
  return write32((_DWORD *)0x1E60890, 0, v7 | 2);
}

//----- (000006D8) --------------------------------------------------------
_DWORD *Disable_Layer_Video()
{
  int v0; // r0
  int v1; // r0

  v0 = read32(31852688);
  write32((_DWORD *)0x1E60890, 0, v0 & 0xFFFFFFFD);
  v1 = read32(31852544);
  return write32((_DWORD *)0x1E60800, 0, v1 & 0xFFFFFEFF);
}

//----- (00000728) --------------------------------------------------------
_DWORD *Enable_Layer_Video()
{
  int v0; // r0
  int v1; // r0

  v0 = read32(31852688);
  write32((_DWORD *)0x1E60890, 0, v0 | 2);
  v1 = read32(31852544);
  return write32((_DWORD *)0x1E60800, 0, v1 | 0x100);
}

//----- (00000778) --------------------------------------------------------
int LCD_IO_Init()
{
  signed int i; // r4
  int result; // r0

  for ( i = 0; i <= 21; ++i )
    result = GPIO_Congif(29493356, i, 2, 0);
  return result;
}
// FA8: using guessed type int __fastcall GPIO_Congif(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (000007B0) --------------------------------------------------------
int LCD_MCU_IO_Init()
{
  signed int i; // r4
  signed int j; // r4

  for ( i = 1; i < 9; ++i )
    GPIO_Congif(29493356, i, 2, 0);
  for ( j = 10; j < 18; ++j )
    GPIO_Congif(29493356, j, 2, 0);
  GPIO_Congif(29493356, 18, 2, 0);
  GPIO_Congif(29493356, 20, 2, 0);
  GPIO_Congif(29493356, 21, 2, 0);
  return GPIO_Congif(29493356, 19, 2, 0);
}
// FA8: using guessed type int __fastcall GPIO_Congif(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00000860) --------------------------------------------------------
int TCON_ISR()
{
  int v0; // r0
  _DWORD *v1; // r0

  v0 = read32(29409284);
  v1 = write32((_DWORD *)0x1C0C004, 0, v0 & 0xFFFF7FFF);
  vpost_set_windows(v1);
  return LCD_MCU_IO_Init();
}
// FC0: using guessed type int __fastcall vpost_set_windows(_DWORD);

//----- (00000894) --------------------------------------------------------
_DWORD *__fastcall Tcon_Init(int a1)
{
  int v1; // r5
  _DWORD *v2; // r4
  int v3; // r0
  int v4; // r0
  int v5; // r0
  int v6; // r0
  int v7; // r0
  int v8; // r0
  int v9; // r6
  int v10; // r0
  unsigned int v11; // r6
  int v12; // r7
  int v13; // r7
  int v14; // r0
  int v15; // r0
  int v16; // r0
  int v17; // r0
  int v18; // r6

  v1 = a1;
  v2 = *(_DWORD **)(a1 + 16);
  v3 = read32(29491216);
  write32((_DWORD *)0x1C20010, 0, v3 & 0x7FFFFFFF);
  write32((_DWORD *)0x1C20010, 0, 50348803);
  v4 = read32(29491216);
  write32((_DWORD *)0x1C20010, 0, v4 | 0x80000000);
  delay_ms(1);
  v5 = read32(29491300);
  write32((_DWORD *)0x1C20064, 0, v5 | 0x10);
  v6 = read32(29491480);
  write32((_DWORD *)0x1C20118, 0, v6 | 0x80000000);
  v7 = read32(29491908);
  write32((_DWORD *)0x1C202C4, 0, v7 | 0x10);
  delay_ms(1);
  v8 = read32((int)v2);
  write32(v2, 0, v8 & 0xFFFFFFFE);
  v9 = *(_DWORD *)(v1 + 80) + *(_DWORD *)(v1 + 84) + *(_DWORD *)(v1 + 88);
  v10 = read32((int)(v2 + 16));
  write32(v2 + 16, 0, v10 | 0x80000000 | 16 * (v9 & 0x1F));
  v11 = 0x18519600u / *(_DWORD *)(v1 + 64);
  if ( v11 < 6 )
    v11 = 6;
  write32(v2 + 17, 0, v11 | 0xF0000000);
  write32(v2 + 18, 0, (*(_DWORD *)(v1 + 32) - 1) | ((*(unsigned __int16 *)(v1 + 28) - 1) << 16));
  v12 = *(_DWORD *)(v1 + 76) + *(_DWORD *)(v1 + 72);
  write32(v2 + 19, 0, (v12 - 1) | ((*(_DWORD *)(v1 + 28) + *(_DWORD *)(v1 + 68) + v12 - 1) << 16));
  v13 = *(_DWORD *)(v1 + 88) + *(_DWORD *)(v1 + 84);
  write32(v2 + 20, 0, (v13 - 1) | ((*(_DWORD *)(v1 + 32) + *(_DWORD *)(v1 + 80) + v13) << 17));
  write32(v2 + 21, 0, (*(_DWORD *)(v1 + 88) - 1) | ((*(unsigned __int16 *)(v1 + 76) - 1) << 16));
  if ( *(_DWORD *)(v1 + 24) == 1 )
  {
    write32(v2 + 22, 0, 0);
    write32(v2 + 24, 0, 0);
  }
  else
  {
    v14 = read32((int)(v2 + 16));
    write32(v2 + 16, 0, v14 | 0x1000000);
    write32(v2 + 22, 0, 0);
    write32(v2 + 24, 0, 2147483648);
  }
  if ( *(_DWORD *)(v1 + 44) == 18 || *(_DWORD *)(v1 + 44) == 16 )
  {
    write32(v2 + 5, 0, 286331153);
    write32(v2 + 6, 0, 286331153);
    write32(v2 + 7, 0, 286331153);
    write32(v2 + 8, 0, 286331153);
    write32(v2 + 9, 0, 286331153);
    write32(v2 + 10, 0, 286331153);
    write32(v2 + 11, 0, 16842752);
    write32(v2 + 12, 0, 353702161);
    write32(v2 + 13, 0, 1465341269);
    write32(v2 + 14, 0, 2139060087);
    if ( *(_DWORD *)(v1 + 44) == 18 )
      v15 = 2147483648;
    else
      v15 = -2147483568;
    write32(v2 + 4, 0, v15);
  }
  if ( *(_DWORD *)(v1 + 24) )
  {
    v16 = read32((int)(v2 + 16));
    write32(v2 + 16, 0, v16 | 0x800000);
  }
  else
  {
    v17 = read32((int)(v2 + 16));
    write32(v2 + 16, 0, v17 & 0xFF7FFFFF);
  }
  v18 = 0x10000000;
  if ( !*(_DWORD *)(v1 + 92) )
    v18 = 301989888;
  if ( !*(_DWORD *)(v1 + 96) )
    v18 |= 0x1000000u;
  if ( !*(_DWORD *)(v1 + 100) )
    v18 |= 0x8000000u;
  if ( !*(_DWORD *)(v1 + 104) )
    v18 |= 0x4000000u;
  if ( *(_DWORD *)(v1 + 24) )
    write32(v2 + 34, 0, v18);
  else
    write32(v2 + 34, 0, 402653184);
  return write32(v2 + 35, 0, 0);
}
// FB8: using guessed type int __fastcall delay_ms(_DWORD);

//----- (00000D04) --------------------------------------------------------
_DWORD *__fastcall f1c100s_debe_set_address(int a1, unsigned int a2)
{
  unsigned int v2; // r4
  int v3; // r6

  v2 = a2;
  v3 = *(_DWORD *)(a1 + 8);
  write32((_DWORD *)(v3 + 2128), 0, 8 * a2);
  return write32((_DWORD *)(v3 + 2144), 0, v2 >> 29);
}

//----- (00000D38) --------------------------------------------------------
_DWORD *__fastcall f1c100s_set_address(unsigned int a1)
{
  unsigned int v1; // r4
  int v2; // r5

  v1 = a1;
  v2 = *(_DWORD *)((char *)&loc_8 + (_DWORD)lcd_pdat);
  write32((_DWORD *)(v2 + 2132), 0, 8 * a1);
  return write32((_DWORD *)(v2 + 2148), 0, v1 >> 29);
}
// FA0: using guessed type int (*lcd_pdat)(int, int, int, int, int, int, int, int);

//----- (00000D7C) --------------------------------------------------------
_DWORD *__fastcall f1c100s_tcon_disable(int a1)
{
  _DWORD *v1; // r4
  int v2; // r0

  v1 = *(_DWORD **)(a1 + 16);
  write32(*(_DWORD **)(a1 + 16), 0, 0);
  write32(v1 + 1, 0, 0);
  v2 = read32((int)(v1 + 17));
  write32(v1 + 17, 0, v2 & 0xFFFFFFF);
  write32(v1 + 35, 0, -1);
  return write32(v1 + 61, 0, -1);
}

//----- (00000DF0) --------------------------------------------------------
int __fastcall f1c100s_tcon_enable(int a1)
{
  int v1; // r5
  _DWORD *v2; // r4
  int v3; // r0
  int result; // r0
  int v5; // r0

  v1 = a1;
  v2 = *(_DWORD **)(a1 + 16);
  v3 = read32(*(_DWORD *)(a1 + 16));
  write32(v2, 0, v3 | 0x80000000);
  result = *(_DWORD *)(v1 + 24);
  if ( !result )
  {
    v5 = read32((int)(v2 + 24));
    write32(v2 + 24, 0, v5 | 0x10000000);
    write32(v2 + 1, 0, 2147483648);
    result = IRQ_Init();
  }
  return result;
}
// FB0: using guessed type int IRQ_Init(void);

//----- (00000E80) --------------------------------------------------------
int __fastcall read16(unsigned __int16 *a1)
{
  return *a1;
}

//----- (00000E90) --------------------------------------------------------
int __fastcall read32(int a1)
{
  return *(_DWORD *)a1;
}

//----- (00000EA0) --------------------------------------------------------
__int64 __fastcall read64(int a1)
{
  return *(_QWORD *)a1;
}

//----- (00000EB0) --------------------------------------------------------
int __fastcall read8(unsigned __int8 *a1)
{
  return *a1;
}

//----- (00000EC0) --------------------------------------------------------
int __fastcall set_video_window(int a1, int a2, int a3, int a4)
{
  int v4; // r6
  int v5; // r7

  v4 = a3;
  v5 = a4;
  write32((_DWORD *)0x1E60820, 0, a1 | (a2 << 16));
  write32((_DWORD *)0x1E60810, 0, (v4 - 1) | ((v5 - 1) << 16));
  return 0;
}

//----- (00000F0C) --------------------------------------------------------
_WORD *__fastcall write16(_WORD *result, int a2, __int16 a3)
{
  *result = a3;
  return result;
}

//----- (00000F14) --------------------------------------------------------
_DWORD *__fastcall write32(_DWORD *result, int a2, int a3)
{
  *result = a3;
  return result;
}

//----- (00000F1C) --------------------------------------------------------
_QWORD *__fastcall write64(_QWORD *result, int a2, __int64 a3)
{
  *result = a3;
  return result;
}

//----- (00000F24) --------------------------------------------------------
_BYTE *__fastcall write8(_BYTE *result, int a2, char a3)
{
  *result = a3;
  return result;
}

// ALL OK, 26 function(s) have been successfully decompiled
