/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

unsigned __int64 __fastcall map_l1_section(int a1, int a2, unsigned __int64 a3, unsigned __int64 a4, unsigned __int64 a5, char a6);
int __fastcall read16(unsigned __int16 *a1);
int __fastcall read32(int a1);
__int64 __fastcall read64(int a1);
int __fastcall read8(unsigned __int8 *a1);
int sys_mmu_init();
_WORD *__fastcall write16(_WORD *result, int a2, __int16 a3);
_DWORD *__fastcall write32(_DWORD *result, int a2, int a3);
_QWORD *__fastcall write64(_QWORD *result, int a2, __int64 a3);
_BYTE *__fastcall write8(_BYTE *result, int a2, char a3);
// int __fastcall arm32_dcache_enable(_DWORD); weak
// int __fastcall arm32_domain_set(_DWORD); weak
// int __fastcall arm32_icache_enable(_DWORD); weak
// int __fastcall arm32_mmu_enable(_DWORD); weak
// int __fastcall arm32_tlb_invalidate(_DWORD); weak
// int __fastcall arm32_ttb_set(_DWORD, _DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN mmuTable; // weak


//----- (00000000) --------------------------------------------------------
unsigned __int64 __fastcall map_l1_section(int a1, int a2, unsigned __int64 a3, unsigned __int64 a4, unsigned __int64 a5, char a6)
{
  int v6; // r8
  unsigned __int64 v7; // r2
  unsigned __int64 v8; // r4
  unsigned __int64 result; // r0

  v6 = a1;
  v7 = a3 >> 20;
  v8 = a4 >> 20;
  result = a5 >> 20;
  while ( result )
  {
    *(_DWORD *)(v6 + 4 * v7) = ((_DWORD)v8 << 20) | 0xC10 | 4 * (a6 & 3) | 2;
    --result;
    ++v7;
    ++v8;
  }
  return result;
}

//----- (0000008C) --------------------------------------------------------
int __fastcall read16(unsigned __int16 *a1)
{
  return *a1;
}

//----- (0000009C) --------------------------------------------------------
int __fastcall read32(int a1)
{
  return *(_DWORD *)a1;
}

//----- (000000AC) --------------------------------------------------------
__int64 __fastcall read64(int a1)
{
  return *(_QWORD *)a1;
}

//----- (000000BC) --------------------------------------------------------
int __fastcall read8(unsigned __int8 *a1)
{
  return *a1;
}

//----- (000000CC) --------------------------------------------------------
int sys_mmu_init()
{
  unsigned __int64 v0; // r0
  int v1; // r0
  int v2; // r0
  int v3; // r0
  int v4; // r0

  map_l1_section((int)&mmuTable, 2147483648, 0LL, 0LL, 0x80000000uLL, 0);
  map_l1_section((int)&mmuTable, 0, 0x80000000uLL, 0x80000000uLL, 0x80000000uLL, 0);
  v0 = map_l1_section((int)&mmuTable, 2147483648, 0x80000000uLL, 0x80000000uLL, 0x2000000uLL, 2);
  v1 = arm32_ttb_set(&mmuTable, HIDWORD(v0));
  arm32_tlb_invalidate(v1);
  v2 = arm32_domain_set(1);
  v3 = arm32_mmu_enable(v2);
  v4 = arm32_icache_enable(v3);
  return arm32_dcache_enable(v4);
}
// 41B4: using guessed type int __fastcall arm32_dcache_enable(_DWORD);
// 41B8: using guessed type int __fastcall arm32_domain_set(_DWORD);
// 41BC: using guessed type int __fastcall arm32_icache_enable(_DWORD);
// 41C0: using guessed type int __fastcall arm32_mmu_enable(_DWORD);
// 41C4: using guessed type int __fastcall arm32_tlb_invalidate(_DWORD);
// 41C8: using guessed type int __fastcall arm32_ttb_set(_DWORD, _DWORD);

//----- (00000194) --------------------------------------------------------
_WORD *__fastcall write16(_WORD *result, int a2, __int16 a3)
{
  *result = a3;
  return result;
}

//----- (0000019C) --------------------------------------------------------
_DWORD *__fastcall write32(_DWORD *result, int a2, int a3)
{
  *result = a3;
  return result;
}

//----- (000001A4) --------------------------------------------------------
_QWORD *__fastcall write64(_QWORD *result, int a2, __int64 a3)
{
  *result = a3;
  return result;
}

//----- (000001AC) --------------------------------------------------------
_BYTE *__fastcall write8(_BYTE *result, int a2, char a3)
{
  *result = a3;
  return result;
}

// ALL OK, 10 function(s) have been successfully decompiled
