/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int TCON1_Init();
int TCON_mux_init();
int __fastcall TCON_set_tv_src(int a1, int a2);
_DWORD *TVE_Clock_Close();
int TVE_Clock_Open();
int TVE_Config();
int TVE_Init();
int __fastcall mdelay(int a1);
int __fastcall read16(unsigned __int16 *a1);
int __fastcall read32(int a1);
__int64 __fastcall read64(int a1);
int __fastcall read8(unsigned __int8 *a1);
int tcon1_yuv_range();
int __fastcall tve_low_close(int a1);
int __fastcall tve_low_dac_auto_cali(int a1, _DWORD *a2);
int __fastcall tve_low_dac_autocheck_disable(int a1);
int __fastcall tve_low_dac_autocheck_enable(int a1);
int __fastcall tve_low_dac_disable(int a1);
int __fastcall tve_low_dac_enable(int a1);
int __fastcall tve_low_enhance(int a1, int a2);
int tve_low_exit();
int __fastcall tve_low_get_dac_status(int a1);
int __fastcall tve_low_init(int a1, int a2, signed int *a3, _DWORD *a4);
int __fastcall tve_low_open(int a1);
int __fastcall tve_low_set_reg_base(int a1, int a2);
int __fastcall tve_low_set_tv_mode(int a1, int a2, int a3);
_WORD *__fastcall write16(_WORD *result, int a2, __int16 a3);
_DWORD *__fastcall write32(_DWORD *result, int a2, int a3);
_QWORD *__fastcall write64(_QWORD *result, int a2, __int64 a3);
_BYTE *__fastcall write8(_BYTE *result, int a2, char a3);
// int __fastcall delay_ms(_DWORD); weak
// int __fastcall sysprintf(_DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_4; // weak
_UNKNOWN loc_8; // weak
_UNKNOWN loc_C; // weak
_UNKNOWN loc_10; // weak
_UNKNOWN loc_14; // weak
_UNKNOWN loc_18; // weak
_UNKNOWN loc_1C; // weak
_UNKNOWN loc_20; // weak
_UNKNOWN loc_30; // weak
_UNKNOWN loc_38; // weak
_UNKNOWN loc_3C; // weak
_UNKNOWN loc_F8; // weak
_UNKNOWN loc_FC; // weak
_UNKNOWN loc_100; // weak
_UNKNOWN loc_104; // weak
_UNKNOWN loc_108; // weak
_UNKNOWN loc_10C; // weak
_UNKNOWN loc_110; // weak
_UNKNOWN loc_114; // weak
_UNKNOWN loc_118; // weak
_UNKNOWN loc_11C; // weak
_UNKNOWN loc_120; // weak
_UNKNOWN loc_124; // weak
_UNKNOWN loc_128; // weak
_UNKNOWN loc_12C; // weak
_UNKNOWN loc_130; // weak
_UNKNOWN loc_134; // weak
_UNKNOWN loc_138; // weak
_UNKNOWN loc_13C; // weak
_UNKNOWN loc_300; // weak
_UNKNOWN loc_304; // weak
_UNKNOWN loc_308; // weak
_UNKNOWN loc_30C; // weak
_UNKNOWN loc_3A0; // weak
int tve_reg_base = 0; // weak
int (*sid_reg_base)() = &TCON1_Init; // weak


//----- (00000000) --------------------------------------------------------
int TCON1_Init()
{
  int v0; // r0
  int v1; // r0
  int v2; // r0
  signed int i; // r4
  int v4; // r0

  v0 = read32(0x1C0C090);
  write32((_DWORD *)0x1C0C090, 0, v0 | 0x80000000);
  v1 = read32(0x1C0C090);
  write32((_DWORD *)0x1C0C090, 0, v1);
  v2 = read32(0x1C0C090);
  write32((_DWORD *)0x1C0C090, 0, v2 | 0x140);
  for ( i = 0; i < 144; i += 4 )
    write32((_DWORD *)(i + 29409280), 0, 0);
  v4 = read32(0x1C0C090);
  write32((_DWORD *)0x1C0C090, 0, v4 | 0x100000);
  write32((_DWORD *)0x1C0C094, 0, 47120671);
  write32((_DWORD *)0x1C0C098, 0, 47120671);
  write32((_DWORD *)0x1C0C09C, 0, 47120671);
  write32((_DWORD *)0x1C0C0A0, 0, 56557706);
  write32((_DWORD *)0x1C0C0A4, 0, 40960021);
  write32((_DWORD *)0x1C0C0A8, 0, 65537);
  write32((_DWORD *)0x1C0C0F0, 0, 0);
  write32((_DWORD *)0x1C0C0F4, 0, 0xFFFFFFF);
  return 0;
}

//----- (00000248) --------------------------------------------------------
int TCON_mux_init()
{
  int v0; // r0
  int v1; // r0
  int v2; // r0

  v0 = read32(0x1C0C200);
  write32((_DWORD *)0x1C0C200, 0, v0 & 0x7FFFFFFF);
  v1 = read32(0x1C0C200);
  write32((_DWORD *)0x1C0C200, 0, v1 & 0xFFFFFF0F);
  v2 = read32(0x1C0C200);
  write32((_DWORD *)0x1C0C200, 0, v2 & 0xFFFFFF0F | 1);
  return 0;
}

//----- (000002BC) --------------------------------------------------------
int __fastcall TCON_set_tv_src(int a1, int a2)
{
  int v2; // r4
  int v3; // r0
  unsigned int v4; // r0

  v2 = a2;
  if ( a1 )
  {
    v4 = read32(0x1C0C200) & 0xFFFFFFFC;
    write32((_DWORD *)0x1C0C200, 0, v4 | v2);
  }
  else
  {
    v3 = read32(0x1C0C200);
    write32((_DWORD *)0x1C0C200, 0, v3 & 0xFFFFFFCF | 16 * v2);
  }
  return 0;
}

//----- (00000328) --------------------------------------------------------
_DWORD *TVE_Clock_Close()
{
  int v0; // r0

  write32((_DWORD *)0x1C20120, 0, 0);
  v0 = read32(29491300);
  return write32((_DWORD *)0x1C20064, 0, v0 & 0xFFFFFBFF);
}

//----- (00000368) --------------------------------------------------------
int TVE_Clock_Open()
{
  int v0; // r0
  int v1; // r0
  int v2; // r0
  int v3; // r0
  int v4; // r0

  v0 = read32(29491216);
  write32((_DWORD *)0x1C20010, 0, v0 & 0x7FFFFFFF);
  write32((_DWORD *)0x1C20010, 0, 25088);
  v1 = read32(29491216);
  write32((_DWORD *)0x1C20010, 0, v1 | 0x80000000);
  delay_ms(1);
  v2 = read32(29491300);
  write32((_DWORD *)0x1C20064, 0, v2 | 0x400);
  v3 = read32(29491488);
  write32((_DWORD *)0x1C20120, 0, v3 | 0x80008109);
  v4 = read32(29491908);
  write32((_DWORD *)0x1C202C4, 0, v4 | 0x400);
  return delay_ms(1);
}
// 1A20: using guessed type int __fastcall delay_ms(_DWORD);

//----- (00000444) --------------------------------------------------------
int TVE_Config()
{
  int v1; // [sp+8h] [bp-10h]
  int v2; // [sp+Ch] [bp-Ch]

  v2 = 0xFFFF;
  v1 = 0xFFFF;
  TVE_Clock_Open();
  tve_low_set_reg_base(0, 0x1C0A000);
  tve_low_init(0, (int)&v2, &v2, &v1);
  TVE_Clock_Close();
  TVE_Clock_Open();
  tve_low_set_tv_mode(0, 1, (int)&v2);
  tve_low_dac_autocheck_enable(0);
  tve_low_enhance(0, 0);
  tve_low_dac_enable(0);
  tve_low_open(0);
  return 0;
}

//----- (000004D0) --------------------------------------------------------
int TVE_Init()
{
  sysprintf("TVE_Init\r\n");
  TCON1_Init();
  TVE_Config();
  return sysprintf("TVE_end\r\n");
}
// 1A24: using guessed type int __fastcall sysprintf(_DWORD);

//----- (00000508) --------------------------------------------------------
int __fastcall mdelay(int a1)
{
  return delay_ms(10 * a1);
}
// 1A20: using guessed type int __fastcall delay_ms(_DWORD);

//----- (00000520) --------------------------------------------------------
int __fastcall read16(unsigned __int16 *a1)
{
  return *a1;
}

//----- (00000530) --------------------------------------------------------
int __fastcall read32(int a1)
{
  return *(_DWORD *)a1;
}

//----- (00000540) --------------------------------------------------------
__int64 __fastcall read64(int a1)
{
  return *(_QWORD *)a1;
}

//----- (00000550) --------------------------------------------------------
int __fastcall read8(unsigned __int8 *a1)
{
  return *a1;
}

//----- (00000560) --------------------------------------------------------
int tcon1_yuv_range()
{
  write32((_DWORD *)0x1C0C110, 0, 256);
  write32((_DWORD *)0x1C0C114, 0, 0);
  write32((_DWORD *)0x1C0C118, 0, 0);
  write32((_DWORD *)0x1C0C11C, 0, 0);
  write32((_DWORD *)0x1C0C120, 0, 0);
  write32((_DWORD *)0x1C0C124, 0, 256);
  write32((_DWORD *)0x1C0C128, 0, 0);
  write32((_DWORD *)0x1C0C12C, 0, 0);
  write32((_DWORD *)0x1C0C130, 0, 0);
  write32((_DWORD *)0x1C0C134, 0, 0);
  write32((_DWORD *)0x1C0C138, 0, 256);
  write32((_DWORD *)0x1C0C13C, 0, 0);
  write32((_DWORD *)0x1C0C140, 0, 1048816);
  write32((_DWORD *)0x1C0C144, 0, 1048811);
  write32((_DWORD *)0x1C0C148, 0, 1048811);
  write32((_DWORD *)0x1C0C100, 0, 2147483648);
  return 0;
}

//----- (000006BC) --------------------------------------------------------
int __fastcall tve_low_close(int a1)
{
  int v1; // r1
  int (*v2)(); // r0
  unsigned int v3; // r2
  int (*v4)(); // r0
  int (*v5)(); // r0
  unsigned int v6; // r2
  int (*v7)(); // r0

  v1 = a1;
  if ( a1 )
    v2 = sid_reg_base;
  else
    v2 = (int (*)())tve_reg_base;
  v3 = *(_DWORD *)v2 & 0xFFFFFFFE;
  if ( v1 )
    v4 = sid_reg_base;
  else
    v4 = (int (*)())tve_reg_base;
  *(_DWORD *)v4 = v3;
  if ( v1 )
    v5 = sid_reg_base;
  else
    v5 = (int (*)())tve_reg_base;
  v6 = *(_DWORD *)v5 | 0x80000000;
  if ( v1 )
    v7 = sid_reg_base;
  else
    v7 = (int (*)())tve_reg_base;
  *(_DWORD *)v7 = v6;
  return 0;
}
// 1A18: using guessed type int tve_reg_base;
// 1A1C: using guessed type int (*sid_reg_base)();

//----- (00000754) --------------------------------------------------------
int __fastcall tve_low_dac_auto_cali(int a1, _DWORD *a2)
{
  int v2; // r4
  _WORD *v3; // r6
  int (*v4)(); // r0
  int (*v5)(); // r0
  int (*v6)(); // r0
  int (*v7)(); // r0
  int (*v8)(); // r0
  int v9; // r1
  int (*v10)(); // r0
  unsigned int i; // r5
  int (*v12)(); // r0
  int v13; // r1
  int (*v14)(); // r0
  int (*v15)(); // r0
  int v16; // r1
  int (*v17)(); // r0
  int (*v18)(); // r0
  int (*v19)(); // r0
  unsigned int v20; // r1
  int (*v21)(); // r0
  int (*v22)(); // r0
  unsigned int v23; // r1
  int (*v24)(); // r0
  int v25; // r1
  int v26; // r1
  int v27; // r1
  int v28; // r7
  int v29; // r8
  int v30; // r1
  int v31; // r9
  int v32; // r10
  int (*v33)(); // r0
  int (*v34)(); // r0
  unsigned int v35; // r1
  int (*v36)(); // r0
  int (*v37)(); // r0
  unsigned int v39; // [sp+0h] [bp-C0h]
  unsigned int v40; // [sp+4h] [bp-BCh]
  unsigned int v41; // [sp+8h] [bp-B8h]
  int v42; // [sp+28h] [bp-98h]
  int v43; // [sp+2Ch] [bp-94h]
  int v44; // [sp+50h] [bp-70h]
  int v45; // [sp+54h] [bp-6Ch]
  int v46; // [sp+58h] [bp-68h]
  _DWORD v47[1]; // [sp+78h] [bp-48h]

  v2 = a1;
  v3 = a2;
  if ( a1 )
    v4 = sid_reg_base;
  else
    v4 = (int (*)())tve_reg_base;
  *(_DWORD *)v4 = -2147482880;
  if ( v2 )
    v5 = sid_reg_base;
  else
    v5 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_30 + (_DWORD)v5) = 0;
  if ( v2 )
    v6 = sid_reg_base;
  else
    v6 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_8 + (_DWORD)v6) = 1128141489;
  if ( v2 )
    v7 = sid_reg_base;
  else
    v7 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_304 + (_DWORD)v7) = (*a2 << 16) | 0xC00;
  if ( v2 )
    v8 = sid_reg_base;
  else
    v8 = (int (*)())tve_reg_base;
  v9 = *(_DWORD *)((char *)&loc_300 + (_DWORD)v8) | 1;
  if ( v2 )
    v10 = sid_reg_base;
  else
    v10 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_300 + (_DWORD)v10) = v9;
  for ( i = 0; i < 3; ++i )
  {
    if ( v2 )
      v12 = sid_reg_base;
    else
      v12 = (int (*)())tve_reg_base;
    v13 = *(_DWORD *)((char *)&loc_304 + (_DWORD)v12) | 0x10;
    if ( v2 )
      v14 = sid_reg_base;
    else
      v14 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_304 + (_DWORD)v14) = v13;
    mdelay(1);
    if ( v2 )
      v15 = sid_reg_base;
    else
      v15 = (int (*)())tve_reg_base;
    v16 = *(_DWORD *)((char *)&loc_304 + (_DWORD)v15) | 1;
    if ( v2 )
      v17 = sid_reg_base;
    else
      v17 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_304 + (_DWORD)v17) = v16;
    mdelay(1);
    if ( v2 )
      v18 = sid_reg_base;
    else
      v18 = (int (*)())tve_reg_base;
    v47[i] = (*(_DWORD *)((char *)&loc_308 + (_DWORD)v18) >> 16) & 0x3FF;
    if ( v2 )
      v19 = sid_reg_base;
    else
      v19 = (int (*)())tve_reg_base;
    v20 = *(_DWORD *)((_BYTE *)&loc_304 + (_DWORD)v19) & 0xFFFFFFFE;
    if ( v2 )
      v21 = sid_reg_base;
    else
      v21 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_304 + (_DWORD)v21) = v20;
    if ( v2 )
      v22 = sid_reg_base;
    else
      v22 = (int (*)())tve_reg_base;
    v23 = *(_DWORD *)((_BYTE *)&loc_304 + (_DWORD)v22) & 0xFFFFFFEF;
    if ( v2 )
      v24 = sid_reg_base;
    else
      v24 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_304 + (_DWORD)v24) = v23;
    mdelay(1);
    if ( v47[i] & 0x200 )
      *(&v44 + i) = v47[i] & 0x1FF;
    else
      *(&v44 + i) = -(v47[i] & 0x1FF);
  }
  if ( v45 - v44 < 0 )
    v25 = v44 - v45;
  else
    v25 = v45 - v44;
  v42 = v25;
  if ( v46 - v45 < 0 )
    v26 = v45 - v46;
  else
    v26 = v46 - v45;
  v43 = v26;
  if ( v44 - v46 < 0 )
    v27 = v46 - v44;
  else
    v27 = v44 - v46;
  v39 = v27 + v42;
  v40 = v42 + v43;
  v41 = v43 + v27;
  if ( v27 + v42 >= (unsigned int)(v42 + v43) || v39 >= v41 )
  {
    if ( v40 >= v39 || v40 >= v41 )
      v28 = v46;
    else
      v28 = v45;
  }
  else
  {
    v28 = v44;
  }
  if ( *v3 & 0x200 )
    v29 = *v3 & 0x1FF;
  else
    v29 = -(*v3 & 0x1FF);
  if ( v28 - v29 < 0 )
    v30 = v29 - v28;
  else
    v30 = v28 - v29;
  if ( v30 >= 100 )
    v31 = v29;
  else
    v31 = v28;
  if ( v31 < 0 )
    v32 = -v31;
  else
    v32 = v31 | 0x200;
  if ( v2 )
    v33 = sid_reg_base;
  else
    v33 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_304 + (_DWORD)v33) = (v32 << 16) | 0xC00;
  if ( v2 )
    v34 = sid_reg_base;
  else
    v34 = (int (*)())tve_reg_base;
  v35 = *(_DWORD *)((_BYTE *)&loc_300 + (_DWORD)v34) & 0xFFFFFFFE;
  if ( v2 )
    v36 = sid_reg_base;
  else
    v36 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_300 + (_DWORD)v36) = v35;
  if ( v2 )
    v37 = sid_reg_base;
  else
    v37 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_30 + (_DWORD)v37) = 1;
  return 0;
}
// 1A18: using guessed type int tve_reg_base;
// 1A1C: using guessed type int (*sid_reg_base)();

//----- (00000BF8) --------------------------------------------------------
int __fastcall tve_low_dac_autocheck_disable(int a1)
{
  int v1; // r1
  int (*v2)(); // r0
  int (*v3)(); // r0

  v1 = a1;
  if ( a1 )
    v2 = sid_reg_base;
  else
    v2 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_30 + (_DWORD)v2) = 0;
  if ( v1 )
    v3 = sid_reg_base;
  else
    v3 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_F8 + (_DWORD)v3) = 0;
  return 0;
}
// 1A18: using guessed type int tve_reg_base;
// 1A1C: using guessed type int (*sid_reg_base)();

//----- (00000C50) --------------------------------------------------------
int __fastcall tve_low_dac_autocheck_enable(int a1)
{
  int v1; // r1
  int (*v2)(); // r0
  int (*v3)(); // r0
  int (*v4)(); // r0
  int (*v5)(); // r0

  v1 = a1;
  if ( a1 )
    v2 = sid_reg_base;
  else
    v2 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_F8 + (_DWORD)v2) = 640;
  if ( v1 )
    v3 = sid_reg_base;
  else
    v3 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_FC + (_DWORD)v3) = 42926335;
  if ( v1 )
    v4 = sid_reg_base;
  else
    v4 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_3C + (_DWORD)v4) = 9;
  if ( v1 )
    v5 = sid_reg_base;
  else
    v5 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_30 + (_DWORD)v5) = 1;
  return 0;
}
// 1A18: using guessed type int tve_reg_base;
// 1A1C: using guessed type int (*sid_reg_base)();

//----- (00000CF4) --------------------------------------------------------
int __fastcall tve_low_dac_disable(int a1)
{
  int v1; // r1
  int (*v2)(); // r0
  unsigned int v3; // r2
  int (*v4)(); // r0

  v1 = a1;
  if ( a1 )
    v2 = sid_reg_base;
  else
    v2 = (int (*)())tve_reg_base;
  v3 = *(_DWORD *)((_BYTE *)&loc_8 + (_DWORD)v2) & 0xFFFFFFFE;
  if ( v1 )
    v4 = sid_reg_base;
  else
    v4 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_8 + (_DWORD)v4) = v3;
  return 0;
}
// 1A18: using guessed type int tve_reg_base;
// 1A1C: using guessed type int (*sid_reg_base)();

//----- (00000D48) --------------------------------------------------------
int __fastcall tve_low_dac_enable(int a1)
{
  int v1; // r1
  int (*v2)(); // r0
  int v3; // r2
  int (*v4)(); // r0

  v1 = a1;
  if ( a1 )
    v2 = sid_reg_base;
  else
    v2 = (int (*)())tve_reg_base;
  v3 = *(_DWORD *)((char *)&loc_8 + (_DWORD)v2) | 1;
  if ( v1 )
    v4 = sid_reg_base;
  else
    v4 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_8 + (_DWORD)v4) = v3;
  return 0;
}
// 1A18: using guessed type int tve_reg_base;
// 1A1C: using guessed type int (*sid_reg_base)();

//----- (00000D9C) --------------------------------------------------------
int __fastcall tve_low_enhance(int a1, int a2)
{
  int v2; // r2
  int (*v3)(); // r0
  unsigned int v4; // r3
  int (*v5)(); // r0
  int (*v6)(); // r0
  int v7; // r3
  int (*v8)(); // r0
  int (*v9)(); // r0
  unsigned int v10; // r3
  int (*v11)(); // r0
  int (*v12)(); // r0
  int v13; // r3
  int (*v14)(); // r0
  int (*v15)(); // r0
  unsigned int v16; // r3
  int (*v17)(); // r0
  int (*v18)(); // r0
  int v19; // r3
  int (*v20)(); // r0
  int (*v21)(); // r0
  unsigned int v22; // r3
  int (*v23)(); // r0
  int (*v24)(); // r0
  unsigned int v25; // r3
  int (*v26)(); // r0
  int (*v27)(); // r0
  unsigned int v28; // r3
  int (*v29)(); // r0
  int (*v30)(); // r0
  int v31; // r3
  int (*v32)(); // r0
  int (*v33)(); // r0
  int v34; // r3
  int (*v35)(); // r0

  v2 = a1;
  if ( a2 )
  {
    if ( a2 == 1 )
    {
      if ( a1 )
        v15 = sid_reg_base;
      else
        v15 = (int (*)())tve_reg_base;
      v16 = *(_DWORD *)v15 & 0xFFFFC3FF;
      if ( v2 )
        v17 = sid_reg_base;
      else
        v17 = (int (*)())tve_reg_base;
      *(_DWORD *)v17 = v16;
      if ( v2 )
        v18 = sid_reg_base;
      else
        v18 = (int (*)())tve_reg_base;
      v19 = *(_DWORD *)v18 | 0x1400;
      if ( v2 )
        v20 = sid_reg_base;
      else
        v20 = (int (*)())tve_reg_base;
      *(_DWORD *)v20 = v19;
      if ( v2 )
        v21 = sid_reg_base;
      else
        v21 = (int (*)())tve_reg_base;
      v22 = *(_DWORD *)((char *)&loc_C + (_DWORD)v21) | 0x80000000;
      if ( v2 )
        v23 = sid_reg_base;
      else
        v23 = (int (*)())tve_reg_base;
      *(_DWORD *)((char *)&loc_C + (_DWORD)v23) = v22;
      if ( v2 )
        v24 = sid_reg_base;
      else
        v24 = (int (*)())tve_reg_base;
      v25 = *(_DWORD *)((_BYTE *)&loc_C + (_DWORD)v24) & 0xFFFEFFFF;
      if ( v2 )
        v26 = sid_reg_base;
      else
        v26 = (int (*)())tve_reg_base;
      *(_DWORD *)((char *)&loc_C + (_DWORD)v26) = v25;
    }
    else if ( a2 == 2 )
    {
      if ( a1 )
        v27 = sid_reg_base;
      else
        v27 = (int (*)())tve_reg_base;
      v28 = *(_DWORD *)v27 & 0xFFFFC3FF;
      if ( v2 )
        v29 = sid_reg_base;
      else
        v29 = (int (*)())tve_reg_base;
      *(_DWORD *)v29 = v28;
      if ( v2 )
        v30 = sid_reg_base;
      else
        v30 = (int (*)())tve_reg_base;
      v31 = *(_DWORD *)((_BYTE *)&loc_C + (_DWORD)v30) & 0x7FFFFFFF;
      if ( v2 )
        v32 = sid_reg_base;
      else
        v32 = (int (*)())tve_reg_base;
      *(_DWORD *)((char *)&loc_C + (_DWORD)v32) = v31;
      if ( v2 )
        v33 = sid_reg_base;
      else
        v33 = (int (*)())tve_reg_base;
      v34 = *(_DWORD *)((char *)&loc_C + (_DWORD)v33) | 0x10000;
      if ( v2 )
        v35 = sid_reg_base;
      else
        v35 = (int (*)())tve_reg_base;
      *(_DWORD *)((char *)&loc_C + (_DWORD)v35) = v34;
    }
  }
  else
  {
    if ( a1 )
      v3 = sid_reg_base;
    else
      v3 = (int (*)())tve_reg_base;
    v4 = *(_DWORD *)v3 & 0xFFFFC3FF;
    if ( v2 )
      v5 = sid_reg_base;
    else
      v5 = (int (*)())tve_reg_base;
    *(_DWORD *)v5 = v4;
    if ( v2 )
      v6 = sid_reg_base;
    else
      v6 = (int (*)())tve_reg_base;
    v7 = *(_DWORD *)v6 | 0x1400;
    if ( v2 )
      v8 = sid_reg_base;
    else
      v8 = (int (*)())tve_reg_base;
    *(_DWORD *)v8 = v7;
    if ( v2 )
      v9 = sid_reg_base;
    else
      v9 = (int (*)())tve_reg_base;
    v10 = *(_DWORD *)((char *)&loc_C + (_DWORD)v9) | 0x80000000;
    if ( v2 )
      v11 = sid_reg_base;
    else
      v11 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_C + (_DWORD)v11) = v10;
    if ( v2 )
      v12 = sid_reg_base;
    else
      v12 = (int (*)())tve_reg_base;
    v13 = *(_DWORD *)((char *)&loc_C + (_DWORD)v12) | 0x10000;
    if ( v2 )
      v14 = sid_reg_base;
    else
      v14 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_C + (_DWORD)v14) = v13;
  }
  return 0;
}
// 1A18: using guessed type int tve_reg_base;
// 1A1C: using guessed type int (*sid_reg_base)();

//----- (000010B8) --------------------------------------------------------
int tve_low_exit()
{
  return 0;
}

//----- (000010C4) --------------------------------------------------------
int __fastcall tve_low_get_dac_status(int a1)
{
  int (*v1)(); // r0

  if ( a1 )
    v1 = sid_reg_base;
  else
    v1 = (int (*)())tve_reg_base;
  return *(_DWORD *)((_BYTE *)&loc_38 + (_DWORD)v1) & 3;
}
// 1A18: using guessed type int tve_reg_base;
// 1A1C: using guessed type int (*sid_reg_base)();

//----- (000010F4) --------------------------------------------------------
int __fastcall tve_low_init(int a1, int a2, signed int *a3, _DWORD *a4)
{
  int v4; // r12
  signed int v5; // r0
  int v6; // r1
  int (*v7)(); // r0
  int (*v8)(); // r0
  int (*v9)(); // r0
  int (*v10)(); // r0

  v4 = a1;
  if ( *a3 )
    v5 = *a3;
  else
    v5 = 645;
  v6 = v5 + *a4;
  if ( v4 )
    v7 = sid_reg_base;
  else
    v7 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_304 + (_DWORD)v7) = v6 << 16;
  if ( v4 )
    v8 = sid_reg_base;
  else
    v8 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_30C + (_DWORD)v8) = 1052944;
  if ( v4 )
    v9 = sid_reg_base;
  else
    v9 = (int (*)())tve_reg_base;
  *(_DWORD *)((char *)&loc_8 + (_DWORD)v9) = 1128141489;
  if ( v4 )
    v10 = sid_reg_base;
  else
    v10 = (int (*)())tve_reg_base;
  *(_DWORD *)v10 = 2147483648;
  return 0;
}
// 1A18: using guessed type int tve_reg_base;
// 1A1C: using guessed type int (*sid_reg_base)();

//----- (000011D4) --------------------------------------------------------
int __fastcall tve_low_open(int a1)
{
  int v1; // r1
  int (*v2)(); // r0
  int v3; // r2
  int (*v4)(); // r0
  int (*v5)(); // r0
  int v6; // r2
  int (*v7)(); // r0

  v1 = a1;
  if ( a1 )
    v2 = sid_reg_base;
  else
    v2 = (int (*)())tve_reg_base;
  v3 = *(_DWORD *)v2 & 0x7FFFFFFF;
  if ( v1 )
    v4 = sid_reg_base;
  else
    v4 = (int (*)())tve_reg_base;
  *(_DWORD *)v4 = v3;
  if ( v1 )
    v5 = sid_reg_base;
  else
    v5 = (int (*)())tve_reg_base;
  v6 = *(_DWORD *)v5 | 1;
  if ( v1 )
    v7 = sid_reg_base;
  else
    v7 = (int (*)())tve_reg_base;
  *(_DWORD *)v7 = v6;
  return 0;
}
// 1A18: using guessed type int tve_reg_base;
// 1A1C: using guessed type int (*sid_reg_base)();

//----- (0000126C) --------------------------------------------------------
int __fastcall tve_low_set_reg_base(int a1, int a2)
{
  if ( !a1 )
    tve_reg_base = a2;
  return 0;
}
// 1A18: using guessed type int tve_reg_base;

//----- (0000128C) --------------------------------------------------------
int __fastcall tve_low_set_tv_mode(int a1, int a2, int a3)
{
  int v3; // r4
  int v4; // r5
  int (*v5)(); // r0
  int (*v6)(); // r0
  int (*v7)(); // r0
  int (*v8)(); // r0
  int (*v9)(); // r0
  int (*v10)(); // r0
  int (*v11)(); // r0
  int (*v12)(); // r0
  int (*v13)(); // r0
  int (*v14)(); // r0
  int (*v15)(); // r0
  int (*v16)(); // r0
  int (*v17)(); // r0
  int (*v18)(); // r0
  int (*v19)(); // r0
  int (*v20)(); // r0
  int (*v21)(); // r0
  int (*v22)(); // r0
  int (*v23)(); // r0
  int (*v24)(); // r0
  int (*v25)(); // r0
  int (*v26)(); // r0
  int (*v27)(); // r0
  int (*v28)(); // r0
  int (*v29)(); // r0
  int (*v30)(); // r0
  int (*v31)(); // r0
  int (*v32)(); // r0
  int (*v33)(); // r0
  int (*v34)(); // r0
  int (*v35)(); // r0
  int (*v36)(); // r0
  int (*v37)(); // r0
  int (*v38)(); // r0
  int (*v39)(); // r0
  int (*v40)(); // r0
  int (*v41)(); // r0
  int (*v42)(); // r0
  int (*v43)(); // r0
  int (*v44)(); // r0
  int (*v45)(); // r0
  int (*v46)(); // r0
  int (*v47)(); // r0
  int (*v48)(); // r0
  int (*v49)(); // r0
  int (*v50)(); // r0
  int (*v51)(); // r0
  int (*v52)(); // r0
  int (*v53)(); // r0

  v3 = a1;
  v4 = a2;
  tve_low_dac_auto_cali(a1, (_DWORD *)a3);
  if ( v4 == 6 )
  {
    if ( v3 )
      v5 = sid_reg_base;
    else
      v5 = (int (*)())tve_reg_base;
    *(_DWORD *)v5 = 768;
    if ( v3 )
      v6 = sid_reg_base;
    else
      v6 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_4 + (_DWORD)v6) = 117899264;
    if ( v3 )
      v7 = sid_reg_base;
    else
      v7 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_C + (_DWORD)v7) = 805311488;
    if ( v3 )
      v8 = sid_reg_base;
    else
      v8 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_10 + (_DWORD)v8) = 569408543;
    if ( v3 )
      v9 = sid_reg_base;
    else
      v9 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_14 + (_DWORD)v9) = 7733280;
    if ( v3 )
      v10 = sid_reg_base;
    else
      v10 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_18 + (_DWORD)v10) = 22;
    if ( v3 )
      v11 = sid_reg_base;
    else
      v11 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_1C + (_DWORD)v11) = 1442317;
    if ( v3 )
      v12 = sid_reg_base;
    else
      v12 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_20 + (_DWORD)v12) = 15728922;
    if ( v3 )
      v13 = sid_reg_base;
    else
      v13 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_100 + (_DWORD)v13) = 1;
    if ( v3 )
      v14 = sid_reg_base;
    else
      v14 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_104 + (_DWORD)v14) = 0;
    if ( v3 )
      v15 = sid_reg_base;
    else
      v15 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_108 + (_DWORD)v15) = 2;
    if ( v3 )
      v16 = sid_reg_base;
    else
      v16 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_10C + (_DWORD)v16) = 79;
    if ( v3 )
      v17 = sid_reg_base;
    else
      v17 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_110 + (_DWORD)v17) = 0;
    if ( v3 )
      v18 = sid_reg_base;
    else
      v18 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_114 + (_DWORD)v18) = 1459326;
    if ( v3 )
      v19 = sid_reg_base;
    else
      v19 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_118 + (_DWORD)v19) = 41120;
    if ( v3 )
      v20 = sid_reg_base;
    else
      v20 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_11C + (_DWORD)v20) = 1048816;
    if ( v3 )
      v21 = sid_reg_base;
    else
      v21 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_120 + (_DWORD)v21) = 31982368;
    if ( v3 )
      v22 = sid_reg_base;
    else
      v22 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_124 + (_DWORD)v22) = 1440;
    if ( v3 )
      v23 = sid_reg_base;
    else
      v23 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_128 + (_DWORD)v23) = 0x10000;
    if ( v3 )
      v24 = sid_reg_base;
    else
      v24 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_12C + (_DWORD)v24) = 257;
    if ( v3 )
      v25 = sid_reg_base;
    else
      v25 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_130 + (_DWORD)v25) = 537199464;
    if ( v3 )
      v26 = sid_reg_base;
    else
      v26 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_134 + (_DWORD)v26) = 0;
    if ( v3 )
      v27 = sid_reg_base;
    else
      v27 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_138 + (_DWORD)v27) = 0;
    if ( v3 )
      v28 = sid_reg_base;
    else
      v28 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_13C + (_DWORD)v28) = 0;
  }
  else
  {
    if ( v3 )
      v29 = sid_reg_base;
    else
      v29 = (int (*)())tve_reg_base;
    *(_DWORD *)v29 = 768;
    if ( v3 )
      v30 = sid_reg_base;
    else
      v30 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_4 + (_DWORD)v30) = 117899265;
    if ( v3 )
      v31 = sid_reg_base;
    else
      v31 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_C + (_DWORD)v31) = 805311488;
    if ( v3 )
      v32 = sid_reg_base;
    else
      v32 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_10 + (_DWORD)v32) = 705268427;
    if ( v3 )
      v33 = sid_reg_base;
    else
      v33 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_14 + (_DWORD)v33) = 9043992;
    if ( v3 )
      v34 = sid_reg_base;
    else
      v34 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_18 + (_DWORD)v34) = 22;
    if ( v3 )
      v35 = sid_reg_base;
    else
      v35 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_1C + (_DWORD)v35) = 1442417;
    if ( v3 )
      v36 = sid_reg_base;
    else
      v36 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_20 + (_DWORD)v36) = 16515324;
    if ( v3 )
      v37 = sid_reg_base;
    else
      v37 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_100 + (_DWORD)v37) = 0;
    if ( v3 )
      v38 = sid_reg_base;
    else
      v38 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_104 + (_DWORD)v38) = 1;
    if ( v3 )
      v39 = sid_reg_base;
    else
      v39 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_108 + (_DWORD)v39) = 5;
    if ( v3 )
      v40 = sid_reg_base;
    else
      v40 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_10C + (_DWORD)v40) = 10537;
    if ( v3 )
      v41 = sid_reg_base;
    else
      v41 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_110 + (_DWORD)v41) = 0;
    if ( v3 )
      v42 = sid_reg_base;
    else
      v42 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_114 + (_DWORD)v42) = 1459326;
    if ( v3 )
      v43 = sid_reg_base;
    else
      v43 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_118 + (_DWORD)v43) = 168;
    if ( v3 )
      v44 = sid_reg_base;
    else
      v44 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_11C + (_DWORD)v44) = 1048828;
    if ( v3 )
      v45 = sid_reg_base;
    else
      v45 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_120 + (_DWORD)v45) = 31982368;
    if ( v3 )
      v46 = sid_reg_base;
    else
      v46 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_124 + (_DWORD)v46) = 1440;
    if ( v3 )
      v47 = sid_reg_base;
    else
      v47 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_128 + (_DWORD)v47) = 0x10000;
    if ( v3 )
      v48 = sid_reg_base;
    else
      v48 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_12C + (_DWORD)v48) = 257;
    if ( v3 )
      v49 = sid_reg_base;
    else
      v49 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_130 + (_DWORD)v49) = 537198602;
    if ( v3 )
      v50 = sid_reg_base;
    else
      v50 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_134 + (_DWORD)v50) = 0;
    if ( v3 )
      v51 = sid_reg_base;
    else
      v51 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_138 + (_DWORD)v51) = 0;
    if ( v3 )
      v52 = sid_reg_base;
    else
      v52 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_13C + (_DWORD)v52) = 0;
    if ( v3 )
      v53 = sid_reg_base;
    else
      v53 = (int (*)())tve_reg_base;
    *(_DWORD *)((char *)&loc_3A0 + (_DWORD)v53) = 196609;
  }
  return 0;
}
// 1A18: using guessed type int tve_reg_base;
// 1A1C: using guessed type int (*sid_reg_base)();

//----- (000019F8) --------------------------------------------------------
_WORD *__fastcall write16(_WORD *result, int a2, __int16 a3)
{
  *result = a3;
  return result;
}

//----- (00001A00) --------------------------------------------------------
_DWORD *__fastcall write32(_DWORD *result, int a2, int a3)
{
  *result = a3;
  return result;
}

//----- (00001A08) --------------------------------------------------------
_QWORD *__fastcall write64(_QWORD *result, int a2, __int64 a3)
{
  *result = a3;
  return result;
}

//----- (00001A10) --------------------------------------------------------
_BYTE *__fastcall write8(_BYTE *result, int a2, char a3)
{
  *result = a3;
  return result;
}

// ALL OK, 30 function(s) have been successfully decompiled
