/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

unsigned int __fastcall BSP_TVD_3D_COMB_Filter(int a1, int a2);
void __fastcall BSP_TVD_c_peak(int a1);
void __cdecl BSP_TVD_capture_off();
void __cdecl BSP_TVD_capture_on();
void __fastcall BSP_TVD_config(int a1, int a2, int a3);
unsigned int BSP_TVD_get_hor_start();
int BSP_TVD_get_status();
int BSP_TVD_get_ver_start();
void __cdecl BSP_TVD_init();
void __fastcall BSP_TVD_input_select(int a1);
void __fastcall BSP_TVD_irq_disable(int a1, int a2);
int __fastcall BSP_TVD_irq_enable(int a1, int a2);
signed int __fastcall BSP_TVD_irq_status_clear(int a1, int a2);
unsigned int __fastcall BSP_TVD_irq_status_get(int a1, int a2);
void __fastcall BSP_TVD_set_addr_c(int a1, int a2);
void __fastcall BSP_TVD_set_addr_y(int a1, int a2);
void __fastcall BSP_TVD_set_fmt(int a1, int a2);
void __fastcall BSP_TVD_set_height(int a1, int a2);
void __fastcall BSP_TVD_set_hor_start(int a1, int a2);
void __fastcall BSP_TVD_set_ver_start(int a1, __int16 a2);
void __fastcall BSP_TVD_set_width(int a1, unsigned int a2);
void __fastcall BSP_TVD_set_width_jump(int a1, int a2);
void __fastcall BSP_TVD_y_peak(int a1);
void __cdecl IRQ_TVD_ISR();
int __fastcall TVD_Config(int a1);
int (*__fastcall TVD_StatusHandle(int (*result)()))();
signed int __fastcall com_video_set_blue_flag(char a1);
signed int __fastcall com_video_set_bright(unsigned __int8 a1);
signed int __fastcall com_video_set_chrom_gain(unsigned __int8 a1);
signed int __fastcall com_video_set_contrast(unsigned __int8 a1);
signed int __fastcall com_video_set_hue(unsigned __int8 a1);
signed int __fastcall com_video_set_saturation(unsigned __int8 a1);
int f1c100s_clk_init();
int f1c100s_tvd_AutoMode();
int f1c100s_tvd_Init();
void __fastcall f1c100s_tvd_init(int a1);
int f1c100s_tvd_off();
int __fastcall f1c100s_tvd_set(int a1, int a2, int a3, int a4);
int __fastcall read16(unsigned __int16 *a1);
int __fastcall read32(int a1);
__int64 __fastcall read64(int a1);
int __fastcall read8(unsigned __int8 *a1);
int tvd_get_status();
_WORD *__fastcall write16(_WORD *result, int a2, __int16 a3);
_DWORD *__fastcall write32(_DWORD *result, int a2, int a3);
_QWORD *__fastcall write64(_QWORD *result, int a2, __int64 a3);
_BYTE *__fastcall write8(_BYTE *result, int a2, char a3);
// int Debe_tvdoff(void); weak
// int __fastcall Debe_tvdset(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall Defe_Config_video_uvcombined_yuv422_to_argb(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall Defe_Init(_DWORD); weak
// int __fastcall Defe_Start(_DWORD); weak
// int __fastcall Open_Dev_Clock(_DWORD); weak
// int __fastcall delay_ms(_DWORD); weak
// int sysprintf(const char *, ...); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_4; // weak
_UNKNOWN loc_8; // weak
_UNKNOWN loc_24; // weak
_UNKNOWN loc_2C; // weak
_UNKNOWN loc_30; // weak
_UNKNOWN loc_44; // weak
_UNKNOWN loc_48; // weak
int dword_F1C[5] = { 3852576998, 2296745916, 2727208583, 221130286, 10 }; // weak
_UNKNOWN tvin_buff_y; // weak
_UNKNOWN tvin_buff_c; // weak
__int16 tvd_dis_w = 0; // weak
__int16 tvd_dis_h = 0; // weak
__int16 tvd_dis_x = 0; // weak
__int16 tvd_dis_y = 0; // weak
char tvd_status = '\0'; // weak
int (*tvin_mode[2])() = { &BSP_TVD_3D_COMB_Filter, &BSP_TVD_3D_COMB_Filter }; // weak
int mode = 1; // weak
int tmode = 1; // weak
int dword_1C0B000; // weak
int dword_1C0B008; // weak
int dword_1C0B00C; // weak
int dword_1C0B010; // weak
int dword_1C0B014; // weak
int dword_1C0B018; // weak
int dword_1C0B01C; // weak
int dword_1C0B040; // weak
int dword_1C0B048; // weak
int dword_1C0B04C; // weak
int dword_1C0B050; // weak
int dword_1C0B054; // weak
int dword_1C0B080; // weak
int dword_1C0B084; // weak
int dword_1C0B088; // weak
int dword_1C0B08C; // weak
int dword_1C0B090; // weak
int dword_1C0B094; // weak
int dword_1C0B09C; // weak
int dword_1C0BE04; // weak
int dword_1C0BE2C; // weak
_DWORD dword_1C0BE40;
int dword_1C0BF08; // weak
int dword_1C0BF0C; // weak
int dword_1C0BF10; // weak
int dword_1C0BF14; // weak
int dword_1C0BF1C; // weak
int dword_1C0BF24; // weak


//----- (00000000) --------------------------------------------------------
unsigned int __fastcall BSP_TVD_3D_COMB_Filter(int a1, int a2)
{
  _DWORD *v2; // r3
  unsigned int result; // r0

  if ( a1 )
  {
    dword_1C0B04C = a2;
    dword_1C0B050 = a2 + 0x200000;
    dword_1C0B054 = 0x200000;
    dword_1C0B048 = 0x4040001;
    v2 = (&dword_1C0B000 & ~0x4040001u);
    *(&loc_8 + v2) = *(&loc_8 + (&dword_1C0B000 & ~0x4040001u)) & 0xFFFFFFFE;
    result = *(&dword_1C0B000 & ~0x4040001u) | 0x10;
    *v2 = result;
  }
  else
  {
    dword_1C0B008 |= 1u;
    result = dword_1C0B000 & ~0x10u;
    dword_1C0B000 &= ~0x10u;
  }
  return result;
}
// 1C0B000: using guessed type int dword_1C0B000;
// 1C0B008: using guessed type int dword_1C0B008;
// 1C0B048: using guessed type int dword_1C0B048;
// 1C0B04C: using guessed type int dword_1C0B04C;
// 1C0B050: using guessed type int dword_1C0B050;
// 1C0B054: using guessed type int dword_1C0B054;

//----- (00000078) --------------------------------------------------------
void __fastcall BSP_TVD_c_peak(int a1)
{
  if ( a1 )
    dword_1C0B010 |= 0x10000u;
  else
    dword_1C0B010 &= 0xFFFEFFFF;
}
// 1C0B010: using guessed type int dword_1C0B010;

//----- (000000B0) --------------------------------------------------------
void __cdecl BSP_TVD_capture_off()
{
  dword_1C0B088 &= 0xFFFFFFFE;
}
// 1C0B088: using guessed type int dword_1C0B088;

//----- (000000CC) --------------------------------------------------------
void __cdecl BSP_TVD_capture_on()
{
  dword_1C0B088 |= 1u;
}
// 1C0B088: using guessed type int dword_1C0B088;

//----- (000000E8) --------------------------------------------------------
void __fastcall BSP_TVD_config(int a1, int a2, int a3)
{
  int v3; // r6
  int v4; // r5
  int v5; // r4
  unsigned int v6; // r1
  unsigned int v7; // r1
  unsigned int v8; // r1
  signed int v9; // r1
  int v10; // r1
  signed int v11; // r1
  int v12; // r1

  v3 = a1;
  v4 = a2;
  v5 = a3;
  sysprintf("system:%d\r\n", a2);
  dword_1C0BE04 = 0x8002AAA8;
  dword_1C0BE2C = 0x110000;
  dword_1C0B040 = 0x4000310;
  dword_1C0B000 = 0;
  delay_ms(1000);
  dword_1C0B000 = 0x1F00;                       // reset?
  dword_1C0B014 = 0x20000000;
  dword_1C0BF24 = 0x682810A;
  *(&dword_1C0BF24 ^ 0xC) = 0x6440;             // 1C0BF28
  *(&loc_24 + (&dword_1C0BF24 ^ 0xC)) = 0xE70106C;// 1C0BF4C
  *(&loc_2C + (&dword_1C0BF24 ^ 0xC)) = 0;      // 1C0BF54
  *(&loc_30 + (&dword_1C0BF24 ^ 0xC)) = 0x82;   // 1C0BF58
  *(&loc_44 + (&dword_1C0BF24 ^ 0xC)) = 0xFFFAD0;// 1C0BF6C
  *(&loc_48 + (&dword_1C0BF24 ^ 0xC)) = 0xA010; // 1C0BF70
  if ( v3 == 1 )
  {
    switch ( v4 )
    {
      case 1:
        dword_1C0B008 = 0x10001;
        dword_1C0B00C = 0x202068;
        dword_1C0B010 = 0x300080;
        dword_1C0B018 = 0x21F07C1F;
        dword_1C0B01C = 0x820022;
        dword_1C0BF08 = 0x590100;
        *(&dword_1C0BF08 | 4) = 0x10;           // 1c0bf0c
        *(&loc_4 + (&dword_1C0BF08 | 4)) = 0x8A32DD;// 1C0BF10
        v6 = (&dword_1C0BF08 | 4) + 8;
        *v6 = 0x800000A0;                       // 1C0BF14
        v6 |= 8u;
        *v6 = 0x8A0000;                         // 1C0BF1C
        v6 += 0x10;
        *v6 = 0xCB74;                           // 1C0BF2C
        v6 += 0x18;
        *v6 = 0x4632;                           // 1C0BF44
        v6 |= 0x3C30u;
        *v6 = 0x3C3;                            // 1C0BF74
        v6 += 0xC;
        *v6 = 0x500000;                         // 1C0BF80
        *(v6 | 0x184) = 0x610000;               // 1C0BF84
        dword_1C0B000 = 1;
        if ( v5 == 1 )
        {
          BSP_TVD_set_width(0, 0x2C0u);
          BSP_TVD_set_width_jump(0, 704);
          BSP_TVD_set_height(0, 224);
          BSP_TVD_set_ver_start(0, 50);
        }
        else
        {
          BSP_TVD_set_width(0, 0x2D0u);
          BSP_TVD_set_width_jump(0, 720);
          BSP_TVD_set_height(0, 240);
        }
        break;
      case 2:
        dword_1C0B008 = 0x1101001;
        dword_1C0B00C = 0x202068;
        dword_1C0B010 = 0x300050;
        dword_1C0B018 = 0x2A098ACB;
        dword_1C0B01C = 0x87002A;
        dword_1C0BF08 = 0x11590902;
        dword_1C0BF0C = 0x16;
        dword_1C0BF10 = 0x8A32EC;
        dword_1C0BF14 = 0x800000A0;
        v7 = &dword_1C0BF14 | (&dword_1C0BF14 >> 20);
        *v7 = 0x930000;
        v7 += 0x10;
        *v7 = 0xD74;
        v7 += 0x18;
        *v7 = 16685;
        v7 |= 0x34u;
        *v7 = 835;
        v7 += 0xC;
        *v7 = 5242880;
        *(v7 | 0x304) = 12648448;
        dword_1C0B000 = 1;
        if ( v5 == 1 )
        {
          BSP_TVD_set_width(0, 704u);
          BSP_TVD_set_width_jump(0, 704);
        }
        else
        {
          BSP_TVD_set_width(0, 0x2D0u);
          BSP_TVD_set_width_jump(0, 720);
        }
        BSP_TVD_set_height(0, 288);
        break;
      case 3:
        dword_1C0B008 = 0x2001;
        dword_1C0B00C = 0x2080;
        dword_1C0B010 = 0x300080;
        dword_1C0B018 = 0x21E6EFE3;
        dword_1C0B01C = 0x820022;
        dword_1C0BF08 = 0x590100;
        *(&dword_1C0BF08 | 4) = 64;
        *(&loc_4 + (&dword_1C0BF08 | 4)) = 0x8A32DD;
        v8 = (&dword_1C0BF08 | 4) + 8;
        *v8 = 0x800000A0;
        v8 |= 8u;
        *v8 = 9043968;
        v8 += 16;
        *v8 = 0xCB74;
        v8 += 24;
        *v8 = 0x4632;
        v8 |= 0x3C30u;
        *v8 = 0x3C3;
        v8 += 12;
        *v8 = 5242880;
        *(v8 | 0x184) = 6356992;
        dword_1C0B000 = 1;
        if ( v5 == 1 )
        {
          BSP_TVD_set_width(0, 704u);
          BSP_TVD_set_width_jump(0, 704);
          BSP_TVD_set_height(0, 224);
          dword_1C0B01C = 0x820032;
        }
        else
        {
          BSP_TVD_set_width(0, 0x2D0u);
          BSP_TVD_set_width_jump(0, 720);
          BSP_TVD_set_height(0, 240);
        }
        break;
      case 4:
        dword_1C0B008 = 0x1103001;
        dword_1C0B00C = 0x2080;
        dword_1C0B010 = 0x300080;
        dword_1C0B018 = 0x21F69446;
        dword_1C0B01C = 0x870026;
        dword_1C0BF08 = 0x11590902;
        *(&dword_1C0BF08 | 4) = 64;
        *(&loc_4 + (&dword_1C0BF08 | 4)) = 0x8A32EC;
        v9 = (&dword_1C0BF08 | 4) + 8;
        *v9 = 0x800000A0;
        v10 = v9 | (v9 >> 20);
        *v10 = 14417920;
        v10 += 16;
        *v10 = 0xD74;
        v10 += 24;
        *v10 = 0x4632;
        v10 |= 0x34u;
        *v10 = 835;
        v10 += 12;
        *v10 = 5242880;
        *(v10 | 0x304) = 12648448;
        dword_1C0B000 = 1;
        if ( v5 == 1 )
        {
          BSP_TVD_set_width(0, 0x2C0u);
          BSP_TVD_set_width_jump(0, 704);
        }
        else
        {
          BSP_TVD_set_width(0, 0x2D0u);
          BSP_TVD_set_width_jump(0, 720);
        }
        BSP_TVD_set_height(0, 288);
        break;
      case 5:
        dword_1C0B008 = 0x1104001;
        dword_1C0B00C = 0x2080;
        dword_1C0B010 = 0x3100B0;
        dword_1C0B018 = 0x28A33BB2;
        dword_1C0B01C = 0x870026;
        dword_1C0BF08 = 0x11590902;
        *(&dword_1C0BF08 | 4) = 64;
        *(&loc_4 + (&dword_1C0BF08 | 4)) = 0x8A32EC;
        v11 = (&dword_1C0BF08 | 4) + 8;
        *v11 = 0x800000A0;
        v12 = v11 | (v11 >> 20);
        *v12 = 14417920;
        v12 += 16;
        *v12 = 0xD74;
        v12 += 24;
        *v12 = 20534;
        v12 |= 0x34u;
        *v12 = 835;
        v12 += 12;
        *v12 = 5242880;
        *(v12 | 0x304) = 12648448;
        dword_1C0B000 = 1;
        if ( v5 == 1 )
        {
          BSP_TVD_set_width(0, 0x2C0u);
          BSP_TVD_set_width_jump(0, 704);
        }
        else
        {
          BSP_TVD_set_width(0, 0x2D0u);
          BSP_TVD_set_width_jump(0, 720);
        }
        BSP_TVD_set_height(0, 288);
        break;
      default:
        break;
    }
    dword_1C0BE2C = 0x60000000;
  }
}
// CBC34: using guessed type int __fastcall delay_ms(_DWORD);
// CBC38: using guessed type int sysprintf(const char *, ...);
// 1C0B000: using guessed type int dword_1C0B000;
// 1C0B008: using guessed type int dword_1C0B008;
// 1C0B00C: using guessed type int dword_1C0B00C;
// 1C0B010: using guessed type int dword_1C0B010;
// 1C0B014: using guessed type int dword_1C0B014;
// 1C0B018: using guessed type int dword_1C0B018;
// 1C0B01C: using guessed type int dword_1C0B01C;
// 1C0B040: using guessed type int dword_1C0B040;
// 1C0BE04: using guessed type int dword_1C0BE04;
// 1C0BE2C: using guessed type int dword_1C0BE2C;
// 1C0BF08: using guessed type int dword_1C0BF08;
// 1C0BF0C: using guessed type int dword_1C0BF0C;
// 1C0BF10: using guessed type int dword_1C0BF10;
// 1C0BF14: using guessed type int dword_1C0BF14;
// 1C0BF24: using guessed type int dword_1C0BF24;

//----- (000007E8) --------------------------------------------------------
unsigned int BSP_TVD_get_hor_start()
{
  return (dword_1C0B01C >> 16) & 0xFFF;
}
// 1C0B01C: using guessed type int dword_1C0B01C;

//----- (00000808) --------------------------------------------------------
int BSP_TVD_get_status()
{
  signed int v0; // r2

  v0 = 0;
  if ( !(dword_1C0BE40 & 1) )                   // det
    v0 = 1;
  return v0 + 16 * ((dword_1C0BE40 & 0x40000) != 0);// return ((det<<0)+(system<<4));
}

//----- (00000858) --------------------------------------------------------
int BSP_TVD_get_ver_start()
{
  return dword_1C0B01C & 0x7FF;
}
// 1C0B01C: using guessed type int dword_1C0B01C;

//----- (00000874) --------------------------------------------------------
void __cdecl BSP_TVD_init()
{
  dword_1C0B088 = 0x4000000;
}
// 1C0B088: using guessed type int dword_1C0B088;

//----- (00000888) --------------------------------------------------------
void __fastcall BSP_TVD_input_select(int a1)
{
  if ( a1 )
    dword_1C0BE04 |= 1u;
  else
    dword_1C0BE04 &= 0xFFFFFFFE;
}
// 1C0BE04: using guessed type int dword_1C0BE04;

//----- (000008C0) --------------------------------------------------------
void __fastcall BSP_TVD_irq_disable(int a1, int a2)
{
  if ( a2 == 1 )
    dword_1C0B09C &= ~0x1000000u;               // frame_end?
}
// 1C0B09C: using guessed type int dword_1C0B09C;

//----- (000008EC) --------------------------------------------------------
int __fastcall BSP_TVD_irq_enable(int a1, int a2)
{
  int result; // r0

  if ( a2 == 1 )
  {
    result = dword_1C0B09C | 0x1000000;
    dword_1C0B09C |= 0x1000000u;
  }
  return result;
}
// 1C0B09C: using guessed type int dword_1C0B09C;

//----- (00000940) --------------------------------------------------------
signed int __fastcall BSP_TVD_irq_status_clear(int a1, int a2)
{
  signed int result; // r0

  if ( a2 == 1 )
  {
    result = 0x1000000;
    dword_1C0B094 = 0x1000000;
  }
  return result;
}
// 1C0B094: using guessed type int dword_1C0B094;

//----- (00000968) --------------------------------------------------------
unsigned int __fastcall BSP_TVD_irq_status_get(int a1, int a2)
{
  unsigned int result; // r0

  result = 0;
  if ( a2 == 1 )
    result = (dword_1C0B094 >> 24) & 1;
  return result;
}
// 1C0B094: using guessed type int dword_1C0B094;

//----- (00000998) --------------------------------------------------------
void __fastcall BSP_TVD_set_addr_c(int a1, int a2)
{
  dword_1C0B084 = a2;
  dword_1C0B088 |= 0x10000000u;
}
// 1C0B084: using guessed type int dword_1C0B084;
// 1C0B088: using guessed type int dword_1C0B088;

//----- (000009B8) --------------------------------------------------------
void __fastcall BSP_TVD_set_addr_y(int a1, int a2)
{
  dword_1C0B080 = a2;
  dword_1C0B088 |= 0x10000000u;
}
// 1C0B080: using guessed type int dword_1C0B080;
// 1C0B088: using guessed type int dword_1C0B088;

//----- (000009D8) --------------------------------------------------------
void __fastcall BSP_TVD_set_fmt(int a1, int a2)
{
  unsigned int v2; // r0

  v2 = dword_1C0B088;
  if ( a2 )
  {
    if ( a2 == 1 )
    {
      v2 = (dword_1C0B088 | 0x1000000) & ~0x10u;// TVD_UV_NON_MB_COMBINED_YUV420   //422???
    }
    else if ( a2 == 2 )
    {
      v2 = dword_1C0B088 & ~0x1000000u | 0x10;  // TVD_UV_MB_COMBINED_YUV420
    }
  }
  else
  {
    v2 = dword_1C0B088 & ~0x1000010u;           // TVD_UV_NON_MB_COMBINED_YUV422? // 420??
  }
  dword_1C0B088 = v2;
}
// 1C0B088: using guessed type int dword_1C0B088;

//----- (00000A3C) --------------------------------------------------------
void __fastcall BSP_TVD_set_height(int a1, int a2)
{
  dword_1C0B08C = dword_1C0B08C & 0xF800FFFF | (a2 << 16);
}
// 1C0B08C: using guessed type int dword_1C0B08C;

//----- (00000A60) --------------------------------------------------------
void __fastcall BSP_TVD_set_hor_start(int a1, int a2)
{
  dword_1C0B01C = dword_1C0B01C & 0xF000FFFF | ((a2 & 0xFFFF0FFF) << 16);
}
// 1C0B01C: using guessed type int dword_1C0B01C;

//----- (00000A8C) --------------------------------------------------------
void __fastcall BSP_TVD_set_ver_start(int a1, __int16 a2)
{
  dword_1C0B01C = (dword_1C0B01C >> 11 << 11) | a2 & 0x7FF;
}
// 1C0B01C: using guessed type int dword_1C0B01C;

//----- (00000ABC) --------------------------------------------------------
void __fastcall BSP_TVD_set_width(int a1, unsigned int a2)
{
  unsigned int v2; // r3

  if ( a2 <= 720 )
    v2 = a2;
  else
    v2 = 720;
  dword_1C0B08C = (dword_1C0B08C >> 12 << 12) | v2;
}
// 1C0B08C: using guessed type int dword_1C0B08C;

//----- (00000AF8) --------------------------------------------------------
void __fastcall BSP_TVD_set_width_jump(int a1, int a2)
{
  dword_1C0B090 = a2;
}
// 1C0B090: using guessed type int dword_1C0B090;

//----- (00000B08) --------------------------------------------------------
void __fastcall BSP_TVD_y_peak(int a1)
{
  if ( a1 )
    dword_1C0B00C |= 0x10000u;
  else
    dword_1C0B00C &= ~0x10000u;
}
// 1C0B00C: using guessed type int dword_1C0B00C;

//----- (00000B40) --------------------------------------------------------
void __cdecl IRQ_TVD_ISR()
{
  if ( BSP_TVD_irq_status_get(0, 1) )
    BSP_TVD_irq_status_clear(0, 1);
}

//----- (00000B68) --------------------------------------------------------
int __fastcall TVD_Config(int a1)
{
  int v1; // r4
  int v2; // r0
  int v3; // r0

  v1 = a1;
  sysprintf("TVD Config...\r\n");
  f1c100s_tvd_init(v1);
  v3 = Defe_Init(v2);
  if ( v1 == 1 )
  {
    v3 = Defe_Config_video_uvcombined_yuv422_to_argb(720, 480, tvd_dis_w, tvd_dis_h);
  }
  else if ( v1 == 2 )
  {
    v3 = Defe_Config_video_uvcombined_yuv422_to_argb(720, 576, tvd_dis_w, tvd_dis_h);
  }
  return Defe_Start(v3);
}
// CBC00: using guessed type __int16 tvd_dis_w;
// CBC02: using guessed type __int16 tvd_dis_h;
// CBC24: using guessed type int __fastcall Defe_Config_video_uvcombined_yuv422_to_argb(_DWORD, _DWORD, _DWORD, _DWORD);
// CBC28: using guessed type int __fastcall Defe_Init(_DWORD);
// CBC2C: using guessed type int __fastcall Defe_Start(_DWORD);
// CBC38: using guessed type int sysprintf(const char *, ...);

//----- (00000BF0) --------------------------------------------------------
int (*__fastcall TVD_StatusHandle(int (*result)()))()
{
  tvin_mode[0] = result;
  return result;
}
// CBC0C: using guessed type int (*tvin_mode[2])();

//----- (00000C00) --------------------------------------------------------
signed int __fastcall com_video_set_blue_flag(char a1)
{
  dword_1C0BF14 = dword_1C0BF14 & ~0x30u | 16 * (a1 & 3);
  return 1;
}
// 1C0BF14: using guessed type int dword_1C0BF14;

//----- (00000C2C) --------------------------------------------------------
signed int __fastcall com_video_set_bright(unsigned __int8 a1)
{
  dword_1C0B00C = dword_1C0B00C & 0xFFFF00FF | (a1 << 8);
  return 1;
}
// 1C0B00C: using guessed type int dword_1C0B00C;

//----- (00000C54) --------------------------------------------------------
signed int __fastcall com_video_set_chrom_gain(unsigned __int8 a1)
{
  dword_1C0BF1C = dword_1C0BF1C & 0xFF00FFFF | (a1 << 16);
  return 1;
}
// 1C0BF1C: using guessed type int dword_1C0BF1C;

//----- (00000C7C) --------------------------------------------------------
signed int __fastcall com_video_set_contrast(unsigned __int8 a1)
{
  dword_1C0B00C = dword_1C0B00C & 0xFFFFFF00 | a1;
  return 1;
}
// 1C0B00C: using guessed type int dword_1C0B00C;

//----- (00000CA4) --------------------------------------------------------
signed int __fastcall com_video_set_hue(unsigned __int8 a1)
{
  dword_1C0B010 = dword_1C0B010 & ~0xFF00u | (a1 << 8);
  return 1;
}
// 1C0B010: using guessed type int dword_1C0B010;

//----- (00000CCC) --------------------------------------------------------
signed int __fastcall com_video_set_saturation(unsigned __int8 a1)
{
  dword_1C0B010 = dword_1C0B010 & 0xFFFFFF00 | a1;
  return 1;
}
// 1C0B010: using guessed type int dword_1C0B010;

//----- (00000CF4) --------------------------------------------------------
int f1c100s_clk_init()
{
  int v0; // r0
  int v1; // r0
  int v2; // r0
  int v3; // r0
  int v4; // r0

  Open_Dev_Clock(265);
  v0 = read32(0x1C20100);
  write32(0x1C20100, 0, v0 | 8);
  v1 = read32(0x1C20010);
  write32(0x1C20010, 0, v1 & 0x7FFFFFFF);
  write32(0x1C20010, 0, 25088);
  v2 = read32(0x1C20010);
  write32(0x1C20010, 0, v2 | 0x80000000);
  delay_ms(1);
  write32(0x1C20124, 0, 0);
  v3 = read32(0x1C20124);
  write32(0x1C20124, 0, v3 | 9);
  v4 = read32(0x1C20124);
  write32(0x1C20124, 0, v4 | 0x80000000);
  return Open_Dev_Clock(265);
}
// CBC30: using guessed type int __fastcall Open_Dev_Clock(_DWORD);
// CBC34: using guessed type int __fastcall delay_ms(_DWORD);

//----- (00000DE4) --------------------------------------------------------
int f1c100s_tvd_AutoMode()
{
  int result; // r0
  int v1; // r4

  result = tvd_status;
  if ( tvd_status )
  {
    v1 = BSP_TVD_get_status();
    if ( v1 & 0xF )
    {
      if ( (v1 >> 4) & 0xF )
      {
        mode = 2;
        if ( tvin_mode[0] )
          *tvin_mode[0] = 1;
      }
      else
      {
        mode = 1;
        if ( tvin_mode[0] )
          *tvin_mode[0] = 2;
      }
    }
    else if ( tvin_mode[0] )
    {
      *tvin_mode[0] = 0;
    }
    result = mode;
    if ( mode != tmode )
    {
      sysprintf(dword_F1C);
      if ( mode == 1 )
        sysprintf("TV in [NTSC]...\r\n");
      else
        sysprintf("TV in [PAL]...\r\n");
      TVD_Config(mode);
      result = mode;
      tmode = mode;
    }
  }
  return result;
}
// F1C: using guessed type int dword_F1C[5];
// CBC08: using guessed type char tvd_status;
// CBC0C: using guessed type int (*tvin_mode[2])();
// CBC14: using guessed type int mode;
// CBC18: using guessed type int tmode;
// CBC38: using guessed type int sysprintf(const char *, ...);

//----- (00000F58) --------------------------------------------------------
int f1c100s_tvd_Init()
{
  sysprintf("TVD Init...\r\n");
  return TVD_Config(2);
}
// CBC38: using guessed type int sysprintf(const char *, ...);

//----- (00000F80) --------------------------------------------------------
void __fastcall f1c100s_tvd_init(int a1)
{
  int v1; // r4

  v1 = a1;
  f1c100s_clk_init();
  BSP_TVD_init();
  BSP_TVD_input_select(0);
  BSP_TVD_set_fmt(0, 2);
  BSP_TVD_config(1, v1, 2);
  BSP_TVD_set_addr_y(0, &tvin_buff_y);
  BSP_TVD_set_addr_c(0, &tvin_buff_c);
  com_video_set_blue_flag(2);
  BSP_TVD_capture_on();
}

//----- (00000FE8) --------------------------------------------------------
int f1c100s_tvd_off()
{
  BSP_TVD_capture_off();
  tvd_status = 0;
  return Debe_tvdoff();
}
// CBC08: using guessed type char tvd_status;
// CBC1C: using guessed type int Debe_tvdoff(void);

//----- (0000100C) --------------------------------------------------------
int __fastcall f1c100s_tvd_set(int a1, int a2, int a3, int a4)
{
  int v4; // r7
  int v5; // r4
  int v6; // r5
  int v7; // r6

  v4 = a1;
  v5 = a2;
  v6 = a3;
  v7 = a4;
  tvd_dis_w = a1;
  tvd_dis_h = a2;
  tvd_dis_x = a3;
  tvd_dis_y = a4;
  tvd_status = 1;
  f1c100s_tvd_Init();
  return Debe_tvdset(v4, v5, v6, v7);
}
// CBC00: using guessed type __int16 tvd_dis_w;
// CBC02: using guessed type __int16 tvd_dis_h;
// CBC04: using guessed type __int16 tvd_dis_x;
// CBC06: using guessed type __int16 tvd_dis_y;
// CBC08: using guessed type char tvd_status;
// CBC20: using guessed type int __fastcall Debe_tvdset(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0000107C) --------------------------------------------------------
int __fastcall read16(unsigned __int16 *a1)
{
  return *a1;
}

//----- (0000108C) --------------------------------------------------------
int __fastcall read32(int a1)
{
  return *a1;
}

//----- (0000109C) --------------------------------------------------------
__int64 __fastcall read64(int a1)
{
  return *a1;
}

//----- (000010AC) --------------------------------------------------------
int __fastcall read8(unsigned __int8 *a1)
{
  return *a1;
}

//----- (000010BC) --------------------------------------------------------
int tvd_get_status()
{
  return tvd_status;
}
// CBC08: using guessed type char tvd_status;

//----- (000010CC) --------------------------------------------------------
_WORD *__fastcall write16(_WORD *result, int a2, __int16 a3)
{
  *result = a3;
  return result;
}

//----- (000010D4) --------------------------------------------------------
_DWORD *__fastcall write32(_DWORD *result, int a2, int a3)
{
  *result = a3;
  return result;
}

//----- (000010DC) --------------------------------------------------------
_QWORD *__fastcall write64(_QWORD *result, int a2, __int64 a3)
{
  *result = a3;
  return result;
}

//----- (000010E4) --------------------------------------------------------
_BYTE *__fastcall write8(_BYTE *result, int a2, char a3)
{
  *result = a3;
  return result;
}

// ALL OK, 47 function(s) have been successfully decompiled
