/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall TP_Init(int a1);
int __fastcall read16(unsigned __int16 *a1);
int __fastcall read32(int a1);
__int64 __fastcall read64(int a1);
int __fastcall read8(unsigned __int8 *a1);
_WORD *__fastcall write16(_WORD *result, int a2, __int16 a3);
_DWORD *__fastcall write32(_DWORD *result, int a2, int a3);
_QWORD *__fastcall write64(_QWORD *result, int a2, __int64 a3);
_BYTE *__fastcall write8(_BYTE *result, int a2, char a3);
// int __fastcall bsp_pwm0_io_set(_DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

void *TP_dev = &RTP_DEV; // weak
// extern _UNKNOWN CTP_DEV; weak
// extern _UNKNOWN RTP_DEV; weak


//----- (00000000) --------------------------------------------------------
int __fastcall TP_Init(int a1)
{
  if ( a1 == 127 )
  {
    bsp_pwm0_io_set(1);
    TP_dev = &CTP_DEV;
  }
  else
  {
    TP_dev = &RTP_DEV;
    bsp_pwm0_io_set(0);
  }
  return (*((int (**)(void))TP_dev + 1))();
}
// BC: using guessed type void *TP_dev;
// C8: using guessed type int __fastcall bsp_pwm0_io_set(_DWORD);

//----- (0000005C) --------------------------------------------------------
int __fastcall read16(unsigned __int16 *a1)
{
  return *a1;
}

//----- (0000006C) --------------------------------------------------------
int __fastcall read32(int a1)
{
  return *(_DWORD *)a1;
}

//----- (0000007C) --------------------------------------------------------
__int64 __fastcall read64(int a1)
{
  return *(_QWORD *)a1;
}

//----- (0000008C) --------------------------------------------------------
int __fastcall read8(unsigned __int8 *a1)
{
  return *a1;
}

//----- (0000009C) --------------------------------------------------------
_WORD *__fastcall write16(_WORD *result, int a2, __int16 a3)
{
  *result = a3;
  return result;
}

//----- (000000A4) --------------------------------------------------------
_DWORD *__fastcall write32(_DWORD *result, int a2, int a3)
{
  *result = a3;
  return result;
}

//----- (000000AC) --------------------------------------------------------
_QWORD *__fastcall write64(_QWORD *result, int a2, __int64 a3)
{
  *result = a3;
  return result;
}

//----- (000000B4) --------------------------------------------------------
_BYTE *__fastcall write8(_BYTE *result, int a2, char a3)
{
  *result = a3;
  return result;
}

// ALL OK, 9 function(s) have been successfully decompiled
